### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/miguelbalboa/rfid/master/library.json

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-home#1009]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /miguelbalboa/rfid/master/library.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5B5C1C2E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by ivankravets** [comment]
Should be fixed in the latest PlatformIO IDE 2.0
