### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by ThinCode2020** [platformio/platformio-home#1013]
PIO Core Call Error: "Error: Please specify name, url and vendor fields for C:\\Users\\Louis\\.platformio\\platforms\\atmelmegaavr\\boards\\package_thinary_index.json".

I am trying to create a new project, as soon as I open PIO and click new project. It gave an error above.

Before that, I copy a json file "package_thinary_index.json" into "C:\\Users\\Louis\\.platformio\\platforms\\atmelmegaavr\\boards\\".
I don't know how to install a new board. The Thinary Nano Every (Atmega4808) is my new board and I want to test it in PlatformIO.

I appreciate for any help.

Thank you,

Louis

**Comment by ThinCode2020** [comment]
Here is the "package_thinary_index.json" file:

`{
  "packages":[
    {
      "name":"thinary",
      "maintainer":"Thinary Electronic",
      "websiteURL":"http://thinary.cn",
      "email":"thinary@163.com",
      "help":{
      "online":"http://thinary.cn"
      },
      "platforms": [
        {
          "name": "Thinary AVR Boards",
          "architecture": "avr",
          "version": "1.0.0",
          "category": "Thinary",
          "url": "https://github.com/Thinary/ThinaryArduino/releases/download/1.0.0/thinary-megaavr-1.0.0.zip",
          "archiveFileName": "thinary-megaavr-1.0.0.zip",
          "checksum": "SHA-256:cc9b7471b970794b1c2bf04724431a6425a83cd11b6049a9ab61af961f5cf5f3",
          "size": "990906",
          "help": {
            "online": "https://github.com/Thinary/ThinaryArduino/issues"
          },
          "boards": [
            {
              "name": "Thinary Nano Every(ATmega4808)"
            }
          ],
          "toolsDependencies": [
            {
              "packager": "arduino",
              "name": "avr-gcc",
              "version": "7.3.0-atmel3.6.1-arduino5"
            },
            {
              "packager": "arduino",
              "name": "avrdude",
              "version": "6.3.0-arduino16"
            },
            {
              "packager": "arduino",
              "name": "arduinoOTA",
              "version": "1.3.0"
            }
          ]
        }
      ],
      "tools":[
        {
          "name": "avr-gcc",
          "version": "7.3.0-atmel3.6.1-arduino5",
          "systems": [
            {
              "size": "34462042",
              "checksum": "SHA-256:f4acd5531c6b82c715e2edfa0aadb13fb718b4095b3ea1aa1f7fbde680069639",
              "host": "arm-linux-gnueabihf",
              "archiveFileName": "avr-gcc-7.3.0-atmel3.6.1-arduino5-arm-linux-gnueabihf.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-arm-linux-gnueabihf.tar.bz2"
            },
            {
              "size": "39381972",
              "checksum": "SHA-256:dd9c70190be370a44fb47dab1514de6d8852b861dfa527964b65c740d8d50c10",
              "host": "aarch64-linux-gnu",
              "archiveFileName": "avr-gcc-7.3.0-atmel3.6.1-arduino5-aarch64-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-aarch64-pc-linux-gnu.tar.bz2"
            },
            {
              "size": "38492678",
              "checksum": "SHA-256:f48706317f04452544ab90e75bd1bb193f8af2cb1002f53aa702f27202c1b38f",
              "host": "x86_64-apple-darwin14",
              "archiveFileName": "avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-apple-darwin14.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-apple-darwin14.tar.bz2"
            },
            {
              "size": "53727984",
              "checksum": "SHA-256:6d4a5d089a36e5b5252befc73da204555b49e376ce7577ee19ca7f028b295830",
              "host": "i686-mingw32",
              "archiveFileName": "avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip"
            },
            {
              "size": "38710087",
              "checksum": "SHA-256:2ff12739d7ed09688d6b3c2c126e8df69b5bda1a07ab558799f0e576571e0e1d",
              "host": "i686-linux-gnu",
              "archiveFileName": "avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-pc-linux-gnu.tar.bz2"
            },
            {
              "size": "39114120",
              "checksum": "SHA-256:3effed8ffa1978b6e4a46f1aa2acc629e440b4d77244f71f9b79a916025206fb",
              "host": "x86_64-linux-gnu",
              "archiveFileName": "avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-x86_64-pc-linux-gnu.tar.bz2"
            }
          ]
	},
        {
          "name": "avrdude",
          "version": "6.3.0-arduino17",
          "systems": [
            {
              "size": "219631",
              "checksum": "SHA-256:2a8e68c5d803aa6f902ef219f177ec3a4c28275d85cbe272962ad2cd374f50d1",
              "host": "arm-linux-gnueabihf",
              "archiveFileName": "avrdude-6.3.0-arduino17-armhf-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-armhf-pc-linux-gnu.tar.bz2"
            },
            {
              "size": "229852",
              "checksum": "SHA-256:6cf948f751acfe7b96684537f2291c766ec8b54b4f7dc95539864821456fa9fc",
              "host": "aarch64-linux-gnu",
              "archiveFileName": "avrdude-6.3.0-arduino17-aarch64-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-aarch64-pc-linux-gnu.tar.bz2"
            },
            {
              "size": "279045",
              "checksum": "SHA-256:120cc9edaae699e7e9ac50b1b8eb0e7d51fdfa555bac54233c2511e6ee5418c9",
              "host": "x86_64-apple-darwin12",
              "archiveFileName": "avrdude-6.3.0-arduino17-x86_64-apple-darwin12.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-x86_64-apple-darwin12.tar.bz2"
            },
            {
              "size": "254271",
              "checksum": "SHA-256:accdfb920af2aabf4f7461d2ac73c0751760f525216dc4e7657427a78c60d13d",
              "host": "x86_64-linux-gnu",
              "archiveFileName": "avrdude-6.3.0-arduino17-x86_64-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-x86_64-pc-linux-gnu.tar.bz2"
            },
            {
              "size": "244550",
              "checksum": "SHA-256:5c8cc6c17db9300e1451fe41cd7178b0442b4490ee6fdbc0aed9811aef96c05f",
              "host": "i686-linux-gnu",
              "archiveFileName": "avrdude-6.3.0-arduino17-i686-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-i686-pc-linux-gnu.tar.bz2"
            },
            {
              "size": "328460",
              "checksum": "SHA-256:e99188873c7c5ad8f8f906f068c33600e758b2e36cce3adbd518a21bd266749d",
              "host": "i686-mingw32",
              "archiveFileName": "avrdude-6.3.0-arduino17-i686-w64-mingw32.zip",
              "url": "http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-i686-w64-mingw32.zip"
            }
          ]
        },
        {
          "name": "arduinoOTA",
          "version": "1.3.0",
          "systems": [
            {
              "size": "2633516",
              "checksum": "SHA-256:3e7f59d6fbc7a724598303f0d3289d0c4fd137a8973437980658379a024887b2",
              "host": "i686-linux-gnu",
              "archiveFileName": "arduinoOTA-1.3.0-linux_386.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/arduinoOTA-1.3.0-linux_386.tar.bz2"
            },
            {
              "size": "2716248",
              "checksum": "SHA-256:aa45ee2441ffc3a122daec5802941d1fa2ac47adf5c5c481b5e0daa4dc259ffa",
              "host": "x86_64-linux-gnu",
              "archiveFileName": "arduinoOTA-1.3.0-linux_amd64.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/arduinoOTA-1.3.0-linux_amd64.tar.bz2"
            },
            {
              "size": "2567435",
              "checksum": "SHA-256:1888587409b56aef4ba0ab0e6703b3dccba7cc3a022756ba9b908247e5d5a656",
              "host": "arm-linux-gnueabihf",
              "archiveFileName": "arduinoOTA-1.3.0-linux_arm.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/arduinoOTA-1.3.0-linux_arm.tar.bz2"
            },
            {
              "size": "2472427",
              "checksum": "SHA-256:835ed8f37cffac37e979d1b0f6041559592d3d98be52f0e8611b76c4858e4113",
              "host": "aarch64-linux-gnu",
              "archiveFileName": "arduinoOTA-1.3.0-linux_arm64.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/arduinoOTA-1.3.0-linux_arm64.tar.bz2"
            },
            {
              "size": "2766116",
              "checksum": "SHA-256:d5d0f82ff829c0e434d12a2ee640a6fbd78f893ab37782edbb8b5bf2359d119e",
              "host": "i386-apple-darwin11",
              "archiveFileName": "arduinoOTA-1.3.0-darwin_amd64.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/arduinoOTA-1.3.0-darwin_amd64.tar.bz2"
            },
            {
              "size": "2768948",
              "checksum": "SHA-256:051943844eee442460d2c709edefadca184287fffd2b6c100dd53aa742aa05f6",
              "host": "i686-mingw32",
              "archiveFileName": "arduinoOTA-1.3.0-windows_386.zip",
              "url": "http://downloads.arduino.cc/tools/arduinoOTA-1.3.0-windows_386.zip"
            }
          ]
        }
        ]
      }
   ]
}
`

**Comment by valeros** [comment]
Hi @ThinCode2020 ! You need to delete the file `C:\Users\Louis\.platformio\platforms\atmelmegaavr\boards\package_thinary_index.json` it shouldn't be there since `boards` folder must contain only valid board manifests.
