### ISSUE TITLE
Could not initialize project under windows

### ISSUE THREAD

**Issue by jwillner** [platformio/platformio-home#1017]
PIO Core Call Error: "The current working directory\n C:\\JoWi\\zephyr\\laird_peripheral \nwill be used for the project.\n\nThe next files/directories have been created in \u001b[36mC:\\JoWi\\zephyr\\laird_peripheral\u001b[0m\n\u001b[36minclude\u001b[0m - Put project header files here\n\u001b[36mlib\u001b[0m - Put here project specific (private) libraries\n\u001b[36msrc\u001b[0m - Put project source files here\n\u001b[36mplatformio.ini\u001b[0m - Project Configuration File\n\n\nError: Processing laird_bl654_dvk (platform: nordicnrf52; board: laird_bl654_dvk; framework: zephyr)\n-------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/laird_bl654_dvk.html\nPLATFORM: Nordic nRF52 4.3.0 > BL654 Development Kit\nHARDWARE: NRF52840 64MHz, 256KB RAM, 1MB Flash\nDEBUG: Current (jlink) On-board (cmsis-dap, jlink) External (blackmagic, stlink)\nPACKAGES: \n - framework-zephyr 2.20300.200623 (2.3.0) \n - framework-zephyr-canopennode 0.0.0-alpha+sha.5c6b0566d5 \n - framework-zephyr-civetweb 0.0.0-alpha+sha.99129c5efc \n - framework-zephyr-cmsis 0.0.0-alpha+sha.542b2296e6 \n - framework-zephyr-fatfs 0.0.0-alpha+sha.9ee6b9b951 \n - framework-zephyr-hal-nordic 0.0.0-alpha+sha.742d8fb839 \n - framework-zephyr-libmetal 0.0.0-alpha+sha.3c3c9ec83b \n - framework-zephyr-littlefs 0.0.0-alpha+sha.0aefdda69d \n - framework-zephyr-loramac-node 0.0.0-alpha+sha.29e516ec58 \n - framework-zephyr-lvgl 0.0.0-alpha+sha.74fc2e753a \n - framework-zephyr-mbedtls 0.0.0-alpha+sha.4bf099f125 \n - framework-zephyr-mcuboot 0.0.0-alpha+sha.e88113bbeb \n - framework-zephyr-mcumgr 0.0.0-alpha+sha.5885efb7ca \n - framework-zephyr-mipi-sys-t 0.0.0-alpha+sha.957d46bc3c \n - framework-zephyr-open-amp 0.0.0-alpha+sha.724f7e2a45 \n - framework-zephyr-openthread 0.0.0-alpha+sha.a83d18cf18 \n - framework-zephyr-segger 0.0.0-alpha+sha.6fcf61606d \n - framework-zephyr-tinycbor 0.0.0-alpha+sha.40daca97b4 \n - framework-zephyr-tinycrypt 0.0.0-alpha+sha.3e9a49d267 \n - framework-zephyr-trusted-firmware-m 0.0.0-alpha+sha.7de2daa196 \n - tool-cmake 3.16.4 \n - tool-dtc 1.4.7 \n - tool-ninja 1.9.0 \n - tool-sreccat 1.164.0 (1.64) \n - toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)\nPython 3.4 or greater required, but you have Python 2.7.18\n========================= [FAILED] Took 1.80 seconds ========================="

**Comment by valeros** [comment]
Hi @jwillner ! Looks like your PlatformIO virtual environment was created for Python 2.7, but Zephyr supports Python >=3.4 only.
- Close the IDE
- Make sure Python 3.x is the main Python installation in your system.
- Delete folder `C:\Users\YOUR_USER\.platformio\.penv`
- Open the IDE and wait until a new installation is completed
