### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by masoudjamali137** [platformio/platformio-home#1019]
PIO Core Call Error: "The current working directory C:\\Users\\Administrator\\Documents\\PlatformIO\\Projects\\M66-TEST will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Administrator\\Documents\\PlatformIO\\Projects\\M66-TEST\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Could not find a version that satisfies the requirement '>=4.8.3' for your system 'windows_amd64'"

**Comment by valeros** [comment]
Hi @masoudjamali137 ! What platform/framework you're using?
