### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by FelipeAlmeida43** [platformio/platformio-home#1022]
PIO Core Call Error: "Error: Could not load broken JSON: C:\\Users\\Felipe\\.platformio\\platforms\\espressif32\\boards\\magicbit.json"

**Comment by valeros** [comment]
The error is pretty descriptive, the manifest file for board `C:\Users\Felipe\.platformio\platforms\espressif32\boards\magicbit.json` is broken for some reason.

**Comment by FelipeAlmeida43** [comment]
I will try to unistall and install it again.
Tks.
