### ISSUE TITLE
Libraries: Installed

### ISSUE THREAD

**Issue by vkichline** [platformio/platformio-home#1025]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 281, in lib_list\n    lm = LibraryManager(storage_dir)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 41, in __init__\n    package_dir or self.config.get_optional_dir(\"globallib\")\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 604, in __init__\n    os.makedirs(self.package_dir)\n  File \"c:\\users\\van\\.platformio\\penv\\lib\\os.py\", line 157, in makedirs\n    mkdir(name, mode)\nWindowsError: [Error 183] Cannot create a file when that file already exists: 'E:\\\\Van\\\\Documents\\\\repos\\\\vkichline\\\\M5Sys\\\\Libraries\\\\.pio\\\\libdeps\\\\m5stack-fire'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core 5.0.1-dev. Please re-test with `pio upgrade --dev`.
