### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by luyulei-lyl** [platformio/platformio-home#1042]
PIO Core Call Error: "The current working directory\n C:\\Users\\luyulei\\Documents\\PlatformIO\\Projects\\200728-020758-espidf-blink \nwill be used for the project.\n\nThe next files/directories have been created in \u001b[36mC:\\Users\\luyulei\\Documents\\PlatformIO\\Projects\\200728-020758-espidf-blink\u001b[0m\n\u001b[36minclude\u001b[0m - Put project header files here\n\u001b[36mlib\u001b[0m - Put here project specific (private) libraries\n\u001b[36msrc\u001b[0m - Put project source files here\n\u001b[36mplatformio.ini\u001b[0m - Project Configuration File\n\n\nError: Processing esp32dev (platform: espressif32; framework: espidf; board: esp32dev)\n-------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\nPLATFORM: Espressif 32 1.12.4 > Espressif ESP32 Dev Module\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40001.200521 (4.0.1) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-idf 1.0.1 \n - tool-mconf 1.4060000.20190628 (406.0.0) \n - tool-ninja 1.9.0 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nReading CMake configuration...\n-- Found Git: C:/Program Files/Git/cmd/git.exe (found version \"2.27.0.windows.1\") \n-- mconf-idf version mconf-v4.6.0.0-idf-20190628-win32\n-- IDF_TARGET not set, using default target: esp32\n-- The C compiler identification is GNU 8.2.0\n-- The CXX compiler identification is GNU 8.2.0\n-- The ASM compiler identification is GNU\n-- Found assembler: C:/Users/luyulei/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe\n-- Check for working C compiler: C:/Users/luyulei/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe\n-- Check for working C compiler: C:/Users/luyulei/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Detecting C compile features\n-- Detecting C compile features - done\n-- Check for working CXX compiler: C:/Users/luyulei/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++.exe\n-- Check for working CXX compiler: C:/Users/luyulei/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++.exe -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Detecting CXX compile features\n-- Detecting CXX compile features - done\n-- Configuring incomplete, errors occurred!\nSee also \"C:/Users/luyulei/Documents/PlatformIO/Projects/200728-020758-espidf-blink/.pio/build/esp32dev/CMakeFiles/CMakeOutput.log\".\nCMake Error at .pio/build/esp32dev/CMakeFiles/git-data/grabRef.cmake:41 (file):\n  file failed to open for reading (No such file or directory):\n\n    C:/Users/luyulei/Documents/PlatformIO/Projects/200728-020758-espidf-blink/.pio/build/esp32dev/CMakeFiles/git-data/head-ref\nCall Stack (most recent call first):\n  C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/third_party/GetGitRevisionDescription.cmake:80 (include)\n  C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/third_party/GetGitRevisionDescription.cmake:90 (get_git_head_revision)\n  C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/build.cmake:68 (git_describe)\n  C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/build.cmake:159 (__build_get_idf_git_revision)\n  C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/idf.cmake:43 (__build_init)\n  C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/project.cmake:7 (include)\n  CMakeLists.txt:2 (include)\n\n\nCMake Error at C:/Users/luyulei/.platformio/packages/framework-espidf/tools/cmake/project.cmake:344 (__project_get_revision):\n  Unknown CMake command \"__project_get_revision\".\nCall Stack (most recent call first):\n  CMakeLists.txt:3 (project)\n========================= [FAILED] Took 12.69 seconds ========================="

**Comment by ivankravets** [comment]
Please update all dev-platforms and restart VSCode.
