### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by easyvolts** [platformio/platformio-home#1045]
PIO Core Call Error: "PlatformManager: Installing arduino-esp32\r\narduino-esp32 @ 3da04ce has been successfully installed!\r\n\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 323, in platform_install\r\n    force=force,\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 86, in install\r\n    p = PlatformFactory.newPlatform(platform_dir)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 273, in newPlatform\r\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 562, in __init__\r\n    self._manifest = fs.load_json(manifest_path)\r\n  File \"c:\\users\\ahha7\\.platformio\\penv\\lib\\site-packages\\platformio\\fs.py\", line 54, in load_json\r\n    with open(file_path, \"r\") as f:\r\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\ahha7\\\\.platformio\\\\platforms\\\\arduino-esp32\\\\platform.json'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by valeros** [comment]
Looks like you have a broken development platform here `C:\\Users\\ahha7\\.platformio\\platforms\\arduino-esp32`, try to delete this folder.
