### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by hasenradball** [platformio/platformio-home#1055]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\Frank\\\\.platformio\\\\platforms\\\\arduino-esp32\\\\platform.json'","type":"FileNotFoundError"}

**Comment by valeros** [comment]
Looks like you have a broken development platform here `C:\\Users\\Frank\\.platformio\\platforms\\arduino-esp32`, try to delete this folder.
