### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Kezii** [platformio/platformio-home#1057]
PIO Core Call Error: "The current working directory /home/kezi/Documents/PlatformIO/Projects/loadcell will be used for the project.\n\nThe next files/directories have been created in /home/kezi/Documents/PlatformIO/Projects/loadcell\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'nucleo_g474re'"

**Comment by ivankravets** [comment]
Please update all dev-platforms and restart VSCode.
