### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by Caspar311** [platformio/platformio-home#1065]
PIO Core Call Error: "Platform C:\\Users\\Florian Triphaus\\.platformio\\platforms\\espressif32\r\n--------\r\nUpdating espressif32                     @ 1.11.1         [1.12.4]\r\nUninstalling espressif32 @ 1.11.1: \t[OK]\r\nPlatformManager: Installing espressif32 @ 1.12.4\r\nDownloading...\r\nUnpacking...\r\nespressif32 @ 1.12.4 has been successfully installed!\r\nUpdating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]\r\nUpdating tool-esptoolpy                  @ 1.20600.0      [Up-to-date]\r\nUpdating tool-openocd-esp32              @ 1.1000.20190708[Up-to-date]\r\nUpdating tool-mkspiffs                   @ 2.230.0        [Up-to-date]\r\n\n\nError: Traceback (most recent call last):\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 410, in platform_update\r\n    pm.update(platform, only_packages=only_packages, only_check=only_check)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 154, in update\r\n    self.cleanup_packages(list(p.packages))\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 167, in cleanup_packages\r\n    p = PlatformFactory.newPlatform(manifest[\"__pkg_dir\"])\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 273, in newPlatform\r\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 562, in __init__\r\n    self._manifest = fs.load_json(manifest_path)\r\n  File \"C:\\Users\\Florian Triphaus\\.platformio\\penv\\lib\\site-packages\\platformio\\fs.py\", line 53, in load_json\r\n    with open(file_path, \"r\") as f:\r\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Florian Triphaus\\\\.platformio\\\\platforms\\\\espressif8266\\\\platform.json'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by valeros** [comment]
Hi @Caspar311 ! Looks like you have a missing platform manifest here `C:\\Users\\PK_SOFTTECH\\.platformio\\platforms\\espressif8266\\platform.json`. Please delete the entire `espressif8266` folder and try again.
