### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by NotVexed** [platformio/platformio-home#1067]
PIO Core Call Error: "The current working directory C:\\dev\\OriLearning will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\dev\\OriLearning\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Unknown board ID 'teensy41'"

**Comment by valeros** [comment]
Hi @NotVexed ! What version of the `teensy` platform is installed in your system?

**Comment by NotVexed** [comment]
I have fixed it, by updating the teensy library.
