### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by xinstein** [platformio/platformio-home#1110]
PIO Core Call Error: "The current working directory F:\\xinst\\Documents\\PlatformIO\\Projects\\test8051 will be used for the project.\r\n\r\nThe next files/directories have been created in F:\\xinst\\Documents\\PlatformIO\\Projects\\test8051\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing stc89c52rc (platform: intel_mcs51; board: stc89c52rc)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nAttributeError: 'NoneType' object has no attribute 'version':\r\n  File \"C:\\users\\xinst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 169:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\xinst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\xinst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\users\\xinst\\.platformio\\platforms\\intel_mcs51\\builder\\main.py\", line 120:\r\n    target_firm = env.BuildProgram()\r\n  File \"C:\\Users\\xinst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\users\\xinst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 61:\r\n    env.ProcessProgramDeps()\r\n  File \"C:\\Users\\xinst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\users\\xinst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 104:\r\n    env.PrintConfiguration()\r\n  File \"C:\\Users\\xinst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\users\\xinst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\pioplatform.py\", line 222:\r\n    _get_plaform_data(),\r\n  File \"C:\\users\\xinst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\pioplatform.py\", line 152:\r\n    % (platform.title, pkg_metadata.version or platform.version)\r\n========================== [FAILED] Took 1.81 seconds =========================="

**Comment by valeros** [comment]
What version of PlatformIO Core do you use?
