### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by kephaII** [platformio/platformio-home#1124]
PIO Core Call Error: "The current working directory C:\\Users\\kepha\\Documents\\PlatformIO\\Projects\\200822-095408-arduino-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\kepha\\Documents\\PlatformIO\\Projects\\200822-095408-arduino-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing lightblue-bean (platform: atmelavr; framework: arduino; board: lightblue-bean)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\n  File \"C:\\Users\\kepha\\.platformio\\platforms\\atmelavr\\builder\\main.py\", line 30\r\n\r\n    print \"Please unplug/plug device ...\"\r\n\r\n                                        ^\r\n\r\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"Please unplug/plug device ...\")?\r\n\r\n========================== [FAILED] Took 0.95 seconds ==========================\r\n\r\nEnvironment           Status    Duration\r\n--------------------  --------  ------------\r\nlightblue-bean        FAILED    00:00:00.946\r\nbluefruitmicro        IGNORED\r\ndigispark-pro         IGNORED\r\ndigispark-pro32       IGNORED\r\ndigispark-pro64       IGNORED\r\npro8MHzatmega328      IGNORED\r\nengduinov3            IGNORED\r\nethernet              IGNORED\r\nfeather32u4           IGNORED\r\nflora8                IGNORED\r\nleonardo              IGNORED\r\nmegaatmega2560        IGNORED\r\nmicro                 IGNORED\r\nmightycore1284        IGNORED\r\nmoteinomega           IGNORED\r\npanStampAVR           IGNORED\r\n1284p16m              IGNORED\r\nquirkbot              IGNORED\r\nreprap_rambo          IGNORED\r\nrobotControl          IGNORED\r\nrobotMotor            IGNORED\r\nsanguino_atmega1284p  IGNORED\r\nsparkfun_promicro16   IGNORED\r\nuno                   IGNORED\r\ngemma                 IGNORED\r\nattiny24              IGNORED\r\nwildfirev3            IGNORED\r\nyun                   IGNORED\r\natmega328pb           IGNORED\r\n==================== 1 failed, 0 succeeded in 00:00:00.946 ===================="

**Comment by valeros** [comment]
Hi @kephaII ! Looks like you have an outdated `atmelavr` platform. Please update your platforms in the [PlatformIO Home](https://docs.platformio.org/en/latest/home/index.html#) menu or run `pio platform update atmelavr` in the IDE terminal.
