### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by syf1981** [platformio/platformio-home#1125]
PIO Core Call Error: "The current working directory C:\\Users\\HAI_YFS\\Documents\\PlatformIO\\Projects\\200822-163219-esp8266-rtos-sdk-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\HAI_YFS\\Documents\\PlatformIO\\Projects\\200822-163219-esp8266-rtos-sdk-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError:"

**Comment by valeros** [comment]
Hi @saiquaan5! Unfortunately, the log you provided doesn't contain enough information to help you. Please provide more information about the issue.
