### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by phplego** [platformio/platformio-home#1130]
PIO Core Call Error: "The current working directory /home/dub/Documents/PlatformIO/Projects/nrf52840_CLUE_test will be used for the project.\n\nThe next files/directories have been created in /home/dub/Documents/PlatformIO/Projects/nrf52840_CLUE_test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'adafruit_clue_nrf52840'"

**Comment by valeros** [comment]
Hi @phplego ! Looks like you have an outdated version of the `nordicnrf52` platform. Please run `pio platform update nordicnrf52` in the IDE terminal and try again.
