### ISSUE TITLE
Libraries: Could not uninstall library

### ISSUE THREAD

**Issue by jackthese** [platformio/platformio-home#1132]
PIO Core Call Error: "Library Storage: C:\\Users\\jackr\\.platformio\\lib\r\n\n\nError: Could not find a package with 'C:\\Users\\jackr\\.platformio\\lib\\Adafruit STMPE610' requirements for your system 'windows_amd64'"

I just installed it. This is an irritating "me too" library that is stupidly forced on you by Adafruit, with no option to not install it within PIO. This is one instance where the Arduino IDE is better than PIO.

**Comment by ivankravets** [comment]
See installation instruction. Please use as `lib_deps`. https://platformio.org/lib/show/377/Adafruit%20STMPE610/installation
