### ISSUE TITLE
Missing west.yml Zephyr Framework

### ISSUE THREAD

**Issue by InfotecDehmer** [platformio/platformio-home#1143]
Creating Project with Zephyr RTOS using the Project Wizard fails due to missing west.yml . Tried different examples with "Project Examples" Dialog with Zephyr included and all failed with the same error.

System:  Windows 10.0.19041
Visual Studio Code: 1.48.1
PlatformIO: 4.3.4

PIO Core Call Error: "The current working directory C:\\Users\\bened\\Documents\\PlatformIO\\Projects\\200825-102250-zephyr-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\bened\\Documents\\PlatformIO\\Projects\\200825-102250-zephyr-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing blackpill_f103c8 (platform: ststm32; framework: zephyr; board: blackpill_f103c8)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ ~1.80201.0\r\ntoolchain-gccarmnoneeabi @ 1.80201.190214 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/blackpill_f103c8.html\r\nPLATFORM: ST STM32 8.0.0 > BlackPill F103C8\r\nHARDWARE: STM32F103C8T6 72MHz, 20KB RAM, 64KB Flash\r\nDEBUG: Current (stlink) External (blackmagic, jlink, stlink)\r\nPACKAGES: \r\n - framework-zephyr 2.20300.200823 (2.3.0) \r\n - framework-zephyr-canopennode 0.0.0-alpha+sha.5c6b0566d5 \r\n - framework-zephyr-civetweb 0.0.0-alpha+sha.99129c5efc \r\n - framework-zephyr-cmsis 0.0.0-alpha+sha.542b2296e6 \r\n - framework-zephyr-fatfs 0.0.0-alpha+sha.9ee6b9b951 \r\n - framework-zephyr-hal-st 0.0.0-alpha+sha.5b3ec3e182 \r\n - framework-zephyr-hal-stm32 0.0.0-alpha+sha.d1bc80d021 \r\n - framework-zephyr-libmetal 0.0.0-alpha+sha.3c3c9ec83b \r\n - framework-zephyr-littlefs 0.0.0-alpha+sha.0aefdda69d \r\n - framework-zephyr-loramac-node 0.0.0-alpha+sha.29e516ec58 \r\n - framework-zephyr-lvgl 0.0.0-alpha+sha.74fc2e753a \r\n - framework-zephyr-mbedtls 0.0.0-alpha+sha.4bf099f125 \r\n - framework-zephyr-mcuboot 0.0.0-alpha+sha.e88113bbeb \r\n - framework-zephyr-mcumgr 0.0.0-alpha+sha.5885efb7ca \r\n - framework-zephyr-mipi-sys-t 0.0.0-alpha+sha.957d46bc3c \r\n - framework-zephyr-open-amp 0.0.0-alpha+sha.724f7e2a45 \r\n - framework-zephyr-openthread 0.0.0-alpha+sha.a83d18cf18 \r\n - framework-zephyr-segger 0.0.0-alpha+sha.6fcf61606d \r\n - framework-zephyr-tinycbor 0.0.0-alpha+sha.40daca97b4 \r\n - framework-zephyr-tinycrypt 0.0.0-alpha+sha.3e9a49d267 \r\n - framework-zephyr-trusted-firmware-m 0.0.0-alpha+sha.7de2daa196 \r\n - tool-cmake 3.16.4 \r\n - tool-dtc 1.4.7 \r\n - tool-ninja 1.9.0 \r\n - toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)\r\nReading CMake configuration...\r\nError: Couldn't find 'west.yml'\r\n========================= [FAILED] Took 63.19 seconds =========================\r\n\r\nEnvironment       Status    Duration\r\n----------------  --------  ------------\r\nblackpill_f103c8  FAILED    00:01:03.192\r\nnucleo_f030r8     IGNORED\r\nnucleo_l073rz     IGNORED\r\nnucleo_g474re     IGNORED\r\n==================== 1 failed, 0 succeeded in 00:01:03.192 ===================="

**Comment by valeros** [comment]
Hi @InfotecDehmer ! That's really strange
- Is there `west.yml` file in `C:\Users\bened\.platformio\packages\framework-zephyr` folder?
- Do you have any global installation of Zephyr framework in your system?
