### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/teemuatlut/TMCStepper/master/library.json

### ISSUE THREAD

**Issue by sternapeg** [platformio/platformio-home#1144]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /teemuatlut/TMCStepper/master/library.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9dc804290>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by valeros** [comment]
Hi @sternapeg ! Is there any chance that Github is blocked by your ISP?
