### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by zhafedee** [platformio/platformio-home#1146]
PIO Core Call Error: "Error: Invalid 'C:\\Users\\Vic_fretz\\Documents\\GitHub\\HIngePL-2k\\HingePL-2K\\platformio.ini' (project configuration file): 'While reading from 'C:\\\\Users\\\\Vic_fretz\\\\Documents\\\\GitHub\\\\HIngePL-2k\\\\HingePL-2K\\\\platformio.ini' [line 18]: option 'lib_deps' in section 'env:nodemcuv2' already exists'"

**Comment by valeros** [comment]
Please delete duplicated lib_deps field in nodemcuv2 environment.

**Comment by zhafedee** [comment]
Thanks I did it nd it worked already
