### ISSUE TITLE
Error occurred while requesting content from https://api.github.com/repos/platformio/platform-windows_x86/releases

### ISSUE THREAD

**Issue by liuzewen2** [platformio/platformio-home#1147]
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by valeros** [comment]
Hi @liuzewen2 ! Do you use a proxy? Have you tried to set up it as described in https://docs.platformio.org/en/latest/integration/ide/vscode.html#proxy-server-support?
