### ISSUE TITLE
Could not initialize project for RemRam_v1 Board

### ISSUE THREAD

**Issue by jeffstaley** [platformio/platformio-home#115]
Trying to create a project for the following board "RemRam_v1" produces the following error:

PIO Core Call Error: "The current working directory /Users/jeffy/Misc/Building_stuff/3D-Printing/CoreXY/Core_XY_Build/firmware_MarlinPlatformIO will be used for the project.\n\nThe next files/directories have been created in /Users/jeffy/Misc/Building_stuff/3D-Printing/CoreXY/Core_XY_Build/firmware_MarlinPlatformIO\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing remramBoard (platform: atmelavr; board: remramBoard; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/remramBoard.html\nPLATFORM: Atmel AVR 1.15.0 > REMRAM_V1\nHARDWARE: STM32F765VI 24MHz, 512KB RAM, 2MB Flash\nPACKAGES: toolchain-atmelavr 1.50400.190710 (5.4.0), framework-arduinoavr 4.1.2\nKeyError: \"Invalid board option 'build.core'\":\n  File \"/Users/jeffy/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py\", line 151:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 605:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 286:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/Users/jeffy/.platformio/platforms/atmelavr/builder/main.py\", line 155:\n    target_elf = env.BuildProgram()\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/jeffy/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py\", line 115:\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/jeffy/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py\", line 319:\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 668:\n    return method(*args, **kw)\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 605:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/Users/jeffy/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 286:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/Users/jeffy/.platformio/platforms/atmelavr/builder/frameworks/arduino.py\", line 87:\n    join(FRAMEWORK_DIR, \"cores\", env.BoardConfig().get(\"build.core\"))\n  File \"/Users/jeffy/.platformio/penv/lib/python3.7/site-packages/platformio/managers/platform.py\", line 731:\n    raise KeyError(\"Invalid board option '%s'\" % path)\n========================== [FAILED] Took 0.59 seconds =========================="

**Comment by ivankravets** [comment]
THis is ST STM 32 dev platform, not AVR. See https://docs.platformio.org/en/latest/boards/ststm32/remram_v1.html

use 
```ini
[env:remram_v1]
platform = ststm32
board = remram_v1
```
