### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/sstaub/Ticker/master/library.json

### ISSUE THREAD

**Issue by cwl0127** [platformio/platformio-home#1151]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sstaub/Ticker/master/library.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025C6993EE48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by valeros** [comment]
Looks like an issue with Github infrastructure. Please try again later.
