### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by MartinPoupa** [platformio/platformio-home#116]
PIO Core Call Error: "Error: Unknown development platform '/Users/martinpoupa/.platformio/platforms/atmelavr'"

There is not this directory. I tried make it there, it give my long error.
I think there must be some configuration files for boards but I don't know where I can take it. 

I use atom and my os is macos

Can you help me?
thenks

**Comment by ivankravets** [comment]
Please remove `/Users/martinpoupa/.platformio/platforms/atmelavr` folder and restart VSCode.

**Comment by MartinPoupa** [comment]
thenks
