### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Fliptron** [platformio/platformio-home#1161]
PIO Core Call Error: "framework-stm32cube @ 2.0.200813 has been successfully installed!\r\nPackageManager: Installing tool-ldscripts-ststm32 @ ~0.1.0\r\ntool-ldscripts-ststm32 @ 0.1.0 has been successfully installed!\r\n======================== [SUCCESS] Took 183.62 seconds ========================"

**Comment by valeros** [comment]
Hi @Fliptron! Unfortunately, the log you provided doesn't contain enough information to help you. Please provide more information about the issue.

**Comment by Fliptron** [comment]
Unfortunately, the only additional info I can provide is that I was installing the above mentioned package, and although it reports success, it also popped up an error box, with a submit button to report an error. So I clicked the submit button. I think I was installing for STM32F303CB generic on a Window 7 Pro x64 system.

**Comment by valeros** [comment]
Are you able to create a new project or the problem still persists?
