### ISSUE TITLE
Libraries: Search

### ISSUE THREAD

**Issue by hacker5510** [platformio/platformio-home#1171]
PIO Core Call Error: "'utf-8' codec can't decode byte 0xa8 in position 1567: invalid start byte"

**Comment by valeros** [comment]
Hi @hacker5510 ! Could you please share some steps to reproduce the issue? What library were you trying to install/search?

**Comment by hacker5510** [comment]
@valeros 

1.Click PIO Home Button
2.Click Tag : Esp32
 
![image](https://user-images.githubusercontent.com/18069281/91976974-77bafb80-ed54-11ea-9940-f13d658a3b9b.png)

**Comment by valeros** [comment]
Unfortunately, I cannot reproduce the issue. Do you have any non-unicode symbols in your username?

**Comment by hacker5510** [comment]
@valeros Thanks you.:-)

**Comment by valeros** [comment]
Have you resolved the issue? Would be great if you could add some comments on your solution for other users.
