### ISSUE TITLE
Error occurred while requesting content from https://bitbucket.org/fmalpartida/new-liquidcrystal/raw/integration/library.json

### ISSUE THREAD

**Issue by mlokhandwala** [platformio/platformio-home#1173]
403 Client Error: Forbidden for url: https://bitbucket.org/fmalpartida/new-liquidcrystal/raw/integration/library.json

**Comment by valeros** [comment]
Hi @mlokhandwala ! Looks like this library https://bitbucket.org/fmalpartida/new-liquidcrystal is no longer available.
