### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by ceerqingtingml** [platformio/platformio-home#1176]
PIO Core Call Error: "framework-arduinoespressif32 @ 3.10004.200129 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~3.30102.0\ntool-scons @ 3.30102.0 has been successfully installed!\n========================= [SUCCESS] Took 44.62 seconds ========================="

**Comment by valeros** [comment]
Hi @ceerqingtingml! Unfortunately, the log you provided doesn't contain enough information to help you. Please provide more information about the issue.
