### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by Kyck-02** [platformio/platformio-home#1178]
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 391, in platform_update\r\n    and not PlatformFactory.newPlatform(pkg_dir).are_outdated_packages()\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 355, in are_outdated_packages\r\n    if self.pm.outdated(manifest[\"__pkg_dir\"], requirements):\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 641, in outdated\r\n    latest = self.get_latest_repo_version(\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 114, in get_latest_repo_version\r\n    for versions in PackageRepoIterator(name, self.repositories):\r\n  File \"c:\\users\\w electronics\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 41, in __init__\r\n    assert isinstance(repositories, list)\r\nAssertionError\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Please upgrade PlatformIO Core to the latest version:

VSCode > Bottom Toolbar (blue) > Terminal Icon > type `pio upgrade`. Restart VSCode.
