### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by Sheridan-Tech** [platformio/platformio-home#1179]
PIO Core Call Error: "Platform Manager: Installing NXP Arduino LPC176x\r\n\n\nError: Could not find the package with 'NXP Arduino LPC176x' requirements for your system 'windows_amd64'"

**Comment by valeros** [comment]
Hi @Sheridan-Tech ! There is no such platform with name `NXP Arduino LPC176x`, probably you need to specify a link to repository instead.
