### ISSUE TITLE
Libraries: Could not uninstall library

### ISSUE THREAD

**Issue by WernerNachbaur** [platformio/platformio-home#1183]
PIO Core Call Error: "Library Storage: C:\\Users\\werne\\.platformio\\lib\nLibrary Manager: Removing Domotica @ 1.0.0\r\nLibrary Manager: Removing dependencies...\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 16, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib\\command.py\", line 227, in lib_uninstall\n    library: lm.uninstall(library, silent=silent) for library in libraries\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib\\command.py\", line 227, in <dictcomp>\n    library: lm.uninstall(library, silent=silent) for library in libraries\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\_uninstall.py\", line 29, in uninstall\n    return self._uninstall(spec, silent, skip_dependencies)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\_uninstall.py\", line 46, in _uninstall\n    self.uninstall_dependencies(pkg, silent)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\library.py\", line 102, in uninstall_dependencies\n    name=dependency.get(\"name\"), requirements=dependency.get(\"version\")\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\meta.py\", line 117, in __init__\n    self.requirements = requirements\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\meta.py\", line 162, in requirements\n    else semantic_version.SimpleSpec(str(value))\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\semantic_version\\base.py\", line 610, in __init__\n    self.clause = self._parse_to_clause(expression)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\semantic_version\\base.py\", line 975, in _parse_to_clause\n    return cls.Parser.parse(expression)\n  File \"c:\\users\\werne\\.platformio\\penv\\lib\\site-packages\\semantic_version\\base.py\", line 995, in parse\n    raise ValueError(\"Invalid simple block %r\" % block)\nValueError: Invalid simple block 'https://github.com/madpilot/mDNSResolver'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/issues/3663
