### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by javierdc** [platformio/platformio-home#1187]
PIO Core Call Error: "Platform \u001b[36mC:\\Users\\javie\\.platformio\\platforms\\nxplpc-arduino-lpc176x@src-de6b279104eee6e886c6740cfbf2debe\u001b[0m\n--------\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 421, in platform_update\n    platform, only_packages=only_packages, only_check=only_check, silent=silent\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\platform.py\", line 98, in update\n    pkg = self.get_package(from_spec)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\base.py\", line 229, in get_package\n    spec = self.ensure_spec(spec)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\base.py\", line 100, in ensure_spec\n    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\meta.py\", line 119, in __init__\n    self._parse(raw)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\meta.py\", line 221, in _parse\n    raw = parser(raw)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\meta.py\", line 238, in _parse_requirements\n    self.requirements = tokens[1].strip()\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\meta.py\", line 162, in requirements\n    else semantic_version.SimpleSpec(str(value))\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\semantic_version\\base.py\", line 618, in __init__\n    self.clause = self._parse_to_clause(expression)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\semantic_version\\base.py\", line 1014, in _parse_to_clause\n    return cls.Parser.parse(expression)\n  File \"c:\\users\\javie\\.platformio\\penv\\lib\\site-packages\\semantic_version\\base.py\", line 1034, in parse\n    raise ValueError(\"Invalid simple block %r\" % block)\nValueError: Invalid simple block 'src-de6b279104eee6e886c6740cfbf2debe'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/issues/3663
