### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by ens1985** [platformio/platformio-home#1199]
PIO Core Call Error: "Library Storage: C:\\Users\\enson\\.platformio\\lib\r\nUpdating EspMQTTClient                   @ 1.8.0          [1.9.0]\r\nUninstalling EspMQTTClient @ 1.8.0: \t[OK]\r\nLooking for EspMQTTClient library in registry\r\nFound: https://platformio.org/lib/show/5956/EspMQTTClient\r\nLibraryManager: Installing id=5956 @ 1.9.0\r\n\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 538, in _install_from_tmp_dir\r\n    assert tmp_semver and tmp_semver in semantic_version.SimpleSpec(\r\nAssertionError: Package version 1.8.0 doesn't satisfy requirements 1.9.0\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 260, in lib_update\r\n    lm.update(library, only_check=only_check)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 810, in update\r\n    self.install(name, latest, after_update=True)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 275, in install\r\n    pkg_dir = BasePkgManager.install(\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 704, in install\r\n    pkg_dir = self._install_from_piorepo(name, requirements)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 126, in _install_from_piorepo\r\n    return self._install_from_url(\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 499, in _install_from_url\r\n    return self._install_from_tmp_dir(_tmp_dir, requirements)\r\n  File \"c:\\users\\enson\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 542, in _install_from_tmp_dir\r\n    assert tmp_manifest[\"version\"] == requirements, mismatch_error\r\nAssertionError: Package version 1.8.0 doesn't satisfy requirements 1.9.0\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Please upgrade PlatformIO Core to the latest version. Open PlatformIO CLI and type `pio upgrade`.
