### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by tigertail100** [platformio/platformio-home#1201]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/platformio/commands/lib/command.py\", line 258, in lib_update\n    lm = LibraryPackageManager(storage_dir)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/platformio/package/manager/library.py\", line 27, in __init__\n    PackageType.LIBRARY, package_dir or get_project_global_lib_dir()\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/platformio/package/manager/base.py\", line 54, in __init__\n    self.package_dir = self.ensure_dir_exists(package_dir)\n  File \"/home/ian/.platformio/penv/lib/python3.6/site-packages/platformio/package/manager/base.py\", line 94, in ensure_dir_exists\n    os.makedirs(path)\n  File \"/usr/lib/python3.6/os.py\", line 220, in makedirs\n    mkdir(name, mode)\nFileExistsError: [Errno 17] File exists: '/home/ian/.platformio/penv/bin/.pio/libdeps/heltec_wifi_kit_32'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core 5.0.1-dev. Please re-test with `pio upgrade --dev`.
