### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by ek071391** [platformio/platformio-home#1202]
PIO Core Call Error: "The current working directory /Users/ed/Documents/PlatformIO/Projects/BTT_Marlin_9_6_20  will be used for the project.\n\nThe next files/directories have been created in /Users/ed/Documents/PlatformIO/Projects/BTT_Marlin_9_6_20 \ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing genericSTM32F103RC (platform: ststm32; board: genericSTM32F103RC; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nFileNotFoundError: [Errno 2] No such file or directory: '/Users/ed/Documents/PlatformIO/Projects/BTT_Marlin_9_6_20':\n  File \"/Users/ed/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py\", line 159:\n    env.LoadPioPlatform()\n  File \"/Users/ed/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/ed/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/pioplatform.py\", line 102:\n    board_config = env.BoardConfig()\n  File \"/Users/ed/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/ed/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/pioplatform.py\", line 46:\n    with fs.cd(env.subst(\"$PROJECT_DIR\")):\n  File \"/Users/ed/.platformio/penv/lib/python3.7/site-packages/platformio/fs.py\", line 36:\n    os.chdir(self.new_path)\n========================== [FAILED] Took 0.49 seconds =========================="

**Comment by ivankravets** [comment]
Please restart VSCode - should be fixed

**Comment by ek071391** [comment]
Thank you
