### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by ksirirux** [platformio/platformio-home#1203]
PIO Core Call Error: "The current working directory C:\\Users\\admin\\Documents\\PlatformIO\\Projects\\test_module will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\admin\\Documents\\PlatformIO\\Projects\\test_module\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp-wrover16 (platform: atmelavr; board: esp-wrover16; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/esp-wrover16.html\r\nPLATFORM: Atmel AVR (2.2.0) > Espressif esp-wrover16\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 16MB Flash\r\nPACKAGES: \r\n - toolchain-atmelavr 1.50400.190710 (5.4.0)\r\nAssertionError: :\r\n  File \"C:\\Users\\admin\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 169:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\admin\\.platformio\\packages\\tool-scons\\scons-local-4.0.1\\SCons\\Script\\SConscript.py\", line 598:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\admin\\.platformio\\packages\\tool-scons\\scons-local-4.0.1\\SCons\\Script\\SConscript.py\", line 287:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\admin\\.platformio\\platforms\\atmelavr\\builder\\main.py\", line 161:\r\n    target_elf = env.BuildProgram()\r\n  File \"C:\\Users\\admin\\.platformio\\packages\\tool-scons\\scons-local-4.0.1\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\admin\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 61:\r\n    env.ProcessProgramDeps()\r\n  File \"C:\\Users\\admin\\.platformio\\packages\\tool-scons\\scons-local-4.0.1\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\admin\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 127:\r\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\n  File \"C:\\Users\\admin\\.platformio\\packages\\tool-scons\\scons-local-4.0.1\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\admin\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 342:\r\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\r\n  File \"C:\\Users\\admin\\.platformio\\packages\\tool-scons\\scons-local-4.0.1\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\admin\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\pioplatform.py\", line 59:\r\n    assert p.frameworks and framework in p.frameworks\r\n========================== [FAILED] Took 1.25 seconds =========================="

**Comment by valeros** [comment]
`esp-wrover16` and `espidf` as the framework can only be used with the `espressif32` development platform.
