### ISSUE TITLE
Could not update platform

### ISSUE THREAD

**Issue by ChrisKal** [platformio/platformio-home#1208]
PIO Core Call Error: "Platform C:\\Users\\chrisk\\.platformio\\platforms\\espressif32\r\n--------\n\n\nError: Could not find a package with 'C:\\Users\\chrisk\\.platformio\\platforms\\espressif32' requirements for your system 'windows_amd64'"

**Comment by valeros** [comment]
Hi @ChrisKal ! Looks like you're using an outdated version of `platformio-core`. Please open a terminal window in PlatformIO IDE and run `pio ugrade`

**Comment by ChrisKal** [comment]
Thanks
