### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by tgreif** [platformio/platformio-home#1209]
PIO Core Call Error: "The current working directory\n C:\\Users\\thomas.greif\\Documents\\PlatformIO\\Projects\\200907-164249-az-delivery-devkit-v4 \nwill be used for the project.\n\nThe next files/directories have been created in \u001b[36mC:\\Users\\thomas.greif\\Documents\\PlatformIO\\Projects\\200907-164249-az-delivery-devkit-v4\u001b[0m\n\u001b[36minclude\u001b[0m - Put project header files here\n\u001b[36mlib\u001b[0m - Put here project specific (private) libraries\n\u001b[36msrc\u001b[0m - Put project source files here\n\u001b[36mplatformio.ini\u001b[0m - Project Configuration File\n\n\nError: Could not install package 'platformio/toolchain-xtensa32 @ ~2.50200.0' for 'windows_amd64' system"

**Comment by valeros** [comment]
Hi @tgreif ! Looks like you're using an outdated version of `platformio-core`. Please open a terminal window in PlatformIO IDE and run `pio ugrade`
