### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by levsanduo** [platformio/platformio-home#1212]
PIO Core Call Error: "Library Storage: C:\\Users\\Александр\\Documents\\PlatformIO\\Projects\\MainFramework\\.pio\\libdeps\\esp12e\nLibrary Manager: Installing me-no-dev/ESPAsyncTCP @ ^1.2.2\nUnpacking\nUnpacking\nLibrary Manager: Warning! Package Mirror: 'ascii' codec can't decode byte 0xc0 in position 7: ordinal not in range(128)\nLibrary Manager: Looking for another mirror...\nUnpacking\nUnpacking\nLibrary Manager: Warning! Package Mirror: 'ascii' codec can't decode byte 0xc0 in position 7: ordinal not in range(128)\nLibrary Manager: Looking for another mirror...\nUnpacking\nUnpacking\nLibrary Manager: Warning! Package Mirror: 'ascii' codec can't decode byte 0xc0 in position 7: ordinal not in range(128)\nLibrary Manager: Looking for another mirror...\n\n\nError: Could not install package 'me-no-dev/ESPAsyncTCP @ ^1.2.2' for 'windows_amd64' system"

**Comment by ivankravets** [comment]
Do you use the latest PlatformIO IDE 2.0 for VSCode?
