### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by alexandresvifpb** [platformio/platformio-home#1213]
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 21, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib\\command.py\", line 258, in lib_update\r\n    lm = LibraryPackageManager(storage_dir)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\library.py\", line 26, in __init__\r\n    super(LibraryPackageManager, self).__init__(\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\base.py\", line 54, in __init__\r\n    self.package_dir = self.ensure_dir_exists(package_dir)\r\n  File \"c:\\users\\alexa\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\base.py\", line 94, in ensure_dir_exists\r\n    os.makedirs(path)\r\n  File \"C:\\Python38\\lib\\os.py\", line 221, in makedirs\r\n    mkdir(name, mode)\r\nFileExistsError: [WinError 183] Não é possível criar um arquivo já existente: 'D:\\\\Users\\\\alexa\\\\OneDrive\\\\projetos\\\\cnc\\\\blackrouter\\\\firmaware\\\\Grbl_Esp32\\\\.pio\\\\libdeps\\\\ttgo-t-beam'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/7d3fc1ec1a2155955f81f74a9c21a60d01a8af2e
