### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by wesleymilan** [platformio/platformio-home#1217]
PIO Core Call Error: "Library Storage: /Users/wesleymilan/Documents/Servers/gardeniser/nodemcu/nodemcuv2/.pio/libdeps/nodemcuv2\nLibrary Manager: Installing maakbaas/ESP8266 IoT Framework @ ^1.3.0\nLibrary Manager: ESP8266 IoT Framework @ 1.3.0 has been installed!\nLibrary Manager: Installing dependencies...\nLibrary Manager: Installing ESP Async WebServer\nLibrary Manager: ESP Async WebServer @ 1.2.3 has been installed!\nLibrary Manager: Installing dependencies...\nLibrary Manager: Installing ESPAsyncTCP\nLibrary Manager: ESPAsyncTCP @ 1.2.2 has been installed!\nLibrary Manager: Installing AsyncTCP\nLibrary Manager: AsyncTCP @ 1.1.1 has been installed!\nLibrary Manager: Installing Hash\n\n\nError: Could not find the package with 'Hash' requirements for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/issues/3662
