### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Bai794** [platformio/platformio-home#1219]
PIO Core Call Error: "The current working directory C:\\Users\\bai\\Documents\\PlatformIO\\Projects\\cesi will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\bai\\Documents\\PlatformIO\\Projects\\cesi\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'ATmega2560'"

**Comment by ivankravets** [comment]
Please update all dev-platforms and restart VSCode.
