### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by magfmac** [platformio/platformio-home#1227]
PIO Core Call Error: "Library Storage: /home/arduino/Documents/PlatformIO/Projects/PirTelegram/.pio/libdeps/esp32doit-devkit-v1\nLibrary Manager: Installing ottowinter/ESPAsyncWebServer-esphome @ ^1.2.7\nLibrary Manager: ESPAsyncWebServer-esphome @ 1.2.7 has been installed!\nLibrary Manager: Installing dependencies...\nLibrary Manager: Installing ESPAsyncTCP-esphome\nLibrary Manager: ESPAsyncTCP-esphome @ 1.2.3 has been installed!\nLibrary Manager: Installing AsyncTCP-esphome\nLibrary Manager: AsyncTCP-esphome @ 1.1.1 has been installed!\nLibrary Manager: Installing Hash\n\n\nError: Could not find the package with 'Hash' requirements for your system 'linux_x86_64'"

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/issues/3662
