### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by kruzhkov** [platformio/platformio-home#1230]
PIO Core Call Error: "Platform /Users/sergeykruzhkov/.platformio/platforms/espressif8266@2.2.3\n--------\n\n\nError: Could not find the package with '/Users/sergeykruzhkov/.platformio/platforms/espressif8266@2.2.3' requirements for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Yes, just use `espressif8266@2.2.3`
