### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Patrekur** [platformio/platformio-home#1233]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1254, in invoke\n    cmd_name, cmd, args = self.resolve_command(ctx, args)\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1297, in resolve_command\n    cmd = self.get_command(ctx, cmd_name)\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 67, in get_command\n    return self._handle_obsolate_command(cmd_name)\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 77, in _handle_obsolate_command\n    from platformio.commands.project import project_init\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\project.py\", line 26, in <module>\n    from platformio.package.manager.platform import PlatformPackageManager\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\platform.py\", line 16, in <module>\n    from platformio.clients.http import HTTPClientError, InternetIsOffline\n  File \"c:\\users\\patre\\.platformio\\penv\\lib\\site-packages\\platformio\\clients\\http.py\", line 23, in <module>\n    from platformio import __check_internet_hosts__, __default_requests_timeout__, app, util\nImportError: cannot import name __check_internet_hosts__\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by valeros** [comment]
Hi @Patrekur ! Looks like you're using an outdated `platformio-core`. Please open a new terminal window in the IDE and run `platformio upgrade`.
