### ISSUE TITLE
time Libraries: Search

### ISSUE THREAD

**Issue by kedarchavan** [platformio/platformio-home#1234]
PIO Core Call Error: "b''\n\nb'Error: Traceback (most recent call last):\\r\\n  File \"c:\\\\users\\\\hp\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\__main__.py\", line 109, in main\\r\\n    cli()  # pylint: disable=no-value-for-parameter\\r\\n  File \"c:\\\\users\\\\hp\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 829, in __call__\\r\\n    return self.main(*args, **kwargs)\\r\\n  File \"c:\\\\users\\\\hp\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 782, in main\\r\\n    rv = self.invoke(ctx)\\r\\n  File \"c:\\\\users\\\\hp\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\commands\\\\__init__.py\", line 44, in invoke\\r\\n    return super(PlatformioCLI, self).invoke(ctx)\\r\\n  File \"c:\\\\users\\\\hp\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 1259, in invoke\\r\\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\\r\\n  File \"c:\\\\users\\\\hp\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 1259, in invoke\\r\\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\\r\\n  File \"c:\\\\users\\\\hp\\

**Comment by ivankravets** [comment]
Hi Abrishek,

Please restart VSCode and check your internet conenction
