### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by GJ2333** [platformio/platformio-home#1236]
PIO Core Call Error: "The current working directory E:\\Study\\stm32\\TEXT will be used for the project.\r\n\r\nThe next files/directories have been created in E:\\Study\\stm32\\TEXT\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: HTTPSConnectionPool(host='dl.registry.platformio.org', port=443): Max retries exceeded with url: /download/platformio/tool/toolchain-gccarmnoneeabi/1.90201.191206/toolchain-gccarmnoneeabi-windows_amd64-1.90201.191206.tar.gz?bypass=e7d7c0c04d791bc87c42d421b08215048de5e3e5 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))"

**Comment by ivankravets** [comment]
Do you use proxy?
