### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Steve-B** [platformio/platformio-home#124]
PIO Core Call Error: "The current working directory C:\\Apps\\arduino\\projects\\spi_cp\\spi_cp will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Apps\\arduino\\projects\\spi_cp\\spi_cp\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing uno (platform: atmelavr; board: uno; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\n  File \"C:\\Users\\Steve\\.platformio\\platforms\\atmelavr\\builder\\main.py\", line 30\r\n\r\n    print \"Please unplug/plug device ...\"\r\n\r\n                                        ^\r\n\r\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"Please unplug/plug device ...\")?\r\n\r\n========================== [FAILED] Took 1.23 seconds =========================="

**Comment by ivankravets** [comment]
Please open PIO Home > Platforms > Updates.

Update all dev/platforms.
