### ISSUE TITLE
Error: Unknown development platform

### ISSUE THREAD

**Issue by codemaster-22** [platformio/platformio-home#1242]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=/home/hp/.platformio/platforms/shakti metadata=PackageMetaData <type=platform name=shakti version=1.0.2 spec={'owner': 'platformio', 'id': 8033, 'name': 'shakti', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Could you compress this folder `/home/hp/.platformio/platforms` and share somewhere? Thanks!

**Comment by codemaster-22** [comment]
It got resolved, thanks for the quick response.

-shivaram
