### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by ubu78** [platformio/platformio-home#1243]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/commands/lib/command.py\", line 269, in lib_update\n    spec = PackageSpec(library)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/package/meta.py\", line 119, in __init__\n    self._parse(raw)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/package/meta.py\", line 221, in _parse\n    raw = parser(raw)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/package/meta.py\", line 238, in _parse_requirements\n    self.requirements = tokens[1].strip()\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/platformio/package/meta.py\", line 162, in requirements\n    else semantic_version.SimpleSpec(str(value))\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/semantic_version/base.py\", line 618, in __init__\n    self.clause = self._parse_to_clause(expression)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/semantic_version/base.py\", line 1014, in _parse_to_clause\n    return cls.Parser.parse(expression)\n  File \"/home/ubu/.platformio/penv/lib/python3.8/site-packages/semantic_version/base.py\", line 1034, in parse\n    raise ValueError(\"Invalid simple block %r\" % block)\nValueError: Invalid simple block '41a00db32a'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core 5.0.1. Please open PlatformIO CLI and type `pio upgrade`.
