### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by JesConsuegra** [platformio/platformio-home#1252]
PIO Core Call Error: "The current working directory C:\\Users\\jesito_2\\Documents\\PlatformIO\\Projects\\Arduino blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\jesito_2\\Documents\\PlatformIO\\Projects\\Arduino blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/tool-scons @ ~4.40001.0\r\nTool Manager: tool-scons @ 4.40001.0 has been installed!\r\nTool Manager: Removing tool-scons @ 2.20501.7\r\nTool Manager: tool-scons @ 2.20501.7 has been removed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\n  File \"C:\\Users\\jesito_2\\.platformio\\platforms\\atmelavr\\builder\\main.py\", line 30\r\n\r\n    print \"Please unplug/plug device ...\"\r\n\r\n                                        ^\r\n\r\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"Please unplug/plug device ...\")?\r\n\r\n========================== [FAILED] Took 3.66 seconds =========================="

**Comment by valeros** [comment]
Looks like you're using an outdated `atmelavr` platform. Please run `pio update` in the IDE terminal.
