### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by DimasSup** [platformio/platformio-home#1254]
PIO Core Call Error: "Library Storage: /Users/DimasSup/Documents/PlatformIO/Projects/WiFiTest/.pio/libdeps/nanoatmega328\nLibrary Manager: Installing ottowinter/ESPAsyncWebServer-esphome @ ^1.2.7\nLibrary Manager: ESPAsyncWebServer-esphome @ 1.2.7 has been installed!\nLibrary Manager: Installing dependencies...\nLibrary Manager: Installing ESPAsyncTCP-esphome\nLibrary Manager: ESPAsyncTCP-esphome @ 1.2.3 has been installed!\nLibrary Manager: Installing AsyncTCP-esphome\nLibrary Manager: AsyncTCP-esphome @ 1.1.1 has been installed!\nLibrary Manager: Installing Hash\n\n\nError: Could not find the package with 'Hash' requirements for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core 5.0.1. Please open PlatformIO CLI and type `pio upgrade`.
