### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by danieltang3434** [platformio/platformio-home#1263]
PIO Core Call Error: "The current working directory D:\\Software Projects\\espidf-get-started will be used for the project.\r\n\r\nThe next files/directories have been created in D:\\Software Projects\\espidf-get-started\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatform Manager: Installing espressif32\r\nPlatform Manager: espressif32 @ 2.0.0 has been installed!\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.50200.0\r\nTool Manager: toolchain-xtensa32 @ 2.50200.80 has been installed!\r\nTool Manager: Installing platformio/tool-esptoolpy @ ~1.20600.0\r\nTool Manager: tool-esptoolpy @ 1.20600.0 has been installed!\r\nThe platform 'espressif32' has been successfully installed!\r\nThe rest of the packages will be installed later depending on your build environment.\r\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\r\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\r\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\r\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\r\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\r\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\r\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\r\nTool Manager: tool-cmake @ 3.16.4 has been installed!\r\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\r\nTool Manager: tool-ninja @ 1.9.0 has been installed!\r\nTool Manager: Installing platformio/tool-mconf @ ~1.4060000.0\r\nTool Manager: tool-mconf @ 1.4060000.20190628 has been installed!\r\nTool Manager: Installing platformio/tool-idf @ ~1.0.1\r\nTool Manager: tool-idf @ 1.0.1 has been installed!\r\nTool Manager: Installing platformio/tool-scons @ ~4.40001.0\r\nTool Manager: tool-scons @ 4.40001.0 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\r\nPLATFORM: Espressif 32 (2.0.0) > Espressif ESP32 Dev Module\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40100.200827 (4.1.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200827 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\n'C:\\Users\\Daniel' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n*** Error 1\r\nInstalling windows-curses package\r\n'C:\\Users\\Daniel' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n*** Error 1\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 140.62 seconds ========================="

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations
