### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by manovijay1997** [platformio/platformio-home#1267]
PIO Core Call Error: "The current working directory K:\\RGB music\\RGB_Music will be used for the project.\r\n\r\nThe next files/directories have been created in K:\\RGB music\\RGB_Music\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatform Manager: Installing atmelavr\r\n\n\nError: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v3/packages?query=type%3A%22platform%22+name%3A%22atmelavr%22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000247E7EAA148>, 'Connection to api.registry.ns1.platformio.org timed out. (connect timeout=10)'))"

**Comment by ivankravets** [comment]
Please check your internet connection and restart VSCode.
