### ISSUE TITLE
Save config causes silent error

### ISSUE THREAD

**Issue by elyulka** [platformio/platformio-home#128]
Versions:
```
Home 3.1.0-beta.2
Core 4.1.1b3
```

Saving project config causes silent error:

![saving-renamed-section-used-in-extends](https://user-images.githubusercontent.com/7532384/69721988-b74a1c80-111e-11ea-8043-84c96487df47.png)

@ivankravets Some issue on the Python side? I don't see any visible problems neither in the file or in the API call arguments:
https://raw.githubusercontent.com/TD-er/MCVE_ESPxx/master/platformio.ini

**Comment by ivankravets** [comment]
@elyulka  Can you show errors to the user? So, they can report us directly.

**Comment by ivankravets** [comment]
The saving issue has been fixed in https://github.com/platformio/platformio-core/commit/47469e87594d8067ce9728cc0e40cf6902e5ad0b

**Comment by elyulka** [comment]
Fixed in f8472948f06e1eb4893183da1f434287932cf8b3
