### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by Mohammadsafarisouri** [platformio/platformio-home#1286]
PIO Core Call Error: "Platform Manager: Installing AliyunIoTSDK\r\n\n\nError: Could not find the package with 'AliyunIoTSDK' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
"Platform Manager: Installing AliyunIoTSDK\r\n\n\nError: Could not find the package with 'AliyunIoTSDK' requirements for your system 'windows_amd64'"
