### ISSUE TITLE
Erase flash option missed on "Platformio tasks" after update

### ISSUE THREAD

**Issue by pabloVecchio** [platformio/platformio-home#1297]
I couldn't find 'Erase flash' option after update platformio. I've got Core 5.0.1 and Home 3.3.0 versions. It's has been removed? It was a very helpful tool

**Comment by ivankravets** [comment]
https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks

**Comment by peacepenguin** [comment]
For anyone else having this issue with missing "erase flash" command in the gui. Just select your specific board from the "Project Environment Switcher" at the bottom of vscode. Once you choose your specific board, the "Erase Flash" option comes back under the env: tree in the gui for your now chosen environment.

https://docs.platformio.org/en/latest/_images/platformio-ide-vscode-task-explorer.png

**Comment by Smitty357** [comment]
Still no luck for me. Any other suggestions?

**Comment by peacepenguin** [comment]
What platform are you using?

Im using an esp32dev platform and this procedure has worked well for me on many of my systems that were missing the erase flash command.

But I'm not sure what is normal for other platforms.
