### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by JBInnov** [platformio/platformio-home#1298]
PIO Core Call Error: "The current working directory D:\\Data\\PlatformIO\\Projects\\test a effacer will be used for the project.\r\n\r\nThe next files/directories have been created in D:\\Data\\PlatformIO\\Projects\\test a effacer\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing az-delivery-devkit-v4 (platform: espressif32; board: az-delivery-devkit-v4; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\r\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/az-delivery-devkit-v4.html\r\nPLATFORM: Espressif 32 (2.0.0) > AZ-Delivery ESP-32 Dev Kit C V4\r\nHARDWARE: ESP32 240MHz, 520KB RAM, 16MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40100.200827 (4.1.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200827 (8.2.0)\r\nInstalling windows-curses package\r\nProcessing c:\\users\\jerome\\.platformio\\packages\\framework-espidf\\tools\\kconfig_new\\esp-windows-curses\r\nCollecting windows-curses\r\n  Downloading windows_curses-2.1.0-cp37-cp37m-win_amd64.whl (69 kB)\r\nBuilding wheels for collected packages: esp-windows-curses\r\n  Building wheel for esp-windows-curses (setup.py): started\r\n  Building wheel for esp-windows-curses (setup.py): finished with status 'done'\r\n  Created wheel for esp-windows-curses: filename=esp_windows_curses-0.1-py3-none-any.whl size=1175 sha256=8bc3f102f3be569087899636a75633ec44cf48682dc28931187043d2e8534ec5\r\n  Stored in directory: c:\\users\\jerome\\appdata\\local\\pip\\cache\\wheels\\bc\\40\\b1\\0d41a8a7d43040dd682a9b009da28a2d207f5a79517e45f0cf\r\nSuccessfully built esp-windows-curses\r\nInstalling collected packages: windows-curses, esp-windows-curses\r\nSuccessfully installed esp-windows-curses-0.1 windows-curses-2.1.0\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 79.36 seconds ========================="

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations
