### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by fredolaredo** [platformio/platformio-home#1352]
PIO Core Call Error: "Platform /Users/fred/.platformio/platforms/asrmicro650x\n--------\nUpdating platformio/asrmicro650x              1.1.0                              [Outdated 1.1.1]\nPlatform Manager: Installing platformio/asrmicro650x @ 1.1.1\n\n\nError: Traceback (most recent call last):\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/commands/platform.py\", line 420, in platform_update\n    pm.update(\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/platform.py\", line 107, in update\n    new_pkg = super(PlatformPackageManager, self).update(\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_update.py\", line 114, in update\n    return self._update(pkg, outdated, silent=silent)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_update.py\", line 149, in _update\n    new_pkg = self.install(\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/platform.py\", line 48, in install\n    pkg = super(PlatformPackageManager, self).install(\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_install.py\", line 48, in install\n    pkg = self._install(\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_install.py\", line 99, in _install\n    pkg = self.install_from_registry(spec, search_filters, silent=silent)\n  File \"/Users/fred/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_registry.py\", line 86, in install_from_registry\n    version = self.pick_best_registry_version(package[\"versions\"], spec)\nKeyError: 'versions'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please open PlatformIO CLI and type `pio upgrade`. Restart VSCode. Is fixed in the latest PlatformIO Core 5.0.2
