### ISSUE TITLE
Show one-time warning before saving a project configuration

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-home#137]
------
Warning! Project Configuration does not preserve comments and custom formatting in the `platformio.ini` file. The file contents will be overridden with a current configuration which you see in UI. Would you like to save the configuration?

[Cancel] [Save] 
---

**Comment by TD-er** [comment]
> The file contents will be overridden with a current configuration which you see in UI. Would you like to save the configuration?

This sentence can be improved.

> **Warning!** 
> The entire file contents or `platformio.ini` will be rewritten with the current configuration defined in this UI.
> Continue to save the configuration?

**Comment by pfeerick** [comment]
Another approach to this might also be 'show the warning if the file has not been automatically generated' ... i.e. rather than be a one-time warning, show warning if the file has not been UI generated, and you're trying to make UI changes. If that is feasible. Consider making the warning hidable, for those that think they know what they're doing! ;)

**Comment by ivankravets** [comment]
>  'show the warning if the file has not been automatically generated' 

If there is no `platformio.ini` file, you will not be able to edit it :) So, we show in Projects section only PlatformIO-based projects that have `platformio.ini`.

I'm not sure that it's easy to track how file was created before. I think this warning is good for every developer even he edits the first time. He will know that there is a difference between manual editing and UI.

**Comment by DevinNorgarb** [comment]
@ivankravets @TD-er 
> > The file contents will be overridden with a current configuration which you see in UI. Would you like to save the configuration?
> 
> This sentence can be improved.
> 
> > **Warning!**
> > The entire file contents or `platformio.ini` will be rewritten with the current configuration defined in this UI.
> > Continue to save the configuration?

Do you not mean? 
> The entire file contents ~~or~~ **of** platformio.ini will be rewritten with the current configuration defined in this UI.

I came looking for this because I noticed it now in the IDE and thought that it should be corrected. 
Let me know if it should be `of` instead of `or`. and I quickly create a PR.

**Comment by ivankravets** [comment]
Thanks! Solved in https://github.com/platformio/platformio-home/commit/531e4d226acf4d73d19444d365c90f4a5496f343

**Comment by DevinNorgarb** [comment]
@ivankravets I was hoping to get my first commit into platform.io this way ;) 
But either way, glad I could help. 👍🏻
