### ISSUE TITLE
Project Configuration: PlatformIO configuation on the right

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#138]
Can we have it so the PlatformIO Configuration tab is always pinned to the right side?

![image](https://user-images.githubusercontent.com/5500713/69834699-c3052280-1287-11ea-8b33-32cd81102c23.png)

**Comment by ivankravets** [comment]
Can we insert a new `PlatformIO Configuration` at the beginning of all tabs? Also, how about to rename it to `PIO Configuration`? It seems we can save a space by width.

**Comment by elyulka** [comment]
> Can we insert a new PlatformIO Configuration at the beginning of all tabs?
It was a part of "smart adding new section" feature already done.
