### ISSUE TITLE
Project Configuration: ToC Button location

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#139]
Since the ToC button alters the ToC state for more than the current tab/persists across tabs, can/should it be moved to the top of the screen, outside of the tab area?

**Comment by ivankravets** [comment]
Yes, it makes sense. Otherwise, need to click each time in each tab. @elyulka can we move this button to TOP without any text, just only icon with TOOLTIP. So, if use enabled ToC, then all tabs should automatically show Contents.
