### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by fsr-byte** [platformio/platformio-home#1408]
PIO Core Call Error: "The current working directory C:\\Users\\DELL\\Documents\\PlatformIO\\Projects\\ hello_world will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\DELL\\Documents\\PlatformIO\\Projects\\ hello_world\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatform Manager: Installing espressif32\r\nPlatform Manager: espressif32 @ 2.0.0 has been installed!\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.50200.0\r\nTool Manager: toolchain-xtensa32 @ 2.50200.80 has been installed!\r\nTool Manager: Installing platformio/tool-esptoolpy @ ~1.20600.0\r\nTool Manager: tool-esptoolpy @ 1.20600.0 has been installed!\r\nThe platform 'espressif32' has been successfully installed!\r\nThe rest of the packages will be installed later depending on your build environment.\r\n\n\nError: Processing fm-devkit (platform: espressif32; board: fm-devkit; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\r\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\r\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\r\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\r\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\r\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\r\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\r\nTool Manager: tool-cmake @ 3.16.4 has been installed!\r\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\r\nTool Manager: tool-ninja @ 1.9.0 has been installed!\r\nTool Manager: Installing platformio/tool-mconf @ ~1.4060000.0\r\nTool Manager: tool-mconf @ 1.4060000.20190628 has been installed!\r\nTool Manager: Installing platformio/tool-idf @ ~1.0.1\r\nTool Manager: tool-idf @ 1.0.1 has been installed!\r\nTool Manager: Installing platformio/tool-scons @ ~4.40001.0\r\nTool Manager: tool-scons @ 4.40001.0 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/fm-devkit.html\r\nPLATFORM: Espressif 32 (2.0.0) > ESP32 FM DevKit\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40100.200827 (4.1.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200827 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\nLooking in indexes: http://mirrors.aliyun.com/pypi/simple/\r\nRequirement already satisfied: cryptography>=2.1.4 in c:\\users\\dell\\.platformio\\packages\\contrib-pysite (2.8)\r\nCollecting future>=0.15.2\r\n  Downloading http://mirrors.aliyun.com/pypi/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829 kB)\r\nCollecting pyparsing<2.4.0,>=2.0.3\r\n  Downloading http://mirrors.aliyun.com/pypi/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\r\nRequirement already satisfied: cffi!=1.11.3,>=1.8 in c:\\users\\dell\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.13.0)\r\nRequirement already satisfied: six>=1.4.1 in c:\\users\\dell\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.12.0)\r\nRequirement already satisfied: pycparser in c:\\users\\dell\\.platformio\\packages\\contrib-pysite (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4) (2.19)\r\nBuilding wheels for collected packages: future\r\n  Building wheel for future (setup.py): started\r\n  Building wheel for future (setup.py): finished with status 'done'\r\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=bb96e865edd9af40a287de6126a4f1035e3ef8090e3268c522f41cb7301e541f\r\n  Stored in directory: c:\\users\\dell\\appdata\\local\\pip\\cache\\wheels\\32\\cb\\14\\6b0d3adea56a482126848625bb74692a67fb898990033d6da4\r\nSuccessfully built future\r\nInstalling collected packages: future, pyparsing\r\nSuccessfully installed future-0.18.2 pyparsing-2.3.1\r\nInstalling windows-curses package\r\nLooking in indexes: http://mirrors.aliyun.com/pypi/simple/\r\nProcessing c:\\users\\dell\\.platformio\\packages\\framework-espidf\\tools\\kconfig_new\\esp-windows-curses\r\nCollecting windows-curses\r\n  Downloading http://mirrors.aliyun.com/pypi/packages/cf/6b/19851f32a41e6ff5985bdabf531aa19786eb6fa8ad825e3a82fc1625383e/windows_curses-2.1.0-cp37-cp37m-win_amd64.whl (69 kB)\r\nBuilding wheels for collected packages: esp-windows-curses\r\n  Building wheel for esp-windows-curses (setup.py): started\r\n  Building wheel for esp-windows-curses (setup.py): finished with status 'done'\r\n  Created wheel for esp-windows-curses: filename=esp_windows_curses-0.1-py3-none-any.whl size=1175 sha256=08b84c0e145b21fbbf30fd1dddfe2f70a53f2c213745c4d31017f4b82d9a3455\r\n  Stored in directory: c:\\users\\dell\\appdata\\local\\pip\\cache\\wheels\\1a\\10\\02\\c1fca0e3ed17edbe7e4149593bd575e9b839ad37afb45370df\r\nSuccessfully built esp-windows-curses\r\nInstalling collected packages: windows-curses, esp-windows-curses\r\nSuccessfully installed esp-windows-curses-0.1 windows-curses-2.1.0\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 529.28 seconds ========================="

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations
