### ISSUE TITLE
Could not update platform

### ISSUE THREAD

**Issue by Mateiuc** [platformio/platformio-home#142]
PIO Core Call Error: "Platform C:\\Users\\Cip\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\r\n--------\nUpdating espressif8266                   @ 4db7ada        [043f5fd]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please check that there are no changes in `C:\Users\Cip\.platformio\platforms\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf`. Otherwise, remove `C:\Users\Cip\.platformio\platforms\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf` folder and start build again.
