### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by PHPJJ** [platformio/platformio-home#143]
PIO Core Call Error: "Platform C:\\Users\\peter\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\r\n--------\r\nUpdating espressif8266                   @ 5099faf        [043f5fd]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/94
