### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by Crspy** [platformio/platformio-home#1437]
PIO Core Call Error: "Platform Manager: Installing git+https://github.com/WallaceWilliam/framework-esp8266-rtos-sdk-idf-platformio.git\r\nPlatform Manager: custom8266 @ 1.1.0+sha.cc2f7c6 has been installed!\r\nTool Manager: Installing toolchain-xtensa-lx106-elf @ 5.2.0+100\r\n\n\nError: Could not find the package with 'toolchain-xtensa-lx106-elf @ 5.2.0+100' requirements for your system 'windows_amd64'"

**Comment by EnJiang** [comment]
Encountered the same.
