### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by robgerpin** [platformio/platformio-home#1451]
PIO Core Call Error: "The current working directory C:\\Users\\robge\\Documents\\PlatformIO\\Projects\\teste 001 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\robge\\Documents\\PlatformIO\\Projects\\teste 001\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing ttgo-lora32-v2 (platform: espressif32; board: ttgo-lora32-v2; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\r\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\r\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\r\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\r\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\r\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\r\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\r\nTool Manager: tool-cmake @ 3.16.4 has been installed!\r\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\r\nTool Manager: tool-ninja @ 1.9.0 has been installed!\r\nTool Manager: Installing platformio/tool-mconf @ ~1.4060000.0\r\nTool Manager: tool-mconf @ 1.4060000.20190628 has been installed!\r\nTool Manager: Installing platformio/tool-idf @ ~1.0.1\r\nTool Manager: tool-idf @ 1.0.1 has been installed!\r\nTool Manager: Installing platformio/tool-scons @ ~4.40001.0\r\nTool Manager: tool-scons @ 4.40001.0 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/ttgo-lora32-v2.html\r\nPLATFORM: Espressif 32 (2.0.0) > TTGO LoRa32-OLED V2\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40100.200827 (4.1.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200827 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\nRequirement already satisfied: cryptography>=2.1.4 in c:\\users\\robge\\.platformio\\packages\\contrib-pysite (2.8)\r\nCollecting future>=0.15.2\r\n  Downloading future-0.18.2.tar.gz (829 kB)\r\nCollecting pyparsing<2.4.0,>=2.0.3\r\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\r\nRequirement already satisfied: cffi!=1.11.3,>=1.8 in c:\\users\\robge\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.13.0)\r\nRequirement already satisfied: six>=1.4.1 in c:\\users\\robge\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.12.0)\r\nRequirement already satisfied: pycparser in c:\\users\\robge\\.platformio\\packages\\contrib-pysite (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4) (2.19)\r\nBuilding wheels for collected packages: future\r\n  Building wheel for future (setup.py): started\r\n  Building wheel for future (setup.py): finished with status 'done'\r\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=4f36cc02cbf0325036d7506c614d9ed7b2dddd99ba6617fd7104e1e0ef79f055\r\n  Stored in directory: c:\\users\\robge\\appdata\\local\\pip\\cache\\wheels\\56\\b0\\fe\\4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0\r\nSuccessfully built future\r\nInstalling collected packages: future, pyparsing\r\nSuccessfully installed future-0.18.2 pyparsing-2.3.1\r\nInstalling windows-curses package\r\nProcessing c:\\users\\robge\\.platformio\\packages\\framework-espidf\\tools\\kconfig_new\\esp-windows-curses\r\nCollecting windows-curses\r\n  Downloading windows_curses-2.1.0-cp37-cp37m-win_amd64.whl (69 kB)\r\nBuilding wheels for collected packages: esp-windows-curses\r\n  Building wheel for esp-windows-curses (setup.py): started\r\n  Building wheel for esp-windows-curses (setup.py): finished with status 'done'\r\n  Created wheel for esp-windows-curses: filename=esp_windows_curses-0.1-py3-none-any.whl size=1175 sha256=a88fefc9f4d83649430deffab938ec6e505c09cd150d54c8fd0cd7eec59e7ff6\r\n  Stored in directory: c:\\users\\robge\\appdata\\local\\pip\\cache\\wheels\\a3\\5d\\03\\5ba3744f704f4c793fda64fef612b640f2b72d2cd9abe557dd\r\nSuccessfully built esp-windows-curses\r\nInstalling collected packages: windows-curses, esp-windows-curses\r\nSuccessfully installed esp-windows-curses-0.1 windows-curses-2.1.0\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 134.45 seconds ========================="

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations
