### ISSUE TITLE
Error: Unknown board ID

### ISSUE THREAD

**Issue by assa62** [platformio/platformio-home#155]
PIO Core Call Error: "The current working directory C:\\Users\\Alex\\Desktop\\scetch\\0412\\VOLVO HU850 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Alex\\Desktop\\scetch\\0412\\VOLVO HU850\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Unknown board ID 'diecimilaatmega328'"

**Comment by ivankravets** [comment]
Please find valid board identified (ID) for your hardware in docs https://docs.platformio.org/en/latest/boards/index.html
