### ISSUE TITLE
Unable to update "platformio/contrib-pysite"

### ISSUE THREAD

**Issue by RobThree** [platformio/platformio-home#1566]
When updating PlatformIO I get:

    platformio update
    Updating platformio/contrib-piohome           3.3.0 @ ~3.3.0                     [Up-to-date]
    Updating platformio/contrib-pysite            2.38.191020 @ ~2.38.0              [Outdated 2.38.201019]
    Tool Manager: Installing platformio/contrib-pysite @ 2.38.201019
    Unpacking  [####################################]  100%
    Tool Manager: contrib-pysite @ 2.38.201019 has been installed!
    Tool Manager: Removing contrib-pysite @ 2.38.191020
    Tool Manager: contrib-pysite @ 2.38.191020 has been removed!
    Updating platformio/tool-unity                1.20500.200612 @ ~1.20500.0        [Up-to-date]

And when retrying:

    platformio update
    Updating platformio/contrib-piohome           3.3.0 @ ~3.3.0                     [Up-to-date]
    Updating platformio/contrib-pysite            2.38.201019 @ ~2.38.0              [Incompatible 2.39.201019]
    Updating platformio/tool-unity                1.20500.200612 @ ~1.20500.0        [Up-to-date]

<img width="761" alt="Screenshot 2020-10-25 at 02 55 06" src="https://user-images.githubusercontent.com/607888/97097186-ec802700-166d-11eb-90c2-17b18ed0e8fc.png">

Unfortunately I have no clue how to fix this.

**Comment by cyba3r** [comment]
Same issue here under Windows

**Comment by RobThree** [comment]
![image](https://user-images.githubusercontent.com/607888/99671581-84f1a780-2a72-11eb-92be-160bebaa5030.png)

Yep, getting the same under windows.

**Comment by yuanyanhui** [comment]
Same issue in Windows. Also cannot debug. In the debug console, see a lot of errors from python programs.

**Comment by yuanyanhui** [comment]
According to this post, the incompatible issue is not a problem.
https://community.platformio.org/t/platformio-libraries-updates-not-working-after-updating-to-5-x/16638/13

**Comment by ivankravets** [comment]
The latest PlatformIO Core 5.0.5-dev does not require pysite package. We migrated PIO Home to native Python 3.
