### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Patrick-81** [platformio/platformio-home#1568]
PIO Core Call Error: "The current working directory /home/pat/Documents/PlatformIO/Projects/Test wemos d1 will be used for the project.\n\nThe next files/directories have been created in /home/pat/Documents/PlatformIO/Projects/Test wemos d1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatform Manager: Installing espressif32\nDownloading...\nUnpacking...\nPlatform Manager: espressif32 @ 2.0.0 has been installed!\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.50200.0\nDownloading...\nUnpacking...\nTool Manager: toolchain-xtensa32 @ 2.50200.80 has been installed!\nTool Manager: Installing platformio/tool-esptoolpy @ ~1.20600.0\nDownloading...\nUnpacking...\nTool Manager: tool-esptoolpy @ 1.20600.0 has been installed!\nThe platform 'espressif32' has been successfully installed!\nThe rest of the packages will be installed later depending on your build environment.\n\n\nError: Processing wemos_d1_mini32 (platform: espressif32; board: wemos_d1_mini32; framework: espidf)\n--------------------------------------------------------------------------------\nTool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80200.0\nDownloading...\nUnpacking...\nTool Manager: toolchain-xtensa32 @ 2.80200.200827 has been installed!\nTool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0\nDownloading...\nUnpacking...\nTool Manager: toolchain-esp32ulp @ 1.22851.191205 has been installed!\nTool Manager: Installing platformio/framework-espidf @ ~3.40100.0\nDownloading...\nUnpacking...\nTool Manager: framework-espidf @ 3.40100.200827 has been installed!\nTool Manager: Installing platformio/tool-cmake @ ~3.16.0\nDownloading...\nUnpacking...\nTool Manager: tool-cmake @ 3.16.4 has been installed!\nTool Manager: Installing platformio/tool-ninja @ ^1.7.0\nDownloading...\nUnpacking...\nTool Manager: tool-ninja @ 1.7.1 has been installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/wemos_d1_mini32.html\nPLATFORM: Espressif 32 (2.0.0) > WeMos D1 MINI ESP32\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40100.200827 (4.1.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.7.1 \n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \n - toolchain-xtensa32 2.80200.200827 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nCollecting cryptography>=2.1.4\n  Downloading cryptography-3.1.1-cp35-abi3-manylinux2010_x86_64.whl (2.6 MB)\nCollecting future>=0.15.2\n  Downloading future-0.18.2.tar.gz (829 kB)\nCollecting pyparsing<2.4.0,>=2.0.3\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\nCollecting six>=1.4.1\n  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)\nCollecting cffi!=1.11.3,>=1.8\n  Downloading cffi-1.14.3-cp38-cp38-manylinux1_x86_64.whl (410 kB)\nCollecting pycparser\n  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)\nBuilding wheels for collected packages: future\n  Building wheel for future (setup.py): started\n  Building wheel for future (setup.py): finished with status 'done'\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=8b998e003085775c69f00ce58d7a4bf94be1e6c03e8b690d2d024ca3d6f0fcdc\n  Stored in directory: /home/pat/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4\nSuccessfully built future\nInstalling collected packages: six, pycparser, cffi, cryptography, future, pyparsing\nSuccessfully installed cffi-1.14.3 cryptography-3.1.1 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.15.0\nError: Detected a whitespace character in project paths.\n========================= [FAILED] Took 335.53 seconds ========================="

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations
