### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by freezeghost** [platformio/platformio-home#1591]
PIO Core Call Error: "Library Storage: D:\\!Prog\\Arduino\\My-TTGO-Watch-master\\.pio\\libdeps\\ttgo-t-watch\r\nLibrary Manager: Installing xinyuan-lilygo/TTGO TWatch Library @ ^1.3.0\r\nUnpacking...\r\nLibrary Manager: Warning! Package Mirror: CRC check failed 0xed05a807 != 0x23a65ce7\r\nLibrary Manager: Looking for another mirror...\r\nUnpacking...\r\nLibrary Manager: Warning! Package Mirror: CRC check failed 0xed05a807 != 0x23a65ce7\r\nLibrary Manager: Looking for another mirror...\r\nUnpacking...\r\nLibrary Manager: Warning! Package Mirror: CRC check failed 0xed05a807 != 0x23a65ce7\r\nLibrary Manager: Looking for another mirror...\r\n\n\nError: Could not install package 'xinyuan-lilygo/TTGO TWatch Library @ ^1.3.0' for 'windows_amd64' system"

**Comment by jurov** [comment]
Confirm. But it just fixed itself somehow.

**Comment by ivankravets** [comment]
Sorry, fixed in the registry. Please re-run `pio update.`

**Comment by freezeghost** [comment]
great it is work now. Thank yoy !
