### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by sylvioalves** [platformio/platformio-home#16]
PIO Core Call Error: "Library Storage: /home/sylvio/.platformio/lib\nLibraryManager: Installing id=431 @ ^0.3.9.2\n\n\nError: Could not find a version that satisfies the requirement '^0.3.9.2' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-home/commit/396370e2fa5779da8c404b72dfb0ff4eeb8446ff

Please install manually via `id=431`
