### ISSUE TITLE
DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Tianxiaomo** [platformio/platformio-home#1623]
PIO Core Call Error: "DLL load failed: 找不到指定的程序。"

**Comment by ivankravets** [comment]
Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type 
```
pio system info
```

Please share the output here.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/1772
