### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by BartvanS** [platformio/platformio-home#1628]
PIO Core Call Error: "The current working directory C:\\Users\\bartv\\Documents\\PlatformIO\\Projects\\test nucleo will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\bartv\\Documents\\PlatformIO\\Projects\\test nucleo\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatform Manager: Installing ststm32\r\nUnpacking...\r\nPlatform Manager: Warning! Package Mirror: [Errno 28] No space left on device\r\nPlatform Manager: Looking for another mirror...\r\nUnpacking...\r\nPlatform Manager: Warning! Package Mirror: [Errno 28] No space left on device\r\nPlatform Manager: Looking for another mirror...\r\nUnpacking...\r\nPlatform Manager: Warning! Package Mirror: [Errno 28] No space left on device\r\nPlatform Manager: Looking for another mirror...\r\n\n\nError: Could not install package 'ststm32' for 'windows_amd64' system"

**Comment by ivankravets** [comment]
No space left on device
