### ISSUE TITLE
Can not open PIO Home 

### ISSUE THREAD

**Issue by AlopexXx** [platformio/platformio-home#168]
When I try to open Home screen by clicking the icon in the side bar the home screen appears for a fraction of a second and then disappears.

When trying to open it from terminal "pio home" I get the following Error:

> Error: {'code': 4999, 'message': "HTTPSConnectionPool(host='dl.platformio.org', port=443): Max retries exceeded with url: /tweets/PlatformIO_Org/data.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))"}

**Comment by ivankravets** [comment]
Please restart VSCode. It should work now. Sorry for the issue.
