### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by luke4177** [platformio/platformio-home#1706]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Luke Puttock\\.platformio\\platforms\\ststm32@8.0.0 metadata=PackageMetaData <type=platform name=ststm32 version=8.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
