### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by Xgl0baltk** [platformio/platformio-home#1712]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\x_tar\\.platformio\\platforms\\atmelavr metadata=PackageMetaData <type=platform name=atmelavr version=3.0.0 spec={'owner': 'platformio', 'id': 8006, 'name': 'atmelavr', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
