### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by dmarirs** [platformio/platformio-home#1747]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\dmari\\.platformio\\platforms\\espressif32 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
