### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by targetarchitecture** [platformio/platformio-home#1751]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\johnf\\.platformio\\platforms\\atmelsam@5.0.0 metadata=PackageMetaData <type=platform name=atmelsam version=5.0.0 spec={'owner': 'platformio', 'id': 8007, 'name': 'atmelsam', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
