### ISSUE TITLE
Libraries: Stats

### ISSUE THREAD

**Issue by ens1985** [platformio/platformio-home#1760]
PIO Core Call Error: "Error: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v2/lib/stats (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1348
