### ISSUE TITLE
Could not initialize project or import Arduino project

### ISSUE THREAD

**Issue by okelk** [platformio/platformio-home#1764]
I get following error:

PIO Core Call Error: "spawnProcess not available since pywin32 is not installed."

Deleting ~/.platformio/packages/contrib-pysite as indicated [here](https://github.com/platformio/platformio-home/issues/48) did not help.

**Comment by ivankravets** [comment]
Could it be related to https://github.com/platformio/platformio-home/issues/1772 ?
