### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Hendrikus-Simplex** [platformio/platformio-home#1769]
PIO Core Call Error: "The current working directory C:\\Users\\Hendrik Horn\\Documents\\PlatformIO\\Projects\\1234 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Hendrik Horn\\Documents\\PlatformIO\\Projects\\1234\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing espmxdevkit (platform: espressif8266; board: espmxdevkit; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'espmxdevkit'\r\n========================== [FAILED] Took 0.68 seconds =========================="

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/1768
