### ISSUE TITLE
PIO Core Call Error: "DLL load failed: The specified procedure could not be found."

### ISSUE THREAD

**Issue by thijsdelft** [platformio/platformio-home#1772]
Could not load platform updates
PIO Core Call Error: "DLL load failed: The specified procedure could not be found."

`pio system info
>>
--------------------------  --------------------------------------------------------------
PlatformIO Core             5.0.3
Python                      3.7.7-final.0
System Type                 windows_amd64
Platform                    Windows-10
File System Encoding        utf-8
Locale Encoding             cp1252
PlatformIO Core Directory   C:\Users\user name\.platformio
PlatformIO Core Executable  C:\Users\user name\.platformio\penv\Scripts\platformio.exe
Python Executable           c:\users\user name\.platformio\penv\scripts\python.exe
Global Libraries            3
Development Platforms       4
Tools & Toolchains          13
--------------------------  --------------------------------------------------------------`

**Comment by thijsdelft** [comment]
The same happens when:
- adding a library to a project
- initializing a new project

Both in Atom and Visual Code Studio

From the command line interface platform updates *can* be installed.

Any hints on how to resolve this issue?

**Comment by ivankravets** [comment]
Do you have multiple Pythons in a system?

**Comment by thijsdelft** [comment]
Yes I do. (But I have this configuration already for quite some time)

**Comment by thijsdelft** [comment]
After removing Anaconda the issue with the DLL procedure was resolved. 
I can now create projects and load platform updates again!

**Comment by ivankravets** [comment]
See https://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found

Yes, it is caused by anaconda. I don't people who use anaconda. They provide unofficial binaries of Python with unofficial libraries. What is the benefit? The whole PyPi registry is not compatible with their binaries.

Please use official Python and you will save your time and nerves 😊

**Comment by maddentist** [comment]
No "broken" or unofficial Python dsitribution is installed on my system, and still I get the error. Please advise

**Comment by ivankravets** [comment]
@maddentist Do you have any Python installed in your system?

**Comment by TimSet0815** [comment]
I just uninstalled all versions of python and anaconda (which I did not had installed) and only freshly installed python 3.9.. I still get the DLL-error when checking for updates of my platforms. Any ideas?

**Comment by ivankravets** [comment]
Resolved with porting PIO Home backend server to native Python 3 Async I/O. PlatformIO Core 5.0.5 will be released soon.
