### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by s0menickname** [platformio/platformio-home#1777]
Arch Linux, Code OSS 1.51.1, PlatformIO 2.2.1.
Steps to reproduce: try to create a project.
Error:
`PIO Core Call Error: "decode() argument 'encoding' must be str, not None"`

**Comment by nametable** [comment]
I also have the same issue, Arch Linux, same PlatformIO version

**Comment by ivankravets** [comment]
Should be fixed in the latest PIO Core.
