### ISSUE TITLE
Libraries: Stats

### ISSUE THREAD

**Issue by BenjiFTL** [platformio/platformio-home#1781]
PIO Core Call Error: "Error: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v2/lib/stats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x106e83850>, 'Connection to api.registry.ns1.platformio.org timed out. (connect timeout=10)'))"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1348
