### ISSUE TITLE
Libraries: Builtin

### ISSUE THREAD

**Issue by Real-Maker** [platformio/platformio-home#1786]
PIO Core Call Error: "b''\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib\\command.py\", line 419, in lib_builtin\r\n    items = get_builtin_libs(storage)\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib\\helpers.py\", line 34, in get_builtin_libs\r\n    for storage in p.get_lib_storages():\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\platform\\base.py\", line 214, in get_lib_storages\r\n    pkg = self.get_package(opts[\"package\"])\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\platform\\_packages.py\", line 31, in get_package\r\n    return self.pm.get_package(self.get_package_spec(name))\r\n  File \"c:\\users\\offley's envy\\.platformio\\penv\\lib\\site-packages\\platformio\\platform\\_packages.py\", line 21, in get_package_spec\r\n    version = self.packages[name].get(\"version\", \"\")\r\nKeyError: 'framework-stm32cube'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Fixed in the latest ST STM32 dev-platform. Please open `PIO Home > PlatformIO > Updates` and update to the latest version.
