### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by rockyanton** [platformio/platformio-home#1798]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Losga\\.platformio\\platforms\\ststm32@9.0.0 metadata=PackageMetaData <type=platform name=ststm32 version=9.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by rockyanton** [comment]
Solved after program restart

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?

**Comment by rockyanton** [comment]
Sorry I don't remember, almost 2 months passed.
