### ISSUE TITLE
pio home stuck "Loading..." with 4.1.0rc1 on macOS 10.14.6

### ISSUE THREAD

**Issue by blackketter** [platformio/platformio-home#18]
I updated via pio upgrade --dev then pio update, rebuilt my project then I start pio home.

I’m stuck with a web browser window that just says “Loading…” on a black background. Any logging I can turn on to find out what’s going on?

macOS 10.14.6, PlatformIO 4.1.0rc1, tested Safari and Firefox.  

Worked fine until I updated  with --dev.

**Comment by blackketter** [comment]
This is an issue with Firefox and Safari.  Seems to load ok with Chrome.

**Comment by ivankravets** [comment]
Thanks! This is our bug.

@elyulka please fix this RegExp => https://github.com/platformio/platformio-home/blob/develop/app/modules/inspect/helpers.js#L174
