### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by TimVerbecque** [platformio/platformio-home#1806]
PIO Core Call Error: "Library Storage: D:\\1ITF10\\IT essentials\\Project\\Projects\\ESP32 Serial monitor\\.pio\\libdeps\\featheresp32\r\nLibrary Manager: Installing Adafruit BMP280\r\n\n\nError: Could not find the package with 'Adafruit BMP280' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2144
