### ISSUE TITLE
Libraries: Stats

### ISSUE THREAD

**Issue by rodolfomsantos** [platformio/platformio-home#1819]
PIO Core Call Error: "Error: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v2/lib/stats (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104adf880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1348
