### ISSUE TITLE
Libraries: Installed

### ISSUE THREAD

**Issue by zutawin** [platformio/platformio-home#1822]
PIO Core Call Error: "b''\n\nError: The directory `C:\\Users\\zutawin\\.platformio` or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually `C:\\Users\\zutawin\\.platformio` directory and PlatformIO will create new from the current user."

**Comment by ivankravets** [comment]
The directory C:\\Users\\zutawin\\.platformio or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually C:\\Users\\zutawin\\.platformio directory and PlatformIO will create new from the current user
