### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by gufobi** [platformio/platformio-home#1835]
PIO Core Call Error: "Platform C:\\Users\\kfirg\\.platformio\\platforms\\nordicnrf52\r\n--------\r\nUpdating git+https://github.com/meshtastic/platform-nordicnrf52.git#1a2639a6b0f79b5df66bea3e3089f0d5285fdc63 4.4.0+sha.1a2639a                  [Up-to-date]\r\nUpdating platformio/toolchain-gccarmnoneeabi  1.70201.0 @ >=1.60301.0,<1.80000.0 [Up-to-date]\r\nUpdating git+https://github.com/meshtastic/Adafruit_nRF52_Arduino.git 0.21.0+sha.d8179b9                 [Up-to-date]\r\nUpdating platformio/tool-sreccat              1.164.0 @ ~1.164.0                 [Up-to-date]\r\nUpdating platformio/tool-jlink                1.65200.0 @ ^1.63208.0             [Outdated 1.68801.0]\r\nTool Manager: Installing platformio/tool-jlink @ 1.68801.0\r\nTool Manager: tool-jlink @ 1.68801.0 has been installed!\r\nTool Manager: Removing tool-jlink @ 1.65200.0\r\nTool Manager: tool-jlink @ 1.65200.0 has been removed!\r\nTool Manager: Removing toolchain-gccarmnoneeabi @ 1.70201.0\r\nTool Manager: toolchain-gccarmnoneeabi @ 1.70201.0 has been removed!\r\n\r\n\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1224, in _process_result\r\n    value = ctx.invoke(self.result_callback, value, **ctx.params)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 21, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 69, in process_result\r\n    maintenance.on_platformio_end(ctx, result)\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\platformio\\maintenance.py\", line 56, in on_platformio_end\r\n    check_internal_updates(ctx, \"platforms\")\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\platformio\\maintenance.py\", line 279, in check_internal_updates\r\n    pm.outdated(pkg).is_outdated(),\r\n  File \"c:\\users\\kfirg\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\_update.py\", line 29, in outdated\r\n    assert os.path.isdir(pkg.path) and pkg.metadata\r\nAssertionError\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3818
