### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by knausis** [platformio/platformio-home#1837]
Server error: {"type":"FileNotFoundError","args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\viksn\\\\Documents\\\\PlatformIO\\\\Projects\\\\201207-104159-uno'"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
