### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by anthonyl822** [platformio/platformio-home#1846]
PIO Core Call Error: "Platform /Users/anthonyl/.platformio/platforms/espressif8266\n--------\nUpdating espressif8266                        2.2.2                              [Outdated 2.6.2]\nPlatform Manager: Installing espressif8266 @ 2.6.2\nPlatform Manager: espressif8266 @ 2.6.2 has been installed!\nTool Manager: Installing toolchain-xtensa @ ~2.40802.191122\nTool Manager: Warning! More than one package has been found by toolchain-xtensa @ ~2.40802.191122 requirements:\n - platformio/toolchain-xtensa @ 2.100100.200706\n - mcspr/toolchain-xtensa @ 5.100200.200918\nTool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts\nTool Manager: toolchain-xtensa @ 2.40802.200502 has been installed!\nTool Manager: tool-esptool @ 1.413.0 is already installed\nTool Manager: Installing tool-esptoolpy @ ~1.20800.0\nTool Manager: tool-esptoolpy @ 1.20800.0 has been installed!\nTool Manager: Removing framework-arduinoespressif8266 @ 2.20502.0\nTool Manager: framework-arduinoespressif8266 @ 2.20502.0 has been removed!\nUpdating platformio/toolchain-xtensa          2.40802.200502 @ ~2.40802.191122   [Up-to-date]\nUpdating tool-esptool                         1.413.0 @ <2                       [Up-to-date]\nUpdating platformio/tool-esptoolpy            1.20800.0 @ ~1.20800.0             \n\nError: Traceback (most recent call last):\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/commands/platform.py\", line 420, in platform_update\n    pm.update(\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/platform.py\", line 120, in update\n    p.update_packages(only_check)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/platform/_packages.py\", line 124, in update_packages\n    self.pm.update(\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_update.py\", line 105, in update\n    outdated = self.outdated(pkg, to_spec)\n  File \"/Users/anthonyl/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_update.py\", line 29, in outdated\n    assert os.path.isdir(pkg.path) and pkg.metadata\nAssertionError\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3818
