### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by ruguodangshi0809** [platformio/platformio-home#185]
PIO Core Call Error: "PlatformManager: Installing gd32v\ngd32v @ 1.1.0 has been successfully installed!\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment. Anyway, you can submit a feature request here https://github.com/sipeed/platform-gd32v/issues
