### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by anh-ifdl** [platformio/platformio-home#1853]
PIO Core Call Error: "Library Storage: /Users/nguyenkimanh/Documents/PlatformIO/Projects/OmronD6T_sample/.pio/libdeps/m5stack-core-esp32\nLibrary Manager: Installing OmronD6T_44L_06\n\n\nError: Could not find the package with 'OmronD6T_44L_06' requirements for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2144
