### ISSUE TITLE
Error: HTTPSConnectionPool

### ISSUE THREAD

**Issue by DanielJRusev** [platformio/platformio-home#1866]
Hi can you please give me a hand with this problem ? 

I've tried to reinstall everything from scratch - doesn't help.
I've got stable internet connection

I'm running on a Mac with Mojave 10.14.6

> Executing task: pio run --target upload --target monitor <

Processing esp-wrover-kit (platform: espressif32; board: esp-wrover-kit; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing platformio/tool-mkspiffs @ ~2.230.0
Error: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v3/packages/platformio/tool/tool-mkspiffs (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x110438fd0>, 'Connection to api.registry.ns1.platformio.org timed out. (connect timeout=10)'))
The terminal process "pio 'run', '--target', 'upload', '--target', 'monitor'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1348
