### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by n9wxu** [platformio/platformio-home#187]
PIO Core Call Error: "Library Storage: C:\\Users\\XXXXX\\.platformio\\lib\r\nLibraryManager: Installing id=942 @ ^2.27.3\r\n\n\nError: Got an unrecognized status code '403' when downloaded http://dl.platformio.org/libraries/archives/9/23993.tar.gz"

**Comment by Super169** [comment]
Same problem, cannot install library even reinstall everything.
