### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by artchula** [platformio/platformio-home#189]
PIO Core Call Error: "********************************************************************************\nObsolete PIO Core v4.1.0 is used (previous was 4.1.1b5)\nPlease remove multiple PIO Cores from a system:\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\n********************************************************************************\nPlatformManager: Installing platform-gd32v\ngd32v @ 9126465 has been successfully installed!\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment. Anyway, you can submit a feature request here https://github.com/sipeed/platform-gd32v/issues
