### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by UKWRadio** [platformio/platformio-home#1896]
Server error: {"type":"FileNotFoundError","args":[2,"Das System kann die angegebene Datei nicht finden"],"message":"[WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\\\Users\\\\FB\\\\Documents\\\\PlatformIO'"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
