### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by artchula** [platformio/platformio-home#190]
PIO Core Call Error: "********************************************************************************\nObsolete PIO Core v4.1.0 is used (previous was 4.1.1b5)\nPlease remove multiple PIO Cores from a system:\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\n********************************************************************************\n\nThe current working directory /Users/MASTER/Documents/PlatformIO/Projects/191219-130249-longan-nano-blink will be used for the project.\n\nThe next files/directories have been created in /Users/MASTER/Documents/PlatformIO/Projects/191219-130249-longan-nano-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment. Anyway, you can submit a feature request here https://github.com/sipeed/platform-gd32v/issues
