### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by mereshow** [platformio/platformio-home#1918]
PIO Core Call Error: "b''\n\nError: Traceback (most recent call last):\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/commands/lib/command.py\", line 262, in lib_update\n    outdated = lm.outdated(pkg, spec)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_update.py\", line 46, in outdated\n    reg_pkg = self.fetch_registry_package(pkg.metadata.spec)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_registry.py\", line 144, in fetch_registry_package\n    result = regclient.get_package(self.pkg_type, spec.owner, spec.name)\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/clients/registry.py\", line 136, in get_package\n    return self.fetch_json_data(\n  File \"/home/alberto/.platformio/penv/lib/python3.8/site-packages/platformio/clients/http.py\", line 143, in fetch_json_data\n    return json.loads(result)\n  File \"/usr/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3818
