### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by danielgonzacas** [platformio/platformio-home#1928]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\dgc84\\.platformio\\platforms\\atmelavr metadata=PackageMetaData <type=platform name=atmelavr version=3.0.0 spec={'owner': 'platformio', 'id': 8006, 'name': 'atmelavr', 'requirements': None, 'url': None}'"

**Comment by LennartArendt** [comment]
Just had the same problem, try deleting the C:\Users\?????\.platformio\platforms\atmelavr folder and hit build again. 
For me it installed the platform again and everything worked!

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
