### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by sergyv** [platformio/platformio-home#1937]
PIO Core Call Error: "The current working directory C:\\Users\\svlad\\OneDrive\\Documents\\PlatformIO\\Projects\\MC60test will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\svlad\\OneDrive\\Documents\\PlatformIO\\Projects\\MC60test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatform Manager: Installing siwigsm\r\nPlatform Manager: siwigsm @ 0.5.0 has been installed!\r\nTool Manager: toolchain-gccarmnoneeabi @ 1.80201.190214 is already installed\r\nTool Manager: Installing framework-siwisdk @ ~0.5.0\r\n\n\nError: Could not find the package with 'framework-siwisdk @ ~0.5.0' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2144
