### ISSUE TITLE
Could not initialize project (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by hansfbaier** [platformio/platformio-home#1943]
PIO Core Call Error: "The current working directory /home/jack/Documents/PlatformIO/Projects/STM32UsbAudio will be used for the project.\n\nThe next files/directories have been created in /home/jack/Documents/PlatformIO/Projects/STM32UsbAudio\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing black_f407vg (platform: ststm32; board: black_f407vg; framework: arduino)\n--------------------------------------------------------------------------------\nTool Manager: Installing platformio/tool-scons @ ~4.40001.0\nTool Manager: tool-scons @ 4.40001.0 has been installed!\nTool Manager: Removing tool-scons @ 2.20501.190826\nTool Manager: tool-scons @ 2.20501.190826 has been removed!\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'black_f407vg'\n========================== [FAILED] Took 4.86 seconds =========================="

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/1768
