### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by Vanvu396** [platformio/platformio-home#1947]
PIO Core Call Error: "Library Storage: E:\\Do_an_tot_nghiep\\ESP8266\\.pio\\libdeps\\nodemcu\r\nLibrary Manager: Installing FirebaseESP8266\r\n\n\nError: Could not find the package with 'FirebaseESP8266' requirements for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2144
