### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by chemkot** [platformio/platformio-home#195]
PIO Core Call Error: "The current working directory /home/****/Documents/PlatformIO/Projects/hygro_controller will be used for the project.\n\nThe next files/directories have been created in /home/****/Documents/PlatformIO/Projects/hygro_controller\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing stm8sblue (platform: ststm8; board: stm8sblue; framework: spl)\n--------------------------------------------------------------------------------\nPackageManager: Installing framework-ststm8spl @ 0.20301.181217\nframework-ststm8spl @ 0.20301.181217 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblue.html\nPLATFORM: ST STM8 1.0.1 > ST STM8S103F3 Breakout Board\nHARDWARE: STM8S103F3P6 16MHz, 1KB RAM, 8KB Flash\nPACKAGES: framework-ststm8spl 0.20301.181217 (2.3.1), tool-stm8binutils 0.230.0 (2.30), toolchain-sdcc 1.30804.10766 (3.8.4)\nError: Could not parse library files for the target.\nstm8s.h:2723:25: fatal error: stm8s_conf.h: No such file or directory\n\n********************************************************************\n* Looking for stm8s_conf.h dependency? Check our library registry!\n*\n* CLI  > platformio lib search \"header:stm8s_conf.h\"\n* Web  > https://platformio.org/lib/search?query=header:stm8s_conf.h\n*\n********************************************************************\n\ncompilation terminated.========================= [FAILED] Took 13.42 seconds ========================="

**Comment by ivankravets** [comment]
Please update dev-platforms. Resolved in https://github.com/platformio/platform-ststm8/issues/6
