### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by ACMSoft** [platformio/platformio-home#1952]
PIO Core Call Error: "Platform Manager: Installing git+https://github.com/markbeee/SHT21\ngit version 2.17.1\n\n\nCloning into '/home/alienc/.platformio/.cache/tmp/pkg-installing-tv3gwuh3'...\nError: Could not find one of 'platform.json' manifest files in the package"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/1785
