### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by vortex314** [platformio/platformio-home#1970]
PIO Core Call Error: "The current working directory /Users/lieven/Documents/PlatformIO/Projects/f411 will be used for the project.\n\nThe next files/directories have been created in /Users/lieven/Documents/PlatformIO/Projects/f411\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'genericSTM32F411CE'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/1768
