### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by iamjosegoes** [platformio/platformio-home#198]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\jose.goes\\\\.platformio\\\\platforms\\\\pio-framework-arduino-lpc176x\\\\platform.json'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/408
