### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by liessem** [platformio/platformio-home#1981]
PIO Core Call Error: "DLL load failed: Não foi possível encontrar o procedimento especificado."

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core. Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type
```
pio upgrade --dev
```

Restart VSCode.
