### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by david3a** [platformio/platformio-home#1990]
PIO Core Call Error: "The current working directory C:\\icotest\\fc-range\\FC1000\\FC1000 USB Interface will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\icotest\\fc-range\\FC1000\\FC1000 USB Interface\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Unknown board ID 'adafruit_qt_py_m0'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/1768
