### ISSUE TITLE
No se pudo cargar la lista de tableros

### ISSUE THREAD

**Issue by lledossoff** [platformio/platformio-home#1994]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\34656\\.platformio\\platforms\\ststm32@9.0.0 metadata=PackageMetaData <type=platform name=ststm32 version=9.0.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
