### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by matymic** [platformio/platformio-home#2006]
Server error: {"type":"FileNotFoundError","args":[2,"Das System kann die angegebene Datei nicht finden"],"message":"[WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\\\Users\\\\MICHI\\\\Documents\\\\PlatformIO'"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
