### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by khoffy** [platformio/platformio-home#201]
PIO Core Call Error: "The current working directory /home/khoffy/Documents/PlatformIO/Projects/NewMspProject will be used for the project.\n\nThe next files/directories have been created in /home/khoffy/Documents/PlatformIO/Projects/NewMspProject\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing lpmsp430g2452 (platform: timsp430; board: lpmsp430g2452; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'lpmsp430g2452'\n========================== [FAILED] Took 1.41 seconds =========================="

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/155
