### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by alstrazz** [platformio/platformio-home#2016]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\alessandro\\.platformio\\platforms\\espressif8266 metadata=PackageMetaData <type=platform name=espressif8266 version=2.6.2 spec={'owner': 'platformio', 'id': 8008, 'name': 'espressif8266', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
