### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by cgwhynot** [platformio/platformio-home#2038]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Dawn\\.platformio\\platforms\\atmelsam@5.1.0 metadata=PackageMetaData <type=platform name=atmelsam version=5.1.0 spec={'owner': None, 'id': None, 'name': 'atmelsam', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
