### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by DoanNguyenTrong** [platformio/platformio-home#2062]
PIO Core Call Error: "The current working directory /Users/nguyendoan/Documents/PlatformIO/Projects/stm32f446_queue_application will be used for the project.\n\nThe next files/directories have been created in /Users/nguyendoan/Documents/PlatformIO/Projects/stm32f446_queue_application\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing nucleo_f446re (platform: ststm32; board: nucleo_f446re; framework: stm32cube)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/nucleo_f446re.html\nPLATFORM: ST STM32 (11.0.0) > ST Nucleo F446RE\nHARDWARE: STM32F446RET6 180MHz, 128KB RAM, 512KB Flash\nDEBUG: Current (stlink) On-board (stlink) External (blackmagic, cmsis-dap, jlink)\nPACKAGES: \n - framework-stm32cubef4 1.25.2 \n - tool-ldscripts-ststm32 0.1.0 \n - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\nLDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf\nLDF Modes: Finder ~ chain, Compatibility ~ soft\nValueError: Please set custom_freertos_config_location in your platformio.ini to the location of a FreeRTOSConfig.h header file -- relative to the location of platformio.ini:\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py\", line 170:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 598:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 287:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/Users/nguyendoan/.platformio/platforms/ststm32/builder/main.py\", line 99:\n    target_elf = env.BuildProgram()\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 62:\n    env.ProcessProjectDeps()\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 140:\n    project_lib_builder = env.ConfigureProjectLibBuilder()\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 1064:\n    lib_builders = env.GetLibBuilders()\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 993:\n    lb = LibBuilderFactory.new(env, lib_dir)\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 61:\n    obj = getattr(sys.modules[__name__], clsname)(env, path, verbose=verbose)\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 137:\n    self.process_extra_options()\n  File \"/Users/nguyendoan/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 280:\n    self.env.SConscript(\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 598:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/Users/nguyendoan/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 287:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/Users/nguyendoan/.platformio/lib/STM32Cube Middleware-FreeRTOS/add_config.py\", line 15:\n    raise ValueError(\"Please set custom_freertos_config_location in your platformio.ini to the location of a FreeRTOSConfig.h header file -- relative to the location of platformio.ini\")\n========================== [FAILED] Took 0.59 seconds =========================="

**Comment by ivankravets** [comment]
Please set custom_freertos_config_location in your platformio.ini to the location of a FreeRTOSConfig.h header file -- relative to the location of platformio.ini
