### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by TimSet0815** [platformio/platformio-home#2064]
PIO Core Call Error: "DLL load failed: Die angegebene Prozedur wurde nicht gefunden."

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core. Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type
```
pio upgrade --dev
```

Restart VSCode.
