### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by Alex38Lyon** [platformio/platformio-home#2069]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\alexa\\.platformio\\platforms\\atmelsam@4.5.1 metadata=PackageMetaData <type=platform name=atmelsam version=4.5.1 spec={'owner': 'platformio', 'id': 8007, 'name': 'atmelsam', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

Could you provide more details on how to reproduce this issue?
