### ISSUE TITLE
Libraries: Search stuck on loading

### ISSUE THREAD

**Issue by raymondhcyu** [platformio/platformio-home#207]
PIO Core Call Error: "Error: [API] Could not connect to PlatformIO API Service. Please try later."

Tried cleaning and restarting VSCode, issue persists. Version 4.1.0

**Comment by lbussy** [comment]
I just swung by here to search for similar issues and here it is.  +1 from me.

**Comment by raymondhcyu** [comment]
Looks like they're back online!
