### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by jamalchelski** [platformio/platformio-home#2079]
PIO Core Call Error: "DLL load failed: The specified procedure could not be found."

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core. Please open [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and type
```
pio upgrade --dev
```

Restart VSCode.
