### ISSUE TITLE
Inspect view - Clickable filenames in defect report

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#21]
If possible, make the file-names / line numbers link to the relevant file/line number. VSCode lets you Ctrl+Click filename/line numbers for errors normally, but that isn't working here. 

Completely understandable if this is not possible due to it being too IDE specific. 

![image](https://user-images.githubusercontent.com/5500713/67675257-67b2ec80-f9ca-11e9-972a-ff781aaada7e.png)

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-home/commit/1fe644429e714a15d832f1fbfdb59e07b6abedc5

I'll inform about new 3.0.0-beta.2
