### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by FredByrman** [platformio/platformio-home#2102]
Server error: {"type":"FileNotFoundError","args":[2,"Het systeem kan het opgegeven bestand niet vinden"],"message":"[WinError 2] Het systeem kan het opgegeven bestand niet vinden: 'C:\\\\Users\\\\Preferred Customer\\\\Documents\\\\PlatformIO'"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
