### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by FelipeMiiller** [platformio/platformio-home#2118]
PIO Core Call Error: "Platform Manager: Installing git+https://github.com/esp8266/Arduino.git\r\ngit version 2.27.0.windows.1\nSubmodule path 'libraries/ESP8266SdFat': checked out '0a46e4ebb2de585c5a64f981dbc2b2223a438984'\nSubmodule path 'libraries/Ethernet': checked out '75a3c37b5e513305b82e926ca6a4f8190f536c9d'\nSubmodule path 'libraries/LittleFS/lib/littlefs': checked out '1a59954ec64ca168828a15242cc6de94ac75f9d1'\nSubmodule path 'libraries/SoftwareSerial': checked out 'adec3fe4f16ef3a61463c0b4eaeafebcb5487a45'\nSubmodule path 'tools/esptool': checked out '4fa0bd7b0d1f69f5ff22b043adc07c5e562a8931'\nSubmodule path 'tools/pyserial': checked out '0e7634747568547b8a7f9fd0c48ed74f16af4b23'\nSubmodule path 'tools/sdk/lwip2/builder': checked out '7421258237b7c8f61629226961af498a0a6e0096'\nSubmodule path 'tools/sdk/ssl/bearssl': checked out 'c0b69dfb837f0027180c72f13f7c90cfafb83c16'\nSubmodule path 'tools/sdk/uzlib': checked out '42398df66c02da1cec387b634b6d2f285007a7af'\n\n\nCloning into 'C:\\Users\\felip\\.platformio\\.cache\\tmp\\pkg-installing-x58hloe9'...\nUpdating files:  83% (993/1185)\rUpdating files:  84% (996/1185)\rUpdating files:  85% (1008/1185)\rUpdating files:  86% (1020/1185)\rUpdating files:  87% (1031/1185)\rUpdating files:  88% (1043/1185)\rUpdating files:  89% (1055/1185)\rUpdating files:  90% (1067/1185)\rUpdating files:  91% (1079/1185)\rUpdating files:  92% (1091/1185)\rUpdating files:  93% (1103/1185)\rUpdating files:  94% (1114/1185)\rUpdating files:  95% (1126/1185)\rUpdating files:  96% (1138/1185)\rUpdating files:  97% (1150/1185)\rUpdating files:  98% (1162/1185)\rUpdating files:  98% (1170/1185)\rUpdating files:  99% (1174/1185)\rUpdating files: 100% (1185/1185)\rUpdating files: 100% (1185/1185), done.\nSubmodule 'libraries/ESP8266SdFat' (https://github.com/earlephilhower/ESP8266SdFat.git) registered for path 'libraries/ESP8266SdFat'\nSubmodule 'libraries/Ethernet' (https://github.com/arduino-libraries/Ethernet.git) registered for path 'libraries/Ethernet'\nSubmodule 'libraries/LittleFS/lib/littlefs' (https://github.com/ARMmbed/littlefs.git) registered for path 'libraries/LittleFS/lib/littlefs'\nSubmodule 'libraries/SoftwareSerial' (https://github.com/plerup/espsoftwareserial.git) registered for path 'libraries/SoftwareSerial'\nSubmodule 'tools/esptool' (https://github.com/espressif/esptool.git) registered for path 'tools/esptool'\nSubmodule 'tools/pyserial' (https://github.com/pyserial/pyserial.git) registered for path 'tools/pyserial'\nSubmodule 'lwip2' (https://github.com/d-a-v/esp82xx-nonos-linklayer.git) registered for path 'tools/sdk/lwip2/builder'\nSubmodule 'tools/sdk/ssl/bearssl' (https://github.com/earlephilhower/bearssl-esp8266.git) registered for path 'tools/sdk/ssl/bearssl'\nSubmodule 'tools/sdk/uzlib' (https://github.com/earlephilhower/uzlib.git) registered for path 'tools/sdk/uzlib'\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/libraries/ESP8266SdFat'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/libraries/Ethernet'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/libraries/LittleFS/lib/littlefs'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/libraries/SoftwareSerial'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/tools/esptool'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/tools/pyserial'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/tools/sdk/lwip2/builder'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/tools/sdk/ssl/bearssl'...\nCloning into 'C:/Users/felip/.platformio/.cache/tmp/pkg-installing-x58hloe9/tools/sdk/uzlib'...\nError: Could not find one of 'platform.json' manifest files in the package"

**Comment by ivankravets** [comment]
Could not find one of 'platform.json' manifest files in the package"
