### ISSUE TITLE
Kan geïnstalleerde platforms niet laden

### ISSUE THREAD

**Issue by theo-ctrl** [platformio/platformio-home#2130]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\theo\\.platformio\\platforms\\nxplpc-arduino-lpc176x metadata=PackageMetaData <type=platform name=nxplpc-arduino-lpc176x version=0.1.3 spec={'owner': None, 'id': None, 'name': 'pio-nxplpc-arduino-lpc176x', 'requirements': None, 'url': 'https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip'}'"

**Comment by ivankravets** [comment]
Fixed in the latest version. Please run `pio update` and restart VSCode.
