### ISSUE TITLE
Could not load PIO Account information

### ISSUE THREAD

**Issue by mripv6** [platformio/platformio-home#214]
PIO Core Call Error: "Error: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by ivankravets** [comment]
Everything should work now. Please restart VSCode.
