### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by wilsonintai76** [platformio/platformio-home#2142]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\wilson\\.platformio\\platforms\\ststm32@8.1.0 metadata=PackageMetaData <type=platform name=ststm32 version=8.1.0 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Could you provide more details on how to reproduce this issue?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123
