### ISSUE TITLE
Libraries: Stats

### ISSUE THREAD

**Issue by inquisitour** [platformio/platformio-home#2152]
PIO Core Call Error: "Error: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v2/lib/stats (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd166a88430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1348
