### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by krepton1985** [platformio/platformio-home#2156]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\.platformio\\platforms\\atmelsam metadata=PackageMetaData <type=platform name=atmelsam version=5.1.1 spec={'owner': 'platformio', 'id': 8007, 'name': 'atmelsam', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
How to reproduce this issue?

**Comment by ivankravets** [comment]
Fixed in the latest version. Please run `pio update` and restart VSCode.
