### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by applesama** [platformio/platformio-home#2157]
PIO Core Call Error: "The current working directory F:\\ArduinoEsp\\WeatherStation will be used for the project.\r\n\r\nThe next files/directories have been created in F:\\ArduinoEsp\\WeatherStation\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError:"

**Comment by ivankravets** [comment]
Please update PlatformIO IDE to the latest version and use the latest PIO Core.

You can run `pio upgrade` command.
