### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by riverskin** [platformio/platformio-home#2158]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\river\\.platformio\\platforms\\ststm32@6.1.1 metadata=PackageMetaData <type=platform name=ststm32 version=6.1.1 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123
