### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by DarkNight21** [platformio/platformio-home#2159]
PIO Core Call Error: "Error: The directory `C:\\Users\\Frank-Superrechner\\.platformio` or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually `C:\\Users\\Frank-Superrechner\\.platformio` directory and PlatformIO will create new from the current user."

**Comment by ivankravets** [comment]
Error: The directory C:\\Users\\Frank-Superrechner\\.platformio or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually C:\\Users\\Frank-Superrechner\\.platformio directory and PlatformIO will create new from the current user.
