### ISSUE TITLE
Could not load installed platforms

### ISSUE THREAD

**Issue by Cathprotech** [platformio/platformio-home#2162]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\Martin\\.platformio\\platforms\\espressif32@2.0.0 metadata=PackageMetaData <type=platform name=espressif32 version=2.0.0 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Fixed in the latest version. Please run `pio update` and restart VSCode.

**Comment by Cathprotech** [comment]
Thank you
