### ISSUE TITLE
Could not load boards list, I'm trying to install ender 3 firmware on the 4.27 board and I keep running in to this problem. 

### ISSUE THREAD

**Issue by elijah-berger** [platformio/platformio-home#2174]
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\elibe\\.platformio\\platforms\\ststm32 metadata=PackageMetaData <type=platform name=ststm32 version=10.0.1 spec={'owner': 'platformio', 'id': 8020, 'name': 'ststm32', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
How to reproduce this issue?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123

**Comment by elijah-berger** [comment]
I don't know what you mean by reproducible.
