### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by Bubbles321** [platformio/platformio-home#2182]
Visual Source Code v1.51.1
From PIO home, updated Boards list, got the following error:
PIO Core Call Error: "Error: Unknown development platform 'PackageItem <path=C:\\Users\\colin\\.platformio\\platforms\\atmelavr@3.0.0 metadata=PackageMetaData <type=platform name=atmelavr version=3.0.0 spec={'owner': None, 'id': None, 'name': 'atmelavr', 'requirements': None, 'url': None}'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/2123
