### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by gatsby27** [platformio/platformio-home#2197]
This message will appear when I create a new project named "Test" with platformio/vscode/windows10.

Server error: {"type":"FileNotFoundError","args":[2,"Le fichier spécifié est introuvable"],"message":"[WinError 2] Le fichier spécifié est introuvable: 'C:\\\\Users\\\\Sonia\\\\Documents\\\\PlatformIO\\\\Projects\\\\Test'"}

This is the first try after installing  VSCode with PlatforIO extension and Python 3.9.1

Could you help me going on

Best regards

**Comment by fancellu** [comment]
Me too
