### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by jompiter** [platformio/platformio-home#2201]
PIO Core Call Error: "The current working directory C:\\Users\\jompi\\Documents\\Impresora\\Marlin\\Marlin will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\jompi\\Documents\\Impresora\\Marlin\\Marlin\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/framework-arduino-avr @ ~5.1.0\r\nTool Manager: framework-arduino-avr @ 5.1.0 has been installed!\r\nTool Manager: Installing platformio/tool-scons @ ~4.40100.2\r\nTool Manager: tool-scons @ 4.40100.2 has been installed!\r\nSCons import failed. Unable to find engine files in:\r\n  C:\\Users\\jompi\\.platformio\\packages\\tool-scons\\..\r\n  C:\\Users\\jompi\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\jompi\\.platformio\\packages\\tool-scons\\scons.py\", line 87, in <module>\r\n    import SCons.Script\r\n  File \"C:\\Users\\jompi\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\__init__.py\", line 85, in <module>\r\nImportError: cannot import name 'Main' from 'SCons.Script' (C:\\Users\\jompi\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\__init__.py)\r\n========================= [FAILED] Took 48.25 seconds ========================="

**Comment by fancellu** [comment]
Me too
