### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by BeeGeeBee** [platformio/platformio-home#2202]
I have been building projects ok until an hour ago. I created a new project and tried compiling it and got the missing scons.py error message.

I get this with any projects I was building successfully only an hour ago. It looks like the core was automatically updated and I cannot see the scons.py. I see pio Home says the core is 5.1.0  and this is on Windows 10.

I have tried uninstalling Platformio and reinstalling the extension and get the same error. Should I remove the extension from VSCode and remove the .platformio folder and try adding the extension again ?

Error Text:

PIO Core Call Error: "The current working directory C:\\Users\\Bernie\\avrprojects\\testtft will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Bernie\\avrprojects\\testtft\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nC:\\Users\\Bernie\\.platformio\\python3\\python.exe: can't open file 'C:\\Users\\Bernie\\.platformio\\packages\\tool-scons\\scons.py': [Errno 2] No such file or directory\r\n========================== [FAILED] Took 0.41 seconds =========================="

**Comment by ivankravets** [comment]
Hm... Please remove `C:\Users\Bernie\.platformio\packages\tool-scons` folder and restart VSCode.
