### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by rudydevolder** [platformio/platformio-home#227]
PIO Core Call Error: "Error: Unknown development platform '/home/rudy/.platformio/platforms/atmelavr'"

**Comment by ming-chu** [comment]
try ```pio platform install atmelavr```

**Comment by rudydevolder** [comment]
Problem solved (by itself) . The website of platformio was busy crashing at that time and I just finished a fresh install of pio. Just  in a period the website was intermittently going slow and on and off before it crashed completely. Sorry I forgot to close this case. Thank you anyway Ming-chu for the reply ;)
