### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by kilowhisk** [platformio/platformio-home#2374]
PIO Core Call Error: "The current working directory /home/ken/Documents/PlatformIO/Projects/ardunio blink  will be used for the project.\n\nThe next files/directories have been created in /home/ken/Documents/PlatformIO/Projects/ardunio blink \ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatform Manager: Installing atmelavr\nPlatform Manager: atmelavr @ 3.2.0 has been installed!\nTool Manager: Installing platformio/toolchain-atmelavr @ ~1.70300.0\nTool Manager: toolchain-atmelavr @ 1.70300.191015 has been installed!\nThe platform 'atmelavr' has been successfully installed!\nThe rest of the packages will be installed later depending on your build environment.\n\n\nError: Processing uno (platform: atmelavr; board: uno; framework: arduino)\n--------------------------------------------------------------------------------\nTool Manager: Installing platformio/framework-arduino-avr @ ~5.1.0\nTool Manager: framework-arduino-avr @ 5.1.0 has been installed!\nTool Manager: Installing platformio/tool-scons @ ~4.40100.2\nTool Manager: tool-scons @ 4.40100.2 has been installed!\nVerbose mode can be enabled via `-v, --verbose` option\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ken/Documents/PlatformIO/Projects/ardunio blink':\n  File \"/home/ken/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py\", line 167:\n    env.LoadPioPlatform()\n  File \"/home/ken/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py\", line 658:\n    return self.method(*nargs, **kwargs)\n  File \"/home/ken/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/pioplatform.py\", line 103:\n    board_config = env.BoardConfig()\n  File \"/home/ken/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py\", line 658:\n    return self.method(*nargs, **kwargs)\n  File \"/home/ken/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/pioplatform.py\", line 46:\n    with fs.cd(env.subst(\"$PROJECT_DIR\")):\n  File \"/home/ken/.platformio/penv/lib/python3.7/site-packages/platformio/fs.py\", line 36:\n    os.chdir(self.new_path)\n========================= [FAILED] Took 23.69 seconds ========================="

**Comment by devozdemirhasancan** [comment]
Check your windows settings 
![image](https://user-images.githubusercontent.com/45903083/112837424-8c6e3080-90a4-11eb-8da5-80585ba9b8eb.png)
