### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Jdominguez991** [platformio/platformio-home#2377]
PIO Core Call Error: "The current working directory C:\\Users\\jason\\Downloads\\test2 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\jason\\Downloads\\test2\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Could not install package 'platformio/framework-arduinoespressif8266 @ ~3.20704.0' for 'windows_amd64' system"

**Comment by devozdemirhasancan** [comment]
Check your windows settings 
![image](https://user-images.githubusercontent.com/45903083/112837424-8c6e3080-90a4-11eb-8da5-80585ba9b8eb.png)
