### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by TranQuangVu1001** [platformio/platformio-home#2384]
PIO Core Call Error: "The current working directory C:\\Users\\QuangVu\\Documents\\PlatformIO\\Projects\\hello will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\QuangVu\\Documents\\PlatformIO\\Projects\\hello\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing lolin32 (platform: espressif32; board: lolin32; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin32.html\r\nPLATFORM: Espressif 32 (3.1.1) > WEMOS LOLIN32\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40200.210118 (4.2.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.30000.201119 (3.0.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.191205 (2.28.51) \r\n - toolchain-xtensa32 2.80400.210211 (8.4.0)\r\nInstalling windows-curses package\r\nProcessing c:\\users\\quangvu\\.platformio\\packages\\framework-espidf\\tools\\kconfig_new\\esp-windows-curses\r\nERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\QuangVu\\\\.platformio\\\\packages\\\\framework-espidf\\\\tools\\\\kconfig_new\\\\esp-windows-curses'\r\n\r\n*** Error 1\r\nReading CMake configuration...\r\nOSError: [WinError 193] %1 is not a valid Win32 application:\r\n  File \"C:\\Users\\QuangVu\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\main.py\", line 177:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\SConscript.py\", line 591:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\SConscript.py\", line 280:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\platforms\\espressif32\\builder\\main.py\", line 225:\r\n    target_elf = env.BuildProgram()\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Util.py\", line 658:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 61:\r\n    env.ProcessProgramDeps()\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Util.py\", line 658:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 127:\r\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Util.py\", line 658:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 342:\r\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\SConscript.py\", line 654:\r\n    return method(*args, **kw)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\SConscript.py\", line 591:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\packages\\tool-scons\\scons-local-4.1.0\\SCons\\Script\\SConscript.py\", line 280:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\platforms\\espressif32\\builder\\frameworks\\espidf.py\", line 1108:\r\n    project_codemodel = get_cmake_code_model(\r\n  File \"C:\\Users\\QuangVu\\.platformio\\platforms\\espressif32\\builder\\frameworks\\espidf.py\", line 212:\r\n    run_cmake(src_dir, build_dir, extra_args)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\platforms\\espressif32\\builder\\frameworks\\espidf.py\", line 665:\r\n    run_tool(cmd)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\platforms\\espressif32\\builder\\frameworks\\espidf.py\", line 620:\r\n    result = exec_command(cmd, env=idf_env)\r\n  File \"c:\\users\\quangvu\\.platformio\\penv\\lib\\site-packages\\platformio\\proc.py\", line 117:\r\n    p = subprocess.Popen(*args, **kwargs)\r\n  File \"C:\\Users\\QuangVu\\.platformio\\python3\\lib\\subprocess.py\", line 951:\r\n    self._execute_child(args, executable, preexec_fn, close_fds,\r\n  File \"C:\\Users\\QuangVu\\.platformio\\python3\\lib\\subprocess.py\", line 1420:\r\n    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,\r\n========================== [FAILED] Took 1.04 seconds =========================="

**Comment by devozdemirhasancan** [comment]
Check your windows settings 
![image](https://user-images.githubusercontent.com/45903083/112837424-8c6e3080-90a4-11eb-8da5-80585ba9b8eb.png)
