### ISSUE TITLE
platformio.org is down.

### ISSUE THREAD

**Issue by laschlo** [platformio/platformio-home#240]
It seems platformio.org domain is down - at least to reachable in Poland, Europe.
Same for platformio trying to reach libraries:
ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80)

Checked for both wired and mobile connection, different devices.

**Comment by TryIoT** [comment]
Same here in Germany.

**Comment by Karshilistic** [comment]
I believe this is the same for everyone. The thing is, this has happened often the last while, and it's making PlatformIO somewhat unreliable. Their teams need to get this figured out.

**Comment by ivankravets** [comment]
It should work now. Sorry for the issue.
