### ISSUE TITLE
Libraries: Search

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-home#245]
PIO Core Call Error: "Error: [API] Invalid response: b'<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body bgcolor=\"white\">\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n'"

**Comment by ivankravets** [comment]
Please upgrade to the latest version.
