### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by powergt** [platformio/platformio-home#249]
PIO Core Call Error: "Library Storage: C:\\Users\\Bono\\.platformio\\lib\r\nLibraryManager: Installing id=89\r\n\n\nError: [API] Invalid response: b'<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\"white\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n'"

**Comment by ivankravets** [comment]
Everything should work now. Please restart VSCode.
