### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by marcniedersachsen** [platformio/platformio-home#2660]
PIO Core Call Error: "Library Storage: /Users/marc/Documents/PlatformIO/Projects/ESP32-Paxcounter-master/.pio/libdeps/ota\nLibrary Manager: Installing laurencebank@gmail.com/BitBang_I2C @ ^2.1.3\n\n\nError: VCS: Unknown repository type laurencebank@gmail.com/BitBang_I2C"

**Comment by Stumblor** [comment]
Having this same issue with Laurence's other projects also:

laurencebank@gmail.com/AnimatedGIF @ ^1.4.1

**Comment by Stumblor** [comment]
This was formally bitbank2/AnimatedGIF@^1.3.2 so likely that change that has caused it?
