### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by yhoo** [platformio/platformio-home#273]
PIO Core Call Error: "********************************************************************************\nObsolete PIO Core v4.1.0 is used (previous was 4.1.1b7)\nPlease remove multiple PIO Cores from a system:\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\n********************************************************************************\n\nThe current working directory /Users/Jimmy/Documents/PlatformIO/Projects/water_irrigation will be used for the project.\n\nThe next files/directories have been created in /Users/Jimmy/Documents/PlatformIO/Projects/water_irrigation\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing espressif32\nespressif32 @ 1.11.1 has been successfully installed!\nPackageManager: Installing toolchain-xtensa32 @ ~2.50200.0\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\nThe platform 'espressif32' has been successfully installed!\nThe rest of packages will be installed automatically depending on your build environment.\n\n\nError: Traceback (most recent call last):\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/commands/init.py\", line 101, in cli\n    pg.generate()\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 125, in generate\n    tpl_vars = self._load_tplvars()\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 78, in _load_tplvars\n    tpl_vars.update(load_project_ide_data(self.project_dir, self.env_name) or {})\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/project/helpers.py\", line 153, in load_project_ide_data\n    raise result.exception\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/testing.py\", line 326, in invoke\n    cli.main(args=args or (), prog_name=prog_name, **extra)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py\", line 138, in cli\n    is_test_running,\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py\", line 170, in process_env\n    result = {\"env\": name, \"duration\": time(), \"succeeded\": ep.process()}\n  File \"/Users/Jimmy/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/processor.py\", line 65, in process\n    telemetry.send_run_environment(self.options, build_targets)\nAttributeError: module 'platformio.telemetry' has no attribute 'send_run_environment'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please upgrade PIO Core to the latest version
