### ISSUE TITLE
Could not initialize project( Raspberry Pi OS, Raspberry Pi 4B 2GB (Solved)

### ISSUE THREAD

**Issue by PIBSAS** [platformio/platformio-home#2871]
PIO Core Call Error: "[Errno 2] No such file or directory: 'platformio': 'platformio'"

**Comment by Luciano2018** [comment]
En Raspberry Pi OS, Instalado con los pasos:
python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
Agregado path a proflle:
nano .profile
El siguiente texto:
export PATH=$PATH:~/.platformio/penv/bin
Reiniciado Raspberry Pi OS
Ejecute:
platformio home
Abrio el navegador y al crear un proyecto tiro ese error
