### ISSUE TITLE
PIO Core Call Error: "'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by kalpabarbosa** [platformio/platformio-home#291]
PIO Core Call Error: "'utf-8' codec can't decode byte 0xe7 in position 809: invalid continuation byte"

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Which library are you going to install? What is your OS? Locale?
