### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by 772886054** [platformio/platformio-home#294]
PIO Core Call Error: "Library Storage: E:\\固件\\Marlin-dev-2.1.x\\.pio\\libdeps\\megaatmega2560\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 253, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 777, in update\n    pkg_dir = self.get_package_dir(*self.parse_pkg_uri(package))\n  File \"c:\\users\\allen\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 242, in parse_pkg_uri\n    text = str(text)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by jangofett4** [comment]
Pretty sure this is a problem caused because of `E:\固件\`, default ascii encoder cant encode that folder.  
Did you try to use a 'program friendly' folder (like say `E:\Projects\your_project_here`)
