### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by drphil3d** [platformio/platformio-home#295]
PIO Core Call Error: "Library Storage: C:\\Users\\Phil\\.platformio\\lib\nUpdating FastLED @ 3.2.9 [3.3.2]\r\nUninstalling FastLED @ 3.2.9: \t[OK]\nLooking for FastLED library in registry\nFound: https://platformio.org/lib/show/126/FastLED\nLibraryManager: Installing id=126 @ 3.3.2\r\nDownloading...\n\n\nError: Please read http://bit.ly/package-manager-ioerror\nError: Traceback (most recent call last):\n File \"c:\\python27\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\n cli() # pylint: disable=no-value-for-parameter\n File \"c:\\python27\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n return self.main(*args, **kwargs)\n File \"c:\\python27\\lib\\site-packages\\click\\core.py\", line 717, in main\n rv = self.invoke(ctx)\n File \"c:\\python27\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n return super(PlatformioCLI, self).invoke(ctx)\n File \"c:\\python27\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n return _process_result(sub_ctx.command.invoke(sub_ctx))\n File \"c:\\python27\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n return _process_result(sub_ctx.command.invoke(sub_ctx))\n File \"c:\\python27\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n return ctx.invoke(self.callback, **ctx.params)\n File \"c:\\python27\\lib\\site-packages\\click\\core.py\", line 555, in invoke\n return callback(*args, **kwargs)\n File \"c:\\python27\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\n return f(get_current_context(), *args, **kwargs)\n File \"c:\\python27\\lib\\site-packages\\platformio\\commands\\lib.py\", line 253, in lib_update\n lm.update(library, only_check=only_check)\n File \"c:\\python27\\lib\\site-packages\\platformio\\managers\\package.py\", line 816, in update\n self.install(name, latest, after_update=True)\n File \"c:\\python27\\lib\\site-packages\\platformio\\managers\\lib.py\", line 301, in install\n force=force,\n File \"c:\\python27\\lib\\site-packages\\platformio\\managers\\package.py\", line 698, in install\n pkg_dir = self._install_from_piorepo(name, requirements)\n File \"c:\\python27\\lib\\site-packages\\platformio\\managers\\lib.py\", line 151, in _install_from_piorepo\n requirements,\n File \"c:\\python27\\lib\\site-packages\\platformio\\managers\\package.py\", line 478, in _install_from_url\n dlpath = self.download(url, tmp_dir, sha1)\n File \"c:\\python27\\lib\\site-packages\\platformio\\managers\\package.py\", line 197, in download\n raise e\nChunkedEncodingError: (\"Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')\", error(10054, 'An existing connection was forcibly closed by the remote host'))\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by tjjdesign** [comment]
![image](https://user-images.githubusercontent.com/28579446/75120121-1d730c80-5646-11ea-8eb2-3d0b65b5ca4e.png)
Getting similar error here as well.
