### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by thaivuongha** [platformio/platformio-home#297]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\TA QUOC ANH\\\\.platformio\\\\platforms\\\\Arduino_Core_STM32\\\\platform.json'","type":"IOError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/408
