### ISSUE TITLE
Could not load PIO Account information

### ISSUE THREAD

**Issue by bashyftw** [platformio/platformio-home#327]
> Could not load PIO Account information
> PIO Core Call Error: "the JSON object must be str, not 'bytes'"

Happens when I click on PIO Accounts in the GUI and when I try to do a remote firmware update.

> Uploading firmware remotely
> the JSON object must be str, not 'bytes'
> The terminal process terminated with exit code: 1

VSCode 1.41.1 
Home 3.1.0-rc.1 
Core 4.1.0
Python 3.5.3
OS Debian 9.9 stretch

Get the same error with pio home

> Error: {'message': 'PIO Core Call Error', 'code': 4003, 'data': "the JSON object must be str, not 'bytes'"}

I can log in through CLI.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/issues/3396
