### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mrRobot62** [platformio/platformio-home#340]
PIO Core Call Error: "Library Storage: /Users/bernhardklein/.platformio/lib\nUpdating EspSoftwareSerial               @ 6.6.1          [6.7.1]\nUninstalling EspSoftwareSerial @ 6.6.1: \t[OK]\nLooking for EspSoftwareSerial library in registry\nFound: https://platformio.org/lib/show/168/EspSoftwareSerial\n\n\nError: Traceback (most recent call last):\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py\", line 253, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 816, in update\n    self.install(name, latest, after_update=True)\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py\", line 301, in install\n    force=force,\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 662, in install\n    with LockFile(self.package_dir):\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/lockfile.py\", line 103, in __enter__\n    self.acquire()\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/lockfile.py\", line 87, in acquire\n    return self._lock()\n  File \"/Users/bernhardklein/.platformio/penv/lib/python2.7/site-packages/platformio/lockfile.py\", line 62, in _lock\n    self._fp = open(self._lock_path, \"w\")\nIOError: [Errno 2] No such file or directory: '/Users/bernhardklein/.platformio/lib.lock'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Could you reproduce this issue again?
