### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by JhonatanAlexander** [platformio/platformio-home#3439]
PIO Core Call Error: "Library Storage: C:\\ESP2_TEST\\basic_tes\\.pio\\libdeps\\esp32doit-devkit-v1\r\nLibrary Manager: Installing pingouin000@hotmail.com/EspMQTTClient @ ^1.13.3\r\n\n\nError: VCS: Unknown repository type pingouin000@hotmail.com/EspMQTTClient"

**Comment by npotts** [comment]
A workaround is to edit your `platform.io`:

Replace 
> pingouin000@hotmail.com/EspMQTTClient@^1.13.3
with
> plapointe6/EspMQTTClient@^1.13.3

plapointe6 is his Github handle, and it looks like PIO is digging out an email.
