### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by sigitxluen** [platformio/platformio-home#3606]
PIO Core Call Error: "The current working directory C:\\Users\\sigit.prasetyo\\OneDrive - Elnusa Tbk\\ALL\\Documents\\PlatformIO\\Projects\\zephyr-test-1 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\sigit.prasetyo\\OneDrive - Elnusa Tbk\\ALL\\Documents\\PlatformIO\\Projects\\zephyr-test-1\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing nucleo_l073rz (platform: ststm32; board: nucleo_l073rz; framework: zephyr)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/nucleo_l073rz.html\r\nPLATFORM: ST STM32 (15.1.0) > ST Nucleo L073RZ\r\nHARDWARE: STM32L073RZ 32MHz, 20KB RAM, 192KB Flash\r\nDEBUG: Current (stlink) On-board (stlink) External (blackmagic, cmsis-dap, jlink)\r\nPACKAGES: \r\n - framework-zephyr 2.20700.211118 (2.7.0) \r\n - tool-cmake 3.21.3 \r\n - tool-dtc 1.4.7 \r\n - tool-ninja 1.9.0 \r\n - toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)\r\nReading CMake configuration...\r\n-- Application: C:/Users/sigit.prasetyo/OneDrive - Elnusa Tbk/ALL/Documents/PlatformIO/Projects/zephyr-test-1/zephyr\r\n-- Zephyr version: 2.7.0 (C:/Users/sigit.prasetyo/.platformio/packages/framework-zephyr)\r\n-- Found Python3: C:/Users/sigit.prasetyo/.platformio/penv/Scripts/python.exe (found suitable exact version \"3.9.2\") found components: Interpreter \r\n-- Board: nucleo_l073rz\r\n-- Cache files will be written to: C:/Users/sigit.prasetyo/.platformio/packages/framework-zephyr/.cache\r\n-- Found dtc: C:/Users/sigit.prasetyo/.platformio/packages/tool-dtc/dtc.exe (found suitable version \"1.4.7\", minimum required is \"1.4.6\")\r\n-- Found toolchain: gnuarmemb (C:/Users/sigit.prasetyo/.platformio/packages/toolchain-gccarmnoneeabi@1.80201.190214)\r\n-- Found BOARD.dts: C:/Users/sigit.prasetyo/.platformio/packages/framework-zephyr/boards/arm/nucleo_l073rz/nucleo_l073rz.dts\r\n-- Configuring incomplete, errors occurred!\r\n\r\nIn file included from <command-line>:\r\nC:/Users/sigit.prasetyo/.platformio/packages/framework-zephyr/boards/arm/nucleo_l073rz/nucleo_l073rz.dts:9:10: fatal error: st/l0/stm32l073r(b-z)tx-pinctrl.dtsi: No such file or directory\r\n #include <st/l0/stm32l073r(b-z)tx-pinctrl.dtsi>\r\n          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\ncompilation terminated.\r\n\r\nCMake Error at C:/Users/sigit.prasetyo/.platformio/packages/framework-zephyr/cmake/dts.cmake:167 (message):\r\n  command failed with return code: 1\r\nCall Stack (most recent call first):\r\n  C:/Users/sigit.prasetyo/.platformio/packages/framework-zephyr/cmake/app/boilerplate.cmake:541 (include)\r\n  CMakeLists.txt:2 (include)\r\n\r\n\r\n========================== [FAILED] Took 4.14 seconds =========================="

**Comment by OptifySudarshanPatil** [comment]
Hi @sigitxluen ,
How did you resolve this issue?
