### ISSUE TITLE
PIO Core Call Error: "the JSON object must be str, not 'bytes'"

### ISSUE THREAD

**Issue by VishalDhayalan** [platformio/platformio-home#363]
PIO Core Call Error: "the JSON object must be str, not 'bytes'"

When trying to login to PIO account browser URL (PIO running on Raspberry Pi 3B+)

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/issues/3396
