### ISSUE TITLE
PIO Core Call Error: "'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by ejngnng** [platformio/platformio-home#365]
PIO Core Call Error: "'utf-8' codec can't decode byte 0xb3 in position 789: invalid start byte"

Python3 version： 3.8.1

**Comment by ivankravets** [comment]
What is your OS? Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
