### ISSUE TITLE
'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by weiyingqiang** [platformio/platformio-home#369]
'ascii' codec can't decode byte 0xe7 in position 14: ordinal not in range(128)

**Comment by meditant** [comment]
Hello,

I have the same 'ascii' codec can't decode

Best,

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```
