### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by nazeem2001** [platformio/platformio-home#3799]
PIO Core Call Error: "The current working directory C:\\Users\\uname\\Documents\\PlatformIO\\Projects\\glove will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\uname\\Documents\\PlatformIO\\Projects\\glove\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError:"

**Comment by buddikatdk** [comment]
unsubscribe
