### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Moda-cmd** [platformio/platformio-home#388]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\karol\\\\OneDrive\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/408
