### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by LongYuMax** [platformio/platformio-home#390]
PIO Core Call Error: "The current working directory /Users/aaron/Desktop/CraterKIMD/CraterKIMD will be used for the project.\n\nThe next files/directories have been created in /Users/aaron/Desktop/CraterKIMD/CraterKIMD\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing genericSTM32F103VE (platform: ststm32; board: genericSTM32F103VE; framework: libopencm3)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103VE.html\nPLATFORM: ST STM32 5.4.1 > STM32F103VE (64k RAM. 512k Flash)\nHARDWARE: STM32F103VET6 72MHz, 64KB RAM, 512KB Flash\nDEBUG: Current (blackmagic) External (blackmagic, jlink, stlink)\nPACKAGES: toolchain-gccarmnoneeabi 1.70201.0 (7.2.1), framework-libopencm3 1.1.0\nFileNotFoundError: [Errno 2] No such file or directory: '/Users/aaron/.platformio/packages/framework-libopencm3/lib/Makefile':\n  File \"/Users/aaron/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py\", line 151:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 605:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 286:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/Users/aaron/.platformio/platforms/ststm32/builder/main.py\", line 90:\n    target_elf = env.BuildProgram()\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/aaron/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py\", line 115:\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/aaron/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py\", line 319:\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 668:\n    return method(*args, **kw)\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 605:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/Users/aaron/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 286:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/Users/aaron/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 181:\n    get_source_files(root_dir)\n  File \"/Users/aaron/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 100:\n    mkdata = parse_makefile_data(join(src_dir, \"Makefile\"))\n  File \"/Users/aaron/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 77:\n    with open(makefile) as f:\n========================== [FAILED] Took 0.81 seconds =========================="

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-ststm32/issues/232

Please update installed dev-platforms via `pio update`.
