### ISSUE TITLE
PIO Core Call Error: "[Errno 32] Broken pipe"

### ISSUE THREAD

**Issue by jsiqueir-sinch** [platformio/platformio-home#40]
PIO Core Call Error: "[Errno 32] Broken pipe"

**Comment by ivankravets** [comment]
Could you reproduce this issue after VSCode restart?

**Comment by jsiqueir-sinch** [comment]
No, happened twice only

**Comment by ivankravets** [comment]
Please reopen this issue if you can reproduce it. Happy coding with PlatformIO!
