### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by aa1ww-coop** [platformio/platformio-home#400]
PIO Core Call Error: "PlatformManager: Installing platform-gd32v\ngd32v @ 2d0265f has been successfully installed!\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by aa1ww-coop** [comment]
I was installing gd32v platform under PlatformIO on VSCode on a MacBook Air running Catalina using the suggested github client 2.23.~~~~~.

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment. Anyway, you can submit a feature request here https://github.com/sipeed/platform-gd32v/issues
