### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by spad** [platformio/platformio-home#401]
PIO Core Call Error: "The current working directory /Users/..../mesh_test will be used for the project.\n\nThe next files/directories have been created in /Users/..../mesh_test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing holyiot_yj16019 (platform: nordicnrf52; board: holyiot_yj16019; framework: zephyr)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/holyiot_yj16019.html\nPLATFORM: Nordic nRF52 4.0.0 > Holyiot YJ-16019\nHARDWARE: NRF52832 64MHz, 64KB RAM, 512KB Flash\nDEBUG: Current (blackmagic) External (blackmagic, cmsis-dap, jlink, stlink)\nPACKAGES: \n - framework-zephyr 1.20100.200106 (2.1.0) \n - framework-zephyr-civetweb 0.20100.190807 (2.1.0) \n - framework-zephyr-fatfs 0.20100.190522 (2.1.0) \n - framework-zephyr-hal-nordic 0.20100.191028 (2.1.0) \n - framework-zephyr-libmetal 0.20100.190530 (2.1.0) \n - framework-zephyr-littlefs 0.20100.190811 (2.1.0) \n - framework-zephyr-lvgl 0.20100.190812 (2.1.0) \n - framework-zephyr-mbedtls 0.20100.191006 (2.1.0) \n - framework-zephyr-mcumgr 0.20100.190528 (2.1.0) \n - framework-zephyr-mipi-sys-t 0.20100.191024 (2.1.0) \n - framework-zephyr-nffs 0.20100.190523 (2.1.0) \n - framework-zephyr-open-amp 0.20100.190612 (2.1.0) \n - framework-zephyr-openthread 0.20100.191024 (2.1.0) \n - framework-zephyr-segger 0.20100.190421 (2.1.0) \n - framework-zephyr-tinycbor 0.20100.191016 (2.1.0) \n - tool-cmake 3.15.5 \n - tool-dtc 1.4.7 \n - tool-gperf 3.1.0 \n - tool-ninja 1.9.0 \n - tool-sreccat 1.164.0 (1.64) \n - toolchain-gccarmnoneeabi 1.80201.181220 (8.2.1)\nPython 3.4 or greater required, but you have Python 2.7.16\n========================== [FAILED] Took 1.00 seconds =========================="

**Comment by valeros** [comment]
Looks like your PlatformIO virtual environment was created for Python 2.7, the Zephyr framework only supports Python 3.
- Close the IDE
- Make sure Python 3.x is the main Python installation in your system.
- Delete `.penv` folder in PlatformIO home directory ` /Users/..../.platformio/.penv`
- Open the IDE and wait until a new installation is completed
