### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/platformio/platformio-libmirror/master/configs/mbed/MatrixMath_Yo_Robot.json

### ISSUE THREAD

**Issue by ZhangYanglyu** [platformio/platformio-home#402]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /platformio/platformio-libmirror/master/configs/mbed/MatrixMath_Yo_Robot.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001BB77DA1748>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by ivankravets** [comment]
Please restart VSCode. It should work now. Sorry for the issue.

**Comment by ZhangYanglyu** [comment]
Thanks, the problem was resolved
