### ISSUE TITLE
FileNotFoundError: Could not initialize project

### ISSUE THREAD

**Issue by huynhmaook** [platformio/platformio-home#408]
# Temporary solution

1. Please check that antivirus tools do not block PlatformIO.
2. Try to restart PIO Home/VSCode.

------

Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\Administrator\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
