### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by ghagasp** [platformio/platformio-home#41]
PIO Core Call Error: "The current working directory C:\\Users\\EMB1B\\Documents\\PlatformIO\\Projects\\123132 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\EMB1B\\Documents\\PlatformIO\\Projects\\123132\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)\r\n--------------------------------------------------------------------------------\r\ntoolchain-gccarmnoneeabi @ 1.70201.0 has been successfully installed!\r\nThe platform 'ststm32' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment."

**Comment by ivankravets** [comment]
> platform: atmelavr; board: megaatmega2560
> The platform 'ststm32

How to reproduce this issue? How did you select 2 boards?

**Comment by ivankravets** [comment]
Please reopen if you still need help
