### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by robstermn** [platformio/platformio-home#414]
PIO Core Call Error: "Library Storage: C:\\Users\\veitchb\\.platformio\\lib\r\nLibraryManager: Installing url\r\nDownloading...\r\n\n\nError: Can not unpack file 'C:\\Users\\veitchb\\.platformio\\lib\\_tmp_installing-lvglc43s-package\\Servo'"

**Comment by sysdl132** [comment]
I have the same PROBLEM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I cannot download because '404 not found'?????
There also has another:PR_CONNECT_RESET_ERROR.
What problem?????????

**Comment by sysdl132** [comment]
And it shows installing... for a long time.

![image](https://user-images.githubusercontent.com/54708046/74807152-b3dfbf00-5322-11ea-9514-61106c9eadd5.png)

**Comment by sysdl132** [comment]
(Anyone can fix it?I need to compile a sketch but the libraries is required.............)
