### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by RaZiegler** [platformio/platformio-home#4188]
PIO Core Call Error: "The current working directory D:\\Dokumente\\PlatformIO\\Projects\\Test will be used for the project.\r\n\r\nThe next files/directories have been created in D:\\Dokumente\\PlatformIO\\Projects\\Test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nC:\\Users\\TanjaRalf\\.platformio\\python3\\python.exe: can't open file 'C:\\Users\\TanjaRalf\\.platformio\\packages\\xtool-scons_xxx\\scons.py': [Errno 2] No such file or directory\r\n========================== [FAILED] Took 0.09 seconds =========================="

**Comment by jomjol** [comment]
I have the same problem. It looks like the esp32cam package is broken
