### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by redlooney** [platformio/platformio-home#42]
Server error: {"args":["module 'platformio.managers.platform.platform-espressif8266' has no attribute 'Platformespressif8266Platform'"],"message":"module 'platformio.managers.platform.platform-espressif8266' has no attribute 'Platformespressif8266Platform'","type":"AttributeError"}

**Comment by ivankravets** [comment]
Please remove `~/.platformio/platforms` folder and reopen PIO Home.
