### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by mabruq** [platformio/platformio-home#4217]
PIO Core Call Error: "Library Storage: /home/m3/Documents/PlatformIO/Projects/sdcard_test/.pio/libdeps/esp32dev\nLibrary Manager: Installing platformio@benoitblanchon.fr/ArduinoJson @ ^6.19.4\n\n\nError: VCS: Unknown repository type platformio@benoitblanchon.fr/ArduinoJson"

**Comment by bauerbyter** [comment]
Same Problem!

**Comment by friedrichengel** [comment]
same here
