### ISSUE TITLE
Libraries: Could not install library TaskScheduler by Anatoli Arkhipenko ver 3.1.3

### ISSUE THREAD

**Issue by aslansari** [platformio/platformio-home#428]
PIO Core Call Error: "'utf-8' codec can't decode byte 0xf0 in position 771: invalid continuation byte"

**Comment by ivankravets** [comment]
What is your OS?

**Comment by aslansari** [comment]
Windows 10, version 3.1.2 works fine btw.

**Comment by ivankravets** [comment]
How to reproduce this? I use Win10 in VM:
![Screen Shot 2020-02-29 at 22 25 05](https://user-images.githubusercontent.com/1760209/75614526-588fa700-5b42-11ea-94a7-8688252bcea2.png)

Do you install library into the global storage to into the project?

**Comment by aslansari** [comment]
I installed the library into the global storage. However,
now I just retried and 3.1.3 has successfully installed, i'm not sure what caused the issue. I had clicked the button in the notification to report the issue at that time.

**Comment by ivankravets** [comment]
Please reopen this issue if you will reproduce it. Thanks!
