### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by n9wxu** [platformio/platformio-home#429]
PIO Core Call Error: "The current working directory /Users/joejulicher/Documents/PlatformIO/Projects/sam_test will be used for the project.\n\nThe next files/directories have been created in /Users/joejulicher/Documents/PlatformIO/Projects/sam_test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'sparkfun_samd21_proRF'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/155
