### ISSUE TITLE
Removing dependencies stopped working after 6.0.1 release

### ISSUE THREAD

**Issue by ArchangelDesign** [platformio/platformio-home#4326]
I'm unable to remove dependency anymore.
Going to `Libraries -> Installed` and clicking `Uninstall` removes the directory from `libdeps` which quickly returns after a few seconds.
Creating another `env` results in the same thing, although unwanted dependency seems to come back with a slight delay.

The dependency in question is `SD` which was installed at some point and then removed. After the last update (6.0.1) I can not remove that library, even if I manually delete the directory and/or integrity file.

Unfortunately, I don't know which exact version I had before the update.
I'm using Windows and VSCode 1.67.2 although I don't think this is a plugin issue.

**Comment by ivankravets** [comment]
Please use temporary new unified package management CLI ( https://docs.platformio.org/en/latest/core/migration.html#package-management )

Here is a guide how to open PlatformIO Core CLI in VSCode https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli
