### ISSUE TITLE
Error occurred while requesting content from http://dl.platformio.org/libraries/examples/0/19/DHT_Unified_Sensor.ino

### ISSUE THREAD

**Issue by djlazy** [platformio/platformio-home#435]
HTTPConnectionPool(host='dl.platformio.org', port=80): Max retries exceeded with url: /libraries/examples/0/19/DHT_Unified_Sensor.ino (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D915A02F88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by ivankravets** [comment]
Please restart VSCode. It should work now. Sorry for the issue.
