### ISSUE TITLE
library manager install for Azure SDK for C adds backwards compatibility that causes errors

### ISSUE THREAD

**Issue by critchards** [platformio/platformio-home#4354]
When using the library manager to install Azure SDK for C, lib_deps gets `azure/Azure SDK for C@^1.0.0-beta.4` which throws an error on build of `Error: Could not find the package with 'azure/Azure SDK for C @ ^1.0.0-beta.4' requirements for your system 'windows_amd64'`

library manager should include specific version as `azure/Azure SDK for C@1.0.0-beta.4`

See [thread for discussion](https://community.platformio.org/t/azure-sdk-for-c-1-0-0-beta-4-cannot-find-package-for-your-system-windows-amd64/27990)

**Comment by ivankravets** [comment]
Thanks! I see, hope we will refactor PIO Home soon to the Core 6.0 and the new registry.
