### ISSUE TITLE
OS_MAKE_DIRS

### ISSUE THREAD

**Issue by alfarisw** [platformio/platformio-home#437]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\ABAC\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-home/issues/408
