### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by jkdk** [platformio/platformio-home#438]
PIO Core Call Error: "PlatformManager: Installing package_stm_index\r\n\n\nError: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json', 'C:\\\\Users\\\\jkej\\\\.platformio\\\\platforms\\\\_tmp_installing-u0sm_vez-package']"

**Comment by ivankravets** [comment]
You need to install `ststm32` dev-platform. See https://docs.platformio.org/en/latest/platforms/ststm32.html
