### ISSUE TITLE
Could not load recent projects　'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by miiketaro** [platformio/platformio-home#444]
Could not load recent projects 'ascii' codec can't decode byte 0xe3 in position 31: ordinal not in range(128)

**Comment by ivankravets** [comment]
What is your OS?

**Comment by miiketaro** [comment]
thank you.
Mac OS Mojave 10.14.6  VScode 1.42.1  PlatformIO Home3.1.0 Core4.2.1

**Comment by miiketaro** [comment]
<img src="http://get.secret.jp/pt/file/1583020955.jpg" border="0">
