### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by spad** [platformio/platformio-home#454]
PIO Core Call Error: "The current working directory F:\\nRF5_Projects\\nRF52_Zephyr will be used for the project.\n\r\nThe next files/directories have been created in F:\\nRF5_Projects\\nRF52_Zephyr\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing nrf52840_dk (platform: nordicnrf52; board: nrf52840_dk; framework: zephyr)\n-------------------------------------------------------------------------------\nPackageManager: Installing framework-zephyr-open-amp @ ~0.20100.190612\nframework-zephyr-open-amp @ 0.20100.190612 has been successfully installed!\nPackageManager: Installing framework-zephyr-hal-nordic @ ~0.20100.191028\nframework-zephyr-hal-nordic @ 0.20100.191028 has been successfully installed!\nPackageManager: Installing tool-dtc @ ~1.4.7\ntool-dtc @ 1.4.7 has been successfully installed!\nPackageManager: Installing framework-zephyr-civetweb @ ~0.20100.190807\nframework-zephyr-civetweb @ 0.20100.190807 has been successfully installed!\nPackageManager: Installing toolchain-gccarmnoneeabi @ ~1.80201.0\ntoolchain-gccarmnoneeabi @ 1.80201.190214 has been successfully installed!\nPackageManager: Installing framework-zephyr-mcumgr @ ~0.20100.190528\nframework-zephyr-mcumgr @ 0.20100.190528 has been successfully installed!\nPackageManager: Installing framework-zephyr-nffs @ ~0.20100.190523\nframework-zephyr-nffs @ 0.20100.190523 has been successfully installed!\nPackageManager: Installing framework-zephyr-mbedtls @ ~0.20100.191006\nframework-zephyr-mbedtls @ 0.20100.191006 has been successfully installed!\nPackageManager: Installing tool-cmake @ ~3.15.0\ntool-cmake @ 3.15.5 has been successfully installed!\nPackageManager: Installing framework-zephyr-openthread @ ~0.20100.191024\nframework-zephyr-openthread @ 0.20100.191024 has been successfully installed!\nPackageManager: Installing framework-zephyr-libmetal @ ~0.20100.190530\nframework-zephyr-libmetal @ 0.20100.190530 has been successfully installed!\nPackageManager: Installing framework-zephyr @ ~1.20100.0\nframework-zephyr @ 1.20100.200106 has been successfully installed!\nPackageManager: Installing framework-zephyr-fatfs @ ~0.20100.190522\nframework-zephyr-fatfs @ 0.20100.190522 has been successfully installed!\nPackageManager: Installing framework-zephyr-littlefs @ ~0.20100.190811\nframework-zephyr-littlefs @ 0.20100.190811 has been successfully installed!\nPackageManager: Installing framework-zephyr-lvgl @ ~0.20100.190812\nframework-zephyr-lvgl @ 0.20100.190812 has been successfully installed!\nPackageManager: Installing tool-ninja @ ^1.7.0\ntool-ninja @ 1.9.0 has been successfully installed!\nPackageManager: Installing framework-zephyr-segger @ ~0.20100.190421\nframework-zephyr-segger @ 0.20100.190421 has been successfully installed!\nPackageManager: Installing framework-zephyr-tinycbor @ ~0.20100.191016\nframework-zephyr-tinycbor @ 0.20100.191016 has been successfully installed!\nPackageManager: Installing framework-zephyr-mipi-sys-t @ ~0.20100.191024\nframework-zephyr-mipi-sys-t @ 0.20100.191024 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/nrf52840_dk.html\nPLATFORM: Nordic nRF52 4.0.0 > Nordic nRF52840-DK\nHARDWARE: NRF52840 64MHz, 256KB RAM, 1MB Flash\nDEBUG: Current (cmsis-dap) On-board (cmsis-dap, jlink) External (blackmagic, stlink)\nPACKAGES: \n - framework-zephyr 1.20100.200106 (2.1.0) \n - framework-zephyr-civetweb 0.20100.190807 (2.1.0) \n - framework-zephyr-fatfs 0.20100.190522 (2.1.0) \n - framework-zephyr-hal-nordic 0.20100.191028 (2.1.0) \n - framework-zephyr-libmetal 0.20100.190530 (2.1.0) \n - framework-zephyr-littlefs 0.20100.190811 (2.1.0) \n - framework-zephyr-lvgl 0.20100.190812 (2.1.0) \n - framework-zephyr-mbedtls 0.20100.191006 (2.1.0) \n - framework-zephyr-mcumgr 0.20100.190528 (2.1.0) \n - framework-zephyr-mipi-sys-t 0.20100.191024 (2.1.0) \n - framework-zephyr-nffs 0.20100.190523 (2.1.0) \n - framework-zephyr-open-amp 0.20100.190612 (2.1.0) \n - framework-zephyr-openthread 0.20100.191024 (2.1.0) \n - framework-zephyr-segger 0.20100.190421 (2.1.0) \n - framework-zephyr-tinycbor 0.20100.191016 (2.1.0) \n - tool-cmake 3.15.5 \n - tool-dtc 1.4.7 \n - tool-ninja 1.9.0 \n - tool-sreccat 1.164.0 (1.64) \n - toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)\nInstalling Zephyr's Python dependencies\nCollecting pyyaml\n  Downloading https://files.pythonhosted.org/packages/6d/1a/dbe0f53ee5830e1eee8aa2d09ab477feb9b5fa15186247989119a2050c0e/PyYAML-5.3-cp27-cp27m-win32.whl (194kB)\nCollecting pykwalify\n  Using cached https://files.pythonhosted.org/packages/36/9f/612de8ca540bd24d604f544248c4c46e9db76f6ea5eb75fb4244da6ebbf0/pykwalify-1.7.0-py2.py3-none-any.whl\nCollecting docopt>=0.6.2 (from pykwalify)\n  Using cached https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz\nCollecting python-dateutil>=2.4.2 (from pykwalify)\n  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl\nRequirement already satisfied: six>=1.5 in c:\\users\\saverio\\.platformio\\packages\\contrib-pysite (from python-dateutil>=2.4.2->pykwalify) (1.12.0)\nBuilding wheels for collected packages: docopt\n  Running setup.py bdist_wheel for docopt: started\n  Running setup.py bdist_wheel for docopt: finished with status 'done'\n  Stored in directory: C:\\Users\\saverio\\AppData\\Local\\pip\\Cache\\wheels\\9b\\04\\dd\\7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e\nSuccessfully built docopt\nInstalling collected packages: pyyaml, docopt, python-dateutil, pykwalify\nSuccessfully installed docopt-0.6.2 pykwalify-1.7.0 python-dateutil-2.8.1 pyyaml-5.3\nYou are using pip version 18.1, however version 20.0.2 is available.\nYou should consider upgrading via the 'python -m pip install --upgrade pip' command.\nPython 3.4 or greater required, but you have Python 2.7.14\n======================== [FAILED] Took 118.06 seconds ========================"

**Comment by valeros** [comment]
Looks like your PlatformIO virtual environment was created for Python 2.7, the Zephyr framework only supports Python 3.
- Close the IDE
- Make sure Python 3.x is the main Python installation in your system.
- Delete folder `c:\users\saverio\.platformio\.penv`
- Open the IDE and wait until a new installation is completed
