### ISSUE TITLE
Could not load PIO Account information

### ISSUE THREAD

**Issue by Coconop** [platformio/platformio-home#455]
**VSCode** version 1.42.1
**PlateformIO** version 4.2.1

**Error in VSCode extenson:**
PIO Core Call Error: "the JSON object must be str, not 'bytes'"

**Context:**
I have created my account and am able to login in CLI via PlatformIO Core.
I got the above error when I enter my credentials through the VSCode extension

**Comment by ivankravets** [comment]
This issue was fixed in the latest PIO Core-dev. We will release it soon. You can switch to the dev version via running in PlatformIO IDE `pio upgrade --dev`.
