### ISSUE TITLE
Could not list directory/home/user

### ISSUE THREAD

**Issue by Batucador** [platformio/platformio-home#463]
'utf-8' codec can't encode character '\udcf1' in position 1421: surrogates not allowed

**Comment by valeros** [comment]
Please provide an output from the system terminal:
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
To me it looks like is caused by Python 2.x. Could you please try to install Python 3.7
https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
