### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by ChenBaoW** [platformio/platformio-home#4751]
PIO Core Call Error: "The current working directory F:\\Demo\\esp32code\\esp32try will be used for the project.\r\n\r\nThe next files/directories have been created in F:\\Demo\\esp32code\\esp32try\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nResolving esp32dev dependencies...\r\n\n\nError:"

**Comment by Sarah-C** [comment]
That's like mine!

Love the error. Prior to this week 2 computers installed and uploaded stuff OK. A laptop I installed VSC and PIO on today failed just like this!
