### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by simon-rob** [platformio/platformio-home#477]
PIO Core Call Error: "The current working directory /home/simon/Documents/PlatformIO/Projects/200313-170804-INS will be used for the project.\n\nThe next files/directories have been created in /home/simon/Documents/PlatformIO/Projects/200313-170804-INS\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'openIMU300'"

**Comment by ivankravets** [comment]
Please update all dev-platforms and restart VSCode.
