### ISSUE TITLE
Could not load platform updates

### ISSUE THREAD

**Issue by DavidFW1960** [platformio/platformio-home#479]
PIO Core Call Error: "Error: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'returncode': 128, 'err': u\"remote: Repository not found.\\nfatal: repository 'https://github.com/Jason2866/Arduino.git/' not found\", 'out': u''})"

**Comment by clodoaldosouza** [comment]
Same problem: 
"PIO Core Call Error: "Error: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'out': '', 'err': \"remote: Repository not found.\\nfatal: repository 'https://github.com/Jason2866/Arduino.git/' not found\\n\", 'returncode': 128})""

**Comment by timbru31** [comment]
The problem is caused by having the entry to non-existing repo (i.e., https://github.com/Jason2866/Arduino.git). You can solve it by removing the folder which contains the repo above in your `~/.platformio` folder.
