### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by vuknikolic** [platformio/platformio-home#480]
PIO Core Call Error: "The current working directory D:\\Users\\Vuk\\Documents\\PlatformIO\\Projects\\testSTM32f401BlackPill\\Test2STM32F401BlackPill will be used for the project.\n\r\nThe next files/directories have been created in D:\\Users\\Vuk\\Documents\\PlatformIO\\Projects\\testSTM32f401BlackPill\\Test2STM32F401BlackPill\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'blackpill_f401cc'"

**Comment by ivankravets** [comment]
Please update all dev-platforms and restart VSCode.
