### ISSUE TITLE
Error occurred while requesting content from https://bitbucket.org/fmalpartida/new-liquidcrystal/raw/integration/library.json

### ISSUE THREAD

**Issue by a-x-** [platformio/platformio-home#481]
HTTPSConnectionPool(host='bitbucket.org', port=443): Max retries exceeded with url: /fmalpartida/new-liquidcrystal/raw/integration/library.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

**Comment by ivankravets** [comment]
Resolved in the latest release.
