### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by Oldiwon** [platformio/platformio-home#497]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/garydean/.platformio/platforms/Arduino/platform.json'","type":"IOError"}

**See below for directory tree of above location**
![Screen Shot 2020-03-19 at 10 19 24](https://user-images.githubusercontent.com/3463152/77057001-31065e80-69cb-11ea-819b-7c743a340166.png)

**Comment by ivankravets** [comment]
Compatible platforms https://platformio.org/platforms
