### ISSUE TITLE
Could not initialize project GAP8 PULP OS Windows 11

### ISSUE THREAD

**Issue by Neathle** [platformio/platformio-home#5073]
PIO Core Call Error: "The current working directory D:\\gap8\\test will be used for the project.\r\n\r\nThe next files/directories have been created in D:\\gap8\\test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nResolving gapuino dependencies...\r\nPlatform Manager: Installing riscv_gap\r\nDownloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%\r\nUnpacking\r\nPlatform Manager: riscv_gap@1.1.0 has been installed!\r\nTool Manager: Installing platformio/framework-gap_sdk @ ~2.0.0\r\nDownloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%\r\nUnpacking\r\nTool Manager: framework-gap_sdk@2.0.0 has been installed!\r\nTool Manager: Installing platformio/toolchain-riscv-pulp @ ~1.70101.0\r\nDownloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%\r\nUnpacking\r\nTool Manager: toolchain-riscv-pulp@1.70101.201217 has been installed!\r\nTool Manager: Installing platformio/tool-pulp_tools @ ~0.1.0\r\nDownloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%\r\nUnpacking\r\nTool Manager: tool-pulp_tools@0.1.181108 has been installed!\r\nUpdating metadata for the vscode IDE...\r\n\n\nError: Processing gapuino (platform: riscv_gap; board: gapuino; framework: pulp-os)\r\n--------------------------------------------------------------------------------\r\nTool Manager: Installing platformio/tool-scons @ ~4.40400.0\r\nDownloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%\r\nUnpacking\r\nTool Manager: tool-scons@4.40400.0 has been installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nModuleNotFoundError: No module named 'platformio.builder.tools.platformio':\r\n  File \"C:\\Users\\gerve\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 188:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\gerve\\.platformio\\packages\\tool-scons\\scons-local-4.4.0\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\gerve\\.platformio\\packages\\tool-scons\\scons-local-4.4.0\\SCons\\Script\\SConscript.py\", line 285:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\gerve\\.platformio\\platforms\\riscv_gap\\builder\\main.py\", line 74:\r\n    SConscript(\"autotiler.py\", exports={\"env\": env})\r\n  File \"C:\\Users\\gerve\\.platformio\\packages\\tool-scons\\scons-local-4.4.0\\SCons\\Script\\SConscript.py\", line 660:\r\n    return method(*args, **kw)\r\n  File \"C:\\Users\\gerve\\.platformio\\packages\\tool-scons\\scons-local-4.4.0\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\gerve\\.platformio\\packages\\tool-scons\\scons-local-4.4.0\\SCons\\Script\\SConscript.py\", line 285:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\gerve\\.platformio\\platforms\\riscv_gap\\builder\\autotiler.py\", line 23:\r\n    from platformio.builder.tools.platformio import SRC_FILTER_DEFAULT\r\n========================== [FAILED] Took 4.32 seconds =========================="

**Comment by Marcela20245** [comment]
No me sirve
