### ISSUE TITLE
AttributeError: 'module' object has no attribute '_strptime_time'

### ISSUE THREAD

**Issue by wfc1973** [platformio/platformio-home#51]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 244, in lib_update\n    latest = lm.outdated(pkg_dir, requirements)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 638, in outdated\n    silent=True,\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 130, in get_latest_repo_version\n    requirements,\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 117, in max_satisfying_repo_version\n    if not item or _cmp_dates(item[\"released\"], v[\"released\"]) == -1:\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 89, in _cmp_dates\n    date1 = util.parse_date(datestr1)\n  File \"c:\\users\\willi\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 419, in parse_date\n    return time.strptime(datestr, \"%Y-%m-%dT%H:%M:%SZ\")\nAttributeError: 'module' object has no attribute '_strptime_time'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
