### ISSUE TITLE
Could not load mDNS services

### ISSUE THREAD

**Issue by cbutlerjr** [platformio/platformio-home#5168]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/platformio/util.py\", line 196, in get_mdns_services\n    import zeroconf\nModuleNotFoundError: No module named 'zeroconf'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1128, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1053, in main\n    rv = self.invoke(ctx)\n  File \"/usr/lib/python3/dist-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1659, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1659, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1395, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 754, in invoke\n    return __callback(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/platformio/commands/device/command.py\", line 50, in device_list\n    data[\"mdns\"] = util.get_mdns_services()\n  File \"/usr/lib/python3/dist-packages/platformio/util.py\", line 201, in get_mdns_services\n    contrib_pysite_dir = get_core_package_dir(\"contrib-pysite\")\n  File \"/usr/lib/python3/dist-packages/platformio/managers/core.py\", line 86, in get_core_package_dir\n    pkg_dir = pm.get_package_dir(name, requirements)\n  File \"/usr/lib/python3/dist-packages/platformio/managers/package.py\", line 415, in get_package_dir\n    manifest = self.get_package(name, requirements, url)\n  File \"/usr/lib/python3/dist-packages/platformio/managers/package.py\", line 384, in get_package\n    for manifest in self.get_installed():\n  File \"/usr/lib/python3/dist-packages/platformio/managers/package.py\", line 374, in get_installed\n    manifest = self.load_manifest(pkg_dir)\n  File \"/usr/lib/python3/dist-packages/platformio/managers/package.py\", line 347, in load_manifest\n    manifest = ManifestParserFactory.new_from_file(manifest_path).as_dict()\n  File \"/usr/lib/python3/dist-packages/platformio/package/manifest/parser.py\", line 73, in new_from_file\n    return ManifestParserFactory.new(\n  File \"/usr/lib/python3/dist-packages/platformio/package/manifest/parser.py\", line 123, in new\n    return cls(contents, remote_url, package_dir)\n  File \"/usr/lib/python3/dist-packages/platformio/package/manifest/parser.py\", line 136, in __init__\n    self._data = self.normalize_repository(self._data)\n  File \"/usr/lib/python3/dist-packages/platformio/package/manifest/parser.py\", line 174, in normalize_repository\n    url = (data.get(\"repository\") or {}).get(\"url\")\nAttributeError: 'str' object has no attribute 'get'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by DrJaymz** [comment]
here's some recent activity - still an issue.  Works ok on newer installations but any installations resurrected from a year or so and updated break.  So presumably something squiffy in the dependencies when it updates.
