### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by Marcos-A-ltaph** [platformio/platformio-home#52]
PIO Core Call Error: "Library Storage: /home/ltaph/.platformio/lib\nUpdating ESP8266 and ESP32 Oled Driver for SSD1306 display @ 4.0.0          [4.1.0]\nUninstalling ESP8266 and ESP32 Oled Driver for SSD1306 display @ 4.0.0: \t[OK]\nLooking for ESP8266 and ESP32 Oled Driver for SSD1306 display library in registry\n\n\nError: Library `{'requirements': u'4.1.0', 'name': 'ESP8266 and ESP32 Oled Driver for SSD1306 display'}` has not been found in PlatformIO Registry.\nYou can ignore this message, if `{'requirements': u'4.1.0', 'name': 'ESP8266 and ESP32 Oled Driver for SSD1306 display'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
Unknown library https://platformio.org/lib/search?query=ESP8266%2520and%2520ESP32%2520Oled%2520Driver%2520for%2520SSD1306%2520display&page=1
