### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by nikhil-alakanty** [platformio/platformio-home#529]
PIO Core Call Error: "The current working directory C:\\Users\\akhil\\OneDrive\\Documents\\PlatformIO\\Projects\\sense esp thing will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\akhil\\OneDrive\\Documents\\PlatformIO\\Projects\\sense esp thing\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing espressif32\nespressif32 @ 1.12.0 has been successfully installed!\nPackageManager: Installing toolchain-xtensa32 @ ~2.50200.0\r\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\r\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\nThe platform 'espressif32' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\n-------------------------------------------------------------------------------\nPackageManager: Installing tool-mconf @ ~1.4060000.0\ntool-mconf @ 1.4060000.20190628 has been successfully installed!\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\nPackageManager: Installing tool-ninja @ ^1.7.0\ntool-ninja @ 1.9.0 has been successfully installed!\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\nPackageManager: Installing tool-cmake @ ~3.16.0\ntool-cmake @ 3.16.4 has been successfully installed!\nPackageManager: Installing framework-espidf @ ~3.40000.0\nframework-espidf @ 3.40000.200303 has been successfully installed!\nPackageManager: Installing tool-idf @ ~1.0.1\ntool-idf @ 1.0.1 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~2.20501.7\ntool-scons @ 2.20501.191222 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\nPLATFORM: Espressif 32 1.12.0 > Espressif ESP32 Dev Module\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40000.200303 (4.0.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-idf 1.0.1 \n - tool-mconf 1.4060000.20190628 (406.0.0) \n - tool-ninja 1.9.0 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nDEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support\nRequirement already satisfied: cryptography>=2.1.4 in c:\\users\\akhil\\.platformio\\packages\\contrib-pysite (2.8)\nCollecting future>=0.15.2\n  Downloading future-0.18.2.tar.gz (829 kB)\nCollecting pyparsing<2.4.0,>=2.0.3\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\nRequirement already satisfied: enum34; python_version < \"3\" in c:\\users\\akhil\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.1.6)\nRequirement already satisfied: ipaddress; python_version < \"3\" in c:\\users\\akhil\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.0.22)\nRequirement already satisfied: six>=1.4.1 in c:\\users\\akhil\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.12.0)\nRequirement already satisfied: cffi!=1.11.3,>=1.8 in c:\\users\\akhil\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.13.0)\nRequirement already satisfied: pycparser in c:\\users\\akhil\\.platformio\\packages\\contrib-pysite (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4) (2.19)\nBuilding wheels for collected packages: future\n  Building wheel for future (setup.py): started\n  Building wheel for future (setup.py): finished with status 'done'\n  Created wheel for future: filename=future-0.18.2-py2-none-any.whl size=502601 sha256=f120e9731c3d87332b092685c0a9c557387ec05f82304bda75ec47f1eb1c33b1\n  Stored in directory: c:\\users\\akhil\\appdata\\local\\pip\\cache\\wheels\\5f\\11\\0c\\aad680baf5ef4fbcbab992c9f03e1130357e0c173a4fdabfff\nSuccessfully built future\nInstalling collected packages: future, pyparsing\nSuccessfully installed future-0.18.2 pyparsing-2.3.1\nError: Detected a whitespace character in project paths.\n======================== [FAILED] Took 225.32 seconds ========================"

**Comment by valeros** [comment]
Hi @nikhil-alakanty ! Starting with ESP-IDF v4.0 white space characters are not allowed in project path and you you have one in yout project name `sense esp thing`.
