### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by brunohorta82** [platformio/platformio-home#53]
PIO Core Call Error: "Library Storage: /Users/brunohorta/COMMUNITY/BH-Easy-Iot/EasyIot7/.pio/libdeps/esp12e\nUpdating ESP Async WebServer             @ 2f37037        [f13685e]\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3033
