### ISSUE TITLE
Could not list directory/home/karls

### ISSUE THREAD

**Issue by karls0** [platformio/platformio-home#533]
'utf-8' codec can't encode character '\udcc5' in position 3087: surrogates not allowed
Folder /home/karls/Documents and its subdirectories can be opened. My PlatformIO-Projects are in subfolders of  /home/karls/Documents/PlatformIO

**Comment by valeros** [comment]
Please provide an output from the system terminal:
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```
To me it looks like is caused by Python 2.x. Could you please try to install Python 3.7
https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
