### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Naildaroueche** [platformio/platformio-home#537]
PIO Core Call Error: "The current working directory C:\\Users\\Nail\\Documents\\PlatformIO\\Projects\\ESP32 WebServer will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Nail\\Documents\\PlatformIO\\Projects\\ESP32 WebServer\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\r\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\r\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\r\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\r\nPackageManager: Installing framework-espidf @ ~3.40000.0\r\nframework-espidf @ 3.40000.200303 has been successfully installed!\r\nPackageManager: Installing tool-cmake @ ~3.16.0\r\ntool-cmake @ 3.16.4 has been successfully installed!\r\nPackageManager: Installing tool-ninja @ ^1.7.0\r\ntool-ninja @ 1.9.0 has been successfully installed!\r\nPackageManager: Installing tool-mconf @ ~1.4060000.0\r\ntool-mconf @ 1.4060000.20190628 has been successfully installed!\r\nPackageManager: Installing tool-idf @ ~1.0.1\r\ntool-idf @ 1.0.1 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\r\nPLATFORM: Espressif 32 1.12.0 > Espressif ESP32 Dev Module\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40000.200303 (4.0.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200226 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\nRequirement already satisfied: cryptography>=2.1.4 in c:\\users\\nail\\.platformio\\packages\\contrib-pysite (2.8)\r\nCollecting future>=0.15.2\r\n  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)\r\nCollecting pyparsing<2.4.0,>=2.0.3\r\n  Downloading https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl (61kB)\r\nRequirement already satisfied: cffi!=1.11.3,>=1.8 in c:\\users\\nail\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.13.0)\r\nRequirement already satisfied: six>=1.4.1 in c:\\users\\nail\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.12.0)\r\nRequirement already satisfied: pycparser in c:\\users\\nail\\.platformio\\packages\\contrib-pysite (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4) (2.19)\r\nInstalling collected packages: future, pyparsing\r\n  Running setup.py install for future: started\r\n    Running setup.py install for future: finished with status 'done'\r\nSuccessfully installed future-0.18.2 pyparsing-2.3.1\r\nWARNING: You are using pip version 19.2.3, however version 20.0.2 is available.\r\nYou should consider upgrading via the 'python -m pip install --upgrade pip' command.\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 328.42 seconds ========================="

**Comment by valeros** [comment]
You have white space characters in project name `ESP32 WebServer`, starting with `ESP-IDF v4.0` they  are not allowed.  More info [here](https://docs.platformio.org/en/latest/frameworks/espidf.html#configuration).
