### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by lishuai199502** [platformio/platformio-home#540]
PIO Core Call Error: "'utf-8' codec can't decode byte 0xd3 in position 536: invalid continuation byte"

**Comment by valeros** [comment]
Please provide an output from the system terminal:
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
To me it looks like is caused by Python 2.x. Could you please try to install Python 3.7
https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
