### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by felix-cn** [platformio/platformio-home#541]
PIO Core Call Error: "toolchain-atmelavr @ 1.50400.190710 has been successfully installed!\r\nPackageManager: Installing framework-arduino-avr @ ~5.0.0\r\nframework-arduino-avr @ 5.0.0 has been successfully installed!\r\nCorePackageManager: Installing tool-scons @ ~3.30102.0\r\ntool-scons @ 3.30102.0 has been successfully installed!\r\n======================== [SUCCESS] Took 2519.80 seconds ========================"

**Comment by valeros** [comment]
What's the error message exactly?
