### ISSUE TITLE
Error: VCS: Could not process command ['git', 'clone

### ISSUE THREAD

**Issue by jeffinchiangmai** [platformio/platformio-home#56]
PIO Core Call Error: "Library Storage: C:\\Users\\jeffi\\.platformio\\lib\nLibraryManager: Installing FreeRTOS\n\n\nError: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/freertos/FreeRTOS.h', 'C:\\\\Users\\\\jeffi\\\\.platformio\\\\lib\\\\_tmp_installing-fjidrv-package']"

**Comment by ivankravets** [comment]
Could you reproduce this issue after VSCode restart?

**Comment by ivankravets** [comment]
Please reopen if you still need help
