### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by Wolfram225** [platformio/platformio-home#560]
PIO Core Call Error: "Platform C:\\Users\\wolfram\\.platformio\\platforms\\espressif32\r\n--------\r\nUpdating espressif32                     @ 1.11.1         [1.12.0]\r\nUninstalling espressif32 @ 1.11.1: \t\n\nError: Traceback (most recent call last):\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 566, in move\r\n    os.rename(src, real_dst)\r\nPermissionError: [WinError 5] Zugriff verweigert: 'C:\\\\Users\\\\wolfram\\\\.platformio\\\\platforms\\\\espressif32@src-5f117260f75b328038ec9d3fd0e14a68' -> 'C:\\\\Users\\\\wolfram\\\\.platformio\\\\platforms\\\\espressif32'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 410, in platform_update\r\n    pm.update(platform, only_packages=only_packages, only_check=only_check)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 148, in update\r\n    BasePkgManager.update(self, pkg_dir, requirements, only_check)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 805, in update\r\n    self.uninstall(pkg_dir, after_update=True)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 120, in uninstall\r\n    BasePkgManager.uninstall(self, pkg_dir, requirements)\r\n  File \"c:\\users\\wolfram\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 754, in uninstall\r\n    pkg_dir, join(self.package_dir, self.get_install_dirname(manifest))\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 578, in move\r\n    rmtree(src)\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 516, in rmtree\r\n    return _rmtree_unsafe(path, onerror)\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 395, in _rmtree_unsafe\r\n    _rmtree_unsafe(fullname, onerror)\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 395, in _rmtree_unsafe\r\n    _rmtree_unsafe(fullname, onerror)\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 395, in _rmtree_unsafe\r\n    _rmtree_unsafe(fullname, onerror)\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 400, in _rmtree_unsafe\r\n    onerror(os.unlink, fullname, sys.exc_info())\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\shutil.py\", line 398, in _rmtree_unsafe\r\n    os.unlink(fullname)\r\nPermissionError: [WinError 5] Zugriff verweigert: 'C:\\\\Users\\\\wolfram\\\\.platformio\\\\platforms\\\\espressif32@src-5f117260f75b328038ec9d3fd0e14a68\\\\.git\\\\objects\\\\pack\\\\pack-7bb9e2334a67adbbea211e9741e77fd6738265e1.idx'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by valeros** [comment]
Hi @Wolfram225 ! Try to delete this folder `C:\\Users\\wolfram\\.platformio\\platforms\\espressif32@src-5f117260f75b328038ec9d3fd0e14a68` manually.
