### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by minlingji** [platformio/platformio-home#564]
PIO Core Call Error: "The current working directory /Users/min/Desktop/PIO_code/longan_gd32v will be used for the project.\n\nThe next files/directories have been created in /Users/min/Desktop/PIO_code/longan_gd32v\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing gd32v\ngd32v @ 1.1.2 has been successfully installed!\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment. Anyway, you can submit a feature request here https://github.com/sipeed/platform-gd32v/issues
