### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by robertlipe** [platformio/platformio-home#569]
Installing on MacOS 10.14.6, it auto-reports the following:

PIO Core Call Error: "PlatformManager: Installing nuclei\nnuclei @ 1.0.3 has been successfully installed!\nPackageManager: Installing toolchain-riscv-gcc-nuclei @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

Trying to get to a RISC-V build environment that includes support for the GD32 series and with a simulator. My attempts at building qemu, in particular, have not been productive, so I was seeking prebuilds.

I also have some Kendrite K210 hardware, so I'll try installing that next. I was hoping to stay in the low-cost 32-bit world...

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment, besides there is no QEMU package for GD32-based MCUs. Anyway, you can submit a feature request here https://github.com/Nuclei-Software/platform-nuclei/issues
