### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by Rainer-king** [platformio/platformio-home#570]
PIO Core Call Error: "========================= [SUCCESS] Took 37.06 seconds =========================\r\n\r\nEnvironment           Status    Duration\r\n--------------------  --------  ------------\r\nsipeed-maix-go        SUCCESS   00:00:37.057\r\nsipeed-maix-one-dock  IGNORED\r\nsipeed-maix-bit       IGNORED\r\nsipeed-maixduino      IGNORED\r\n========================= 1 succeeded in 00:00:37.057 ========================="

**Comment by valeros** [comment]
Hi @Rainer-king ! It's hard to guess what went wrong from the error message you attached. Could you please provide more information about the error?
