### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by pykcheung** [platformio/platformio-home#573]
PIO Core Call Error: "The current working directory /Users/peterc/Documents/PlatformIO/Projects/Hello World will be used for the project.\n\nThe next files/directories have been created in /Users/peterc/Documents/PlatformIO/Projects/Hello World\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\nPLATFORM: Espressif 32 1.12.0 > Espressif ESP32 Dev Module\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40000.200303 (4.0.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.9.0 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nError: Detected a whitespace character in project paths.\n========================== [FAILED] Took 0.64 seconds =========================="

**Comment by valeros** [comment]
You have white space characters in project path `Hello World`, starting with `ESP-IDF v4.0` they  are not allowed.  More info [here](https://docs.platformio.org/en/latest/frameworks/espidf.html#configuration).
