### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by wwwwwwdw** [platformio/platformio-home#579]
PIO Core Call Error: "The current working directory /Users/wdw/PlatformIOTest will be used for the project.\n\nThe next files/directories have been created in /Users/wdw/PlatformIOTest\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing ststm32\nststm32 @ 6.1.0 has been successfully installed!\n\n\nError:"

**Comment by valeros** [comment]
Hi @wwwwwwdw  ! It's hard to guess what went wrong from the error message you attached. Could you please provide more information about the problem?
