### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by wmtorres** [platformio/platformio-home#583]
PIO Core Call Error: "The current working directory C:\\Users\\uidw2311\\Documents\\PlatformIO\\Projects\\teste will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\uidw2311\\Documents\\PlatformIO\\Projects\\teste\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Traceback (most recent call last):\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\project.py\", line 143, in project_init\r\n    pg.generate()\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\platformio\\ide\\projectgenerator.py\", line 133, in generate\r\n    contents = self._render_tpl(tpl_path, tpl_vars)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\lib\\site-packages\\platformio\\ide\\projectgenerator.py\", line 139, in _render_tpl\r\n    return bottle.SimpleTemplate(fp.read()).render(**tpl_vars)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\Scripts\\bottle.py\", line 3419, in render\r\n    self.execute(stdout, env)\r\n  File \"C:\\Users\\uidw2311\\.platformio\\penv\\Scripts\\bottle.py\", line 3406, in execute\r\n    eval(self.co, env)\r\n  File \"<string>\", line 70, in <module>\r\nNameError: name 'includes' is not defined\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by valeros** [comment]
Hi @wmtorres ! Could you please provide more information? What board/framework you are trying to use?
