### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by pwatson100** [platformio/platformio-home#584]
Not sure why I got this. It was working fine on Monday when I last used it.

PIO Core Call Error: "Error: The directory `C:\\Users\\paul\\.platformio` or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually `C:\\Users\\paul\\.platformio` directory and PlatformIO will create new from the current user."

I restarted Visual Studio and did an update all and it's fine now.

**Comment by valeros** [comment]
Closing the issue since it works after restart.
