### ISSUE TITLE
Version list on platform page shows clipped values

### ISSUE THREAD

**Issue by valeros** [platformio/platformio-home#59]
For some reason versions in the drop-down menu are showed in an inadequate way:
![version](https://user-images.githubusercontent.com/886732/68714159-041ee680-05a8-11ea-96cd-679294374519.png)

**Comment by ivankravets** [comment]
The same problem should be for Libraries > Search > Install.

@elyulka please take a look how can we reserve some space for dropdown menu to avoid issue on windows.

**Comment by valeros** [comment]
Actually libraries are totally fine:
![verlib](https://user-images.githubusercontent.com/886732/68717259-f6209400-05ae-11ea-8d0d-92bff29e8fd4.png)
