### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by se09deluca** [platformio/platformio-home#590]
PIO Core Call Error: "PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\nPackageManager: Installing framework-arduinoespressif32 @ ~3.10004.191002\nframework-arduinoespressif32 @ 3.10004.200129 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~2.20501.7\ntool-scons @ 2.20501.191222 has been successfully installed!\n======================== [SUCCESS] Took 1689.95 seconds ========================"

**Comment by valeros** [comment]
Hi @se09deluca ! It's hard to guess what went wrong from the error message you attached. Could you please provide more information about the problem?
