### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by engineerJishnu** [platformio/platformio-home#592]
PIO Core Call Error: "The current working directory /home/pi/Documents/PlatformIO/Projects/kutta will be used for the project.\n\nThe next files/directories have been created in /home/pi/Documents/PlatformIO/Projects/kutta\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing sifive\nsifive @ 2.1.0 has been successfully installed!\nPackageManager: Installing toolchain-riscv @ ~1.80300.0\n\n\nError: Could not find a version that satisfies the requirement '~1.80300.0' for your system 'linux_armv7l'"

**Comment by valeros** [comment]
Hi @engineerJishnu ! Unforunately, there is toolchain for for ARM architecture at the moment. Please open an issue in this repository https://github.com/platformio/platform-sifive/issues
