### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by tokaphi** [platformio/platformio-home#593]
PIO Core Call Error: "Library Storage: C:\\Users\\Philippe\\Documents\\PlatformIO\\Projects\\Notifheure\\.pio\\libdeps\\d1_mini\nLibraryManager: Installing id=1105 @ ^2012.08.29\n\n\nError: Could not find a version that satisfies the requirement '^2012.08.29' for your system 'windows_x86'"

**Comment by ivankravets** [comment]
Just add `clickButton` to `lib_deps` of your project. See https://docs.platformio.org/en/latest/librarymanager/quickstart.html
