### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by dmamontov** [platformio/platformio-home#594]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/commands/boards.py\", line 31, in cli\n    return _print_boards_json(query, installed)\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/commands/boards.py\", line 80, in _print_boards_json\n    for board in _get_boards(installed):\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/commands/boards.py\", line 75, in _get_boards\n    return pm.get_installed_boards() if installed else pm.get_all_boards()\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/managers/platform.py\", line 205, in get_all_boards\n    boards = self.get_installed_boards()\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/util.py\", line 59, in wrapper\n    self.cache[key] = (time.time(), func(*args, **kwargs))\n  File \"/usr/local/Cellar/platformio/4.3.1/libexec/lib/python3.8/site-packages/platformio/managers/platform.py\", line 194, in get_installed_boards\n    for config in p.get_boards().values():\n  File \"/Users/d.mamontov/.platformio/platforms/atmelsam/platform.py\", line 104, in get_boards\n    result[key] = self._add_default_debug_tools(result[key])\n  File \"/Users/d.mamontov/.platformio/platforms/atmelsam/platform.py\", line 147, in _add_default_debug_tools\n    assert openocd_chipname\nAssertionError\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by valeros** [comment]
Hi @dmamontov! Looks like there is a problem with some board manifest. Try to delete `/Users/d.mamontov/.platformio/platforms/atmelsam/` folder .
