### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by PanwarParamveer** [platformio/platformio-home#608]
PIO Core Call Error: "framework-arduinoespressif8266 @ 3.20603.200130 has been successfully installed!\r\nCorePackageManager: Installing tool-scons @ ~3.30102.0\r\ntool-scons @ 3.30102.0 has been successfully installed!\r\n========================= [SUCCESS] Took 83.01 seconds ========================="

**Comment by valeros** [comment]
Hi @PanwarParamveer ! I don't see any error messages. Could you please provide more information?
