### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by nick-holgate** [platformio/platformio-home#641]
PIO Core Call Error: "Platform C:\\Users\\Nick\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\r\n--------\r\nUpdating espressif8266                   @ 4db7ada        [Detached]\r\nUpdating toolchain-xtensa                @ 1.40802.0      [2.40802.191122]\r\nUninstalling toolchain-xtensa @ 2.40802.191122: \t[OK]\r\nPackageManager: Installing toolchain-xtensa @ 2.40802.191122\r\ntoolchain-xtensa @ 2.40802.191122 has been successfully installed!\r\nUpdating framework-arduinoespressif8266  @ 11c3757        \n\nError: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'out': '', 'err': \"remote: Repository not found.\\nfatal: repository 'https://github.com/Jason2866/Arduino.git/' not found\\n\", 'returncode': 128})"

**Comment by valeros** [comment]
What project are you trying to compile? There is no such repository https://github.com/Jason2866/Arduino.git
