### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by winkste** [platformio/platformio-home#643]
PIO Core Call Error: "The current working directory /Users/stephan_wink/Documents/PlatformIO/Projects/200423-065342-espidf-blink will be used for the project.\n\nThe next files/directories have been created in /Users/stephan_wink/Documents/PlatformIO/Projects/200423-065342-espidf-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32dev (platform: espressif32; framework: espidf; board: esp32dev)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\nPLATFORM: Espressif 32 1.12.0 > Espressif ESP32 Dev Module\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40000.200303 (4.0.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.9.0 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nsh: /Volumes/Macintosh: No such file or directory\n*** Error 127\nReading CMake configuration...\n-- Found Git: /usr/bin/git (found version \"2.21.1 (Apple Git-122.3)\") \n-- IDF_TARGET not set, using default target: esp32\n-- The C compiler identification is GNU 8.2.0\n-- The CXX compiler identification is GNU 8.2.0\n-- The ASM compiler identification is GNU\n-- Found assembler: /Users/stephan_wink/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc\n-- Check for working C compiler: /Users/stephan_wink/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc\n-- Check for working C compiler: /Users/stephan_wink/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Detecting C compile features\n-- Detecting C compile features - done\n-- Check for working CXX compiler: /Users/stephan_wink/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++\n-- Check for working CXX compiler: /Users/stephan_wink/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Detecting CXX compile features\n-- Detecting CXX compile features - done\n-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.\n-- Project version: 1\n-- Building ESP-IDF components for target esp32\n-- Checking Python dependencies...\nThe following Python requirements are not satisfied:\nfuture>=0.15.2\ncryptography>=2.1.4\npyparsing>=2.0.3,<2.4.0\nPlease refer to the Get Started section of the ESP-IDF Programming Guide for setting up the required packages.\nAlternatively, you can run \"/Volumes/Macintosh HD/Users/stephan_wink/.platformio/penv/bin/python -m pip install -r /Users/stephan_wink/.platformio/packages/framework-espidf/requirements.txt\" for resolving the issue.\n-- Configuring incomplete, errors occurred!\nSee also \"/Users/stephan_wink/Documents/PlatformIO/Projects/200423-065342-espidf-blink/.pio/build/esp32dev/CMakeFiles/CMakeOutput.log\".\nfatal: not a git repository (or any of the parent directories): .git\nCMake Error at /Users/stephan_wink/.platformio/packages/framework-espidf/tools/cmake/build.cmake:270 (message):\n  Some Python dependencies must be installed.  Check above message for\n  details.\nCall Stack (most recent call first):\n  /Users/stephan_wink/.platformio/packages/framework-espidf/tools/cmake/build.cmake:396 (__build_check_python)\n  /Users/stephan_wink/.platformio/packages/framework-espidf/tools/cmake/project.cmake:337 (idf_build_process)\n  CMakeLists.txt:3 (project)\n========================== [FAILED] Took 1.37 seconds =========================="

**Comment by valeros** [comment]
Hi @winkste ! Could you please open the terminal in VSCode and run the following command:
```
pip install -r /Users/stephan_wink/.platformio/packages/framework-espidf/requirements.txt
```
and try to create a new project.
