### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/olikraus/U8g2_Arduino/master/library.properties

### ISSUE THREAD

**Issue by michaeleastern** [platformio/platformio-home#644]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /olikraus/U8g2_Arduino/master/library.properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001447C489AC8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by valeros** [comment]
GitHub is having occasional infrastructure issues these days, so if you try again it should work.
