### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by JoergSH** [platformio/platformio-home#655]
PIO Core Call Error: "The current working directory /home/joerg/Documents/PlatformIO/Projects/stf4test will be used for the project.\n\nThe next files/directories have been created in /home/joerg/Documents/PlatformIO/Projects/stf4test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'adafruit_feather_f405'"

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platformio-home/issues/606
