### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by dodohack** [platformio/platformio-home#658]
PIO Core Call Error: "The current working directory /Users/aries/Documents/PlatformIO/Projects/200427-100544-dhrystone will be used for the project.\n\nThe next files/directories have been created in /Users/aries/Documents/PlatformIO/Projects/200427-100544-dhrystone\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by valeros** [comment]
Unfortunately there is no toolchain for MacOS at the moment. Anyway, you can submit a feature request here https://github.com/sipeed/platform-gd32v/issues
