### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Kostins1** [platformio/platformio-home#669]
PIO Core Call Error: "********************************************************************************\nObsolete PIO Core v4.3.1 is used (previous was 4.3.3)\nPlease remove multiple PIO Cores from a system:\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\n********************************************************************************\n\nThe current working directory /Users/kost/Documents/PlatformIO/Projects/1 will be used for the project.\n\nThe next files/directories have been created in /Users/kost/Documents/PlatformIO/Projects/1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Traceback (most recent call last):\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/platformio/commands/project.py\", line 143, in project_init\n    pg.generate()\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 133, in generate\n    _relpath = root.replace(tpls_dir, \"\")\n  File \"/Users/kost/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 139, in _render_tpl\n    def generate(self):\n  File \"/Users/kost/.platformio/penv/bin/bottle.py\", line 3419, in render\n    self.execute(stdout, env)\n  File \"/Users/kost/.platformio/penv/bin/bottle.py\", line 3406, in execute\n    eval(self.co, env)\n  File \"<string>\", line 75, in <module>\nNameError: name 'filter_includes' is not defined\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
https://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system

Please uninstall all PlatformIO Cores and use the latest 4.3.3
