### ISSUE TITLE
Could not load serial devices

### ISSUE THREAD

**Issue by BeautifulNow97** [platformio/platformio-home#67]
PIO Core Call Error: "spawnProcess not available since pywin32 is not installed."

**Comment by ivankravets** [comment]
Please update PlatformIO IDE extension to the latest version.
Remove `USER_HOME_DIR/.platformio/penv` folder

Restart VSCode.

**Comment by okelk** [comment]
Unfortunately this solution did not work for me :(

**Comment by ivankravets** [comment]
Could it be related to https://github.com/platformio/platformio-home/issues/1772 ?

**Comment by okelk** [comment]
Uninstalling/removing and reinstalling both VScode and platformIO (multiple times) did not work for me.
Everything seems to work again after installing the PlatformIO Core (CLI tool).
