### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by ToLu24** [platformio/platformio-home#706]
PIO Core Call Error: "Library Storage: /Users/torbjornlundahl/.platformio/lib\nLibraryManager: Installing id=663 @ ^1.0.2\n\n\nError: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by ivankravets** [comment]
Should be fixed in the latest PlatformIO IDE 2.0
