### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by sounschu** [platformio/platformio-home#71]
PIO Core Call Error: "Library Storage: C:\\Users\\bee\\.platformio\\lib\r\nUpdating ESP8266 and ESP32 Oled Driver for SSD1306 display @ 4.0.0          [4.1.0]\r\nUninstalling ESP8266 and ESP32 Oled Driver for SSD1306 display @ 4.0.0: \t[OK]\r\nLooking for ESP8266 and ESP32 Oled Driver for SSD1306 display library in registry\r\n\n\nError: Library `{'name': 'ESP8266 and ESP32 Oled Driver for SSD1306 display', 'requirements': '4.1.0'}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'name': 'ESP8266 and ESP32 Oled Driver for SSD1306 display', 'requirements': '4.1.0'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core/issues/2443
