### ISSUE TITLE
Could not load boards list

### ISSUE THREAD

**Issue by paultissue** [platformio/platformio-home#7110]
PIO Core Call Error: "UnknownPlatform: Unknown development platform 'PackageItem <path=C:\\Users\\pault\\.platformio\\platforms\\espressif32@3.1.1 metadata=PackageMetadata <type=platform name=espressif32 version=3.1.1 spec={'owner': 'platformio', 'id': 8026, 'name': 'espressif32', 'requirements': None, 'uri': None}'"

**Comment by paultissue** [comment]
Initially could not load boards. 
Deleted "C:\Users\pault\.platformio", restarted VSCode and loaded project to reinstall PlatformIO.  All is well now.

**Comment by HWerneck** [comment]
Worked for another board as explained, thanks.
