### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by jirisrba** [platformio/platformio-home#728]
PIO Core Call Error: "The current working directory /Users/jirisrba/Documents/PlatformIO/Projects/siton-oled will be used for the project.\n\nThe next files/directories have been created in /Users/jirisrba/Documents/PlatformIO/Projects/siton-oled\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing ttgo-lora32-v2 (platform: espressif32; board: ttgo-lora32-v2; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'ttgo-lora32-v2'\n========================== [FAILED] Took 0.72 seconds =========================="

**Comment by valeros** [comment]
Looks like you're using an outdated `espressif32` platform, please run `platformio update` command in PlatformIO IDE terminal.
