### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by grahamehorner** [platformio/platformio-home#735]
PIO Core Call Error: "The current working directory C:\\Users\\ghorner2\\OneDrive - DXC Production\\Documents\\PlatformIO\\Projects\\ContactTracing will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\ghorner2\\OneDrive - DXC Production\\Documents\\PlatformIO\\Projects\\ContactTracing\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\r\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\r\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\r\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\r\nPackageManager: Installing framework-espidf @ ~3.40000.0\r\nframework-espidf @ 3.40000.200303 has been successfully installed!\r\nPackageManager: Installing tool-cmake @ ~3.16.0\r\ntool-cmake @ 3.16.5 has been successfully installed!\r\nPackageManager: Installing tool-ninja @ ^1.7.0\r\ntool-ninja @ 1.9.0 has been successfully installed!\r\nPackageManager: Installing tool-mconf @ ~1.4060000.0\r\ntool-mconf @ 1.4060000.20190628 has been successfully installed!\r\nPackageManager: Installing tool-idf @ ~1.0.1\r\ntool-idf @ 1.0.1 has been successfully installed!\r\nCorePackageManager: Installing tool-scons @ ~3.30102.0\r\ntool-scons @ 3.30102.0 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html\r\nPLATFORM: Espressif 32 1.12.1 > DOIT ESP32 DEVKIT V1\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40000.200303 (4.0.0) \r\n - tool-cmake 3.16.5 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200226 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\nRequirement already satisfied: cryptography>=2.1.4 in c:\\users\\ghorner2\\.platformio\\packages\\contrib-pysite (2.8)\r\nCollecting future>=0.15.2\r\n  Downloading future-0.18.2.tar.gz (829 kB)\r\nCollecting pyparsing<2.4.0,>=2.0.3\r\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\r\nRequirement already satisfied: six>=1.4.1 in c:\\users\\ghorner2\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.12.0)\r\nRequirement already satisfied: cffi!=1.11.3,>=1.8 in c:\\users\\ghorner2\\.platformio\\packages\\contrib-pysite (from cryptography>=2.1.4) (1.13.0)\r\nRequirement already satisfied: pycparser in c:\\users\\ghorner2\\.platformio\\packages\\contrib-pysite (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4) (2.19)\r\nBuilding wheels for collected packages: future\r\n  Building wheel for future (setup.py): started\r\n  Building wheel for future (setup.py): finished with status 'done'\r\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=6546658ff141ca077197b5befce4c856a9e1ac995ab793032a0468c511f09f21\r\n  Stored in directory: c:\\users\\ghorner2\\appdata\\local\\pip\\cache\\wheels\\8e\\70\\28\\3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4\r\nSuccessfully built future\r\nInstalling collected packages: future, pyparsing\r\nSuccessfully installed future-0.18.2 pyparsing-2.3.1\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 87.88 seconds ========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in your username. Starting with ESP-IDF v4.0 it's not allowed. You can try to change [Core Dir](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#core-dir) option to a path without spaces.
