### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by tomasmcguinness** [platformio/platformio-home#744]
PIO Core Call Error: "The current working directory C:\\Development\\LED Clock\\LED Clock ESP-IDF will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Development\\LED Clock\\LED Clock ESP-IDF\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing wemos_d1_mini32 (platform: espressif32; board: wemos_d1_mini32; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/wemos_d1_mini32.html\r\nPLATFORM: Espressif 32 1.12.1 > WeMos D1 MINI ESP32\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40000.200303 (4.0.0) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200226 (8.2.0)\r\nError: Detected a whitespace character in project paths.\r\n========================== [FAILED] Took 0.92 seconds =========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in the project name. Starting with ESP-IDF v4.0 it's not allowed. You can try to change [Core Dir](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#core-dir) option to a path without spaces.
