### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Sakvojage** [platformio/platformio-home#751]
PIO Core Call Error: "The current working directory /home/ignas/Documents/PlatformIO/Projects/OLED blink will be used for the project.\n\nThe next files/directories have been created in /home/ignas/Documents/PlatformIO/Projects/OLED blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\n--------------------------------------------------------------------------------\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\nPackageManager: Installing framework-espidf @ ~3.40000.0\nframework-espidf @ 3.40000.200303 has been successfully installed!\nPackageManager: Installing tool-cmake @ ~3.16.0\ntool-cmake @ 3.16.4 has been successfully installed!\nPackageManager: Installing tool-ninja @ ^1.7.0\ntool-ninja @ 1.7.1 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~3.30102.0\ntool-scons @ 3.30102.0 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\nPLATFORM: Espressif 32 1.12.1 > Espressif ESP32 Dev Module\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40000.200303 (4.0.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.7.1 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nCollecting cryptography>=2.1.4\n  Using cached cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)\nProcessing /home/ignas/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl\nCollecting pyparsing<2.4.0,>=2.0.3\n  Using cached pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\nCollecting six>=1.4.1\n  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)\nCollecting cffi!=1.11.3,>=1.8\n  Using cached cffi-1.14.0-cp38-cp38-manylinux1_x86_64.whl (409 kB)\nCollecting pycparser\n  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)\nInstalling collected packages: six, pycparser, cffi, cryptography, future, pyparsing\nSuccessfully installed cffi-1.14.0 cryptography-2.9.2 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.14.0\nError: Detected a whitespace character in project paths.\n========================= [FAILED] Took 40.77 seconds ========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in the project name. Starting with ESP-IDF v4.0 it's not allowed. You can try to change [Core Dir](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#core-dir) option to a path without spaces.
