### ISSUE TITLE
3.1 beta - Project Configuration reset button naming

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#77]
Query: Is the button being named `Reset` as intuitive as it could be? I am under the impression it does do a 'reset' of sorts - i.e. resets the configurator state to that of the `platformio.ini`... but I wonder if it would be better called 'Reload' or 'Refresh'? Or perhaps 'Revert' as in 'Revert to saved'?

I for one was hesitant to click on it... because I thought it might somehow reset my project.ini to some default state - silly, I know... but that was my initial take on it.

**Comment by ivankravets** [comment]
@elyulka How about to name it `Revert`?

**Comment by ivankravets** [comment]
Fixed
