### ISSUE TITLE
TFT_eSPI

### ISSUE THREAD

**Issue by lf8013** [platformio/platformio-home#770]
PIO Core Call Error: "'utf-8' codec can't decode byte 0xb3 in position 671: invalid start byte"

**Comment by valeros** [comment]
Please provide an output from the system terminal:
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
To me it looks like is caused by Python 2.x. Could you please try to install Python 3.7
https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
