### ISSUE TITLE
Could not initialize project with space in project name ESP-32 ESP-IDF

### ISSUE THREAD

**Issue by lubomirskirka** [platformio/platformio-home#774]
PIO Core Call Error: "The current working directory /Users/lubomirskirka/Documents/PlatformIO/Projects/esp32 sdk will be used for the project.\n\nThe next files/directories have been created in /Users/lubomirskirka/Documents/PlatformIO/Projects/esp32 sdk\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\n--------------------------------------------------------------------------------\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\nPackageManager: Installing framework-espidf @ ~3.40000.0\nframework-espidf @ 3.40000.200303 has been successfully installed!\nPackageManager: Installing tool-cmake @ ~3.16.0\ntool-cmake @ 3.16.4 has been successfully installed!\nPackageManager: Installing tool-ninja @ ^1.7.0\ntool-ninja @ 1.9.0 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html\nPLATFORM: Espressif 32 1.12.1 > Espressif ESP32 Dev Module\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40000.200303 (4.0.0) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.9.0 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nCollecting cryptography>=2.1.4\n  Using cached cryptography-2.9.2-cp35-abi3-macosx_10_9_x86_64.whl (1.8 MB)\nCollecting future>=0.15.2\n  Downloading future-0.18.2.tar.gz (829 kB)\nCollecting pyparsing<2.4.0,>=2.0.3\n  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\nCollecting cffi!=1.11.3,>=1.8\n  Using cached cffi-1.14.0-cp37-cp37m-macosx_10_9_x86_64.whl (174 kB)\nCollecting six>=1.4.1\n  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)\nCollecting pycparser\n  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)\nBuilding wheels for collected packages: future\n  Building wheel for future (setup.py): started\n  Building wheel for future (setup.py): finished with status 'done'\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=f077a175d3582759172ca93e1cbed4bb009ce891bd81e98d0443ae5cc9785fd6\n  Stored in directory: /Users/lubomirskirka/Library/Caches/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0\nSuccessfully built future\nInstalling collected packages: pycparser, cffi, six, cryptography, future, pyparsing\nSuccessfully installed cffi-1.14.0 cryptography-2.9.2 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.14.0\nError: Detected a whitespace character in project paths.\n========================= [FAILED] Took 101.18 seconds ========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in the project name `esp32 sdk`. Starting with ESP-IDF v4.0 it's not allowed.
