### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by nickm324** [platformio/platformio-home#778]
PIO Core Call Error: "Library Storage: Z:\\Software\\Marlin-2.0.1\\Marlin-2.0.1\\.pio\\libdeps\\sanguino_atmega1284p\r\nUpdating LiquidCrystal                   @ 1.3.4          [1.5.0]\r\nUninstalling LiquidCrystal @ 1.3.4: \t[OK]\r\nLooking for LiquidCrystal library in registry\r\nLiquidCrystal\r\n=============\r\n#ID: 136\r\nLiquidCrystal Library is faster and extensable, compatible with the original LiquidCrystal library\r\n\r\nKeywords: lcd, hd44780\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Espressif 32, Espressif 8266\r\nAuthors: F Malpartida\r\n\r\nLiquidCrystal\r\n=============\r\n#ID: 887\r\nAllows communication with alphanumerical liquid crystal displays (LCDs).\r\n\r\nKeywords: display\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, Teensy, TI MSP430\r\nAuthors: Arduino, Adafruit\r\n\r\nFound: https://platformio.org/lib/show/136/LiquidCrystal\r\nLibraryManager: Installing id=136 @ 1.5.0\r\n\n\nConflict: More than one library has been found by request {\"name\": \"LiquidCrystal\", \"requirements\": \"1.5.0\"}:\r\nAutomatically chose the first available library (use `--interactive` option to make a choice)\r\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 260, in lib_update\r\n    lm.update(library, only_check=only_check)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 806, in update\r\n    self.install(name, latest, after_update=True)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 281, in install\r\n    force=force,\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 700, in install\r\n    pkg_dir = self._install_from_piorepo(name, requirements)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 131, in _install_from_piorepo\r\n    requirements,\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 499, in _install_from_url\r\n    return self._install_from_tmp_dir(_tmp_dir, requirements)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 524, in _install_from_tmp_dir\r\n    cur_manifest = self.load_manifest(pkg_dir)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 339, in load_manifest\r\n    src_manifest_path = self.get_src_manifest_path(pkg_dir)\r\n  File \"c:\\users\\rippe\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 311, in get_src_manifest_path\r\n    for item in os.listdir(pkg_dir):\r\nOSError: [WinError 6] The handle is invalid: 'Z:\\\\Software\\\\Marlin-2.0.1\\\\Marlin-2.0.1\\\\.pio\\\\libdeps\\\\sanguino_atmega1284p\\\\LiquidCrystal_ID136'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Should be fixed in the latest PlatformIO IDE 2.0
