### ISSUE TITLE
3.1 beta - Project configuration - file watcher / notification

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#78]
Is it possible to implement some form of file watcher that would pop up a notification if the project configurator GUI was open, and the file was altered externally? i.e. 'Project configuration has been changed. Do you want to load the new configuration?'

**Comment by ivankravets** [comment]
Could we fetch RPC `os.get_file_mtime(path_to_platformio.ini)` after reading and compare it before saving?

P.S: `pio upgrade --dev` to get `os.get_file_mtime`.
