### ISSUE TITLE
3.1 beta - Project Configuration - default value indication

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#79]
Feature Request

Is there some way to indicate when showing that the value of a option defaults to that it is currently not set / that it is currently in it's default state? i.e. all of the following are in their default (unset) state, but I don't know that until I click on it and try to type in them. Maybe a different colour if indicating default value?

![image](https://user-images.githubusercontent.com/5500713/68990944-e9e55100-08a4-11ea-8f07-e1eadaecc476.png)

**Comment by ivankravets** [comment]
@elyulka is it possible to make "darkness" default values in input?
