### ISSUE TITLE
Libraries: Installed

### ISSUE THREAD

**Issue by FernandoTusell** [platformio/platformio-home#793]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/commands/lib.py\", line 282, in lib_list\n    items = lm.get_installed()\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/managers/package.py\", line 374, in get_installed\n    manifest = self.load_manifest(pkg_dir)\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/managers/package.py\", line 347, in load_manifest\n    manifest = ManifestParserFactory.new_from_file(manifest_path).as_dict()\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/package/manifest/parser.py\", line 74, in new_from_file\n    cls.read_manifest_contents(path), type_from_uri, remote_url\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/site-packages/platformio/package/manifest/parser.py\", line 64, in read_manifest_contents\n    return fp.read()\n  File \"/home/etptupaf/.platformio/penv/lib/python3.7/codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 69: invalid continuation byte\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by valeros** [comment]
Please provide an output from the system terminal:
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
To me it looks like is caused by Python 2.x. Could you please try to install Python 3.7
https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
