### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by thenewdays** [platformio/platformio-home#815]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\thene\\\\.platformio\\\\platforms\\\\stm32-usb-bootloader\\\\platform.json'","type":"FileNotFoundError"}

**Comment by valeros** [comment]
Hi @thenewdays ! `stm32-usb-bootloader` folder shouldn't be here `C:\\Users\\thene\\.platformio\\platforms\\stm32-usb-bootloader`

**Comment by thenewdays** [comment]
The folder is empty.

**Comment by thenewdays** [comment]
Where should the folder be located?
