### ISSUE TITLE
ModuleNotFoundError: No module named 'multiprocessing'

### ISSUE THREAD

**Issue by thorsten-l** [platformio/platformio-home#82]
PIO Core Call Error: "The current working directory /Users/th/Projects/PlatformIO/esp8266/ESP8266-CC1101 will be used for the project.\n\nThe next files/directories have been created in /Users/th/Projects/PlatformIO/esp8266/ESP8266-CC1101\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Traceback (most recent call last):\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/commands/init.py\", line 101, in cli\n    pg.generate()\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 125, in generate\n    tpl_vars = self._load_tplvars()\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 78, in _load_tplvars\n    tpl_vars.update(load_project_ide_data(self.project_dir, self.env_name) or {})\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/project/helpers.py\", line 140, in load_project_ide_data\n    from platformio.commands.run.command import cli as cmd_run\n  File \"/Users/th/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py\", line 15, in <module>\n    from multiprocessing import cpu_count\nModuleNotFoundError: No module named 'multiprocessing'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> ModuleNotFoundError: No module named 'multiprocessing'

How did you install Python 3.7? It seems like a broken Python 3.

https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.cpu_count

**Comment by ivankravets** [comment]
Please reopen if you still need help
