### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by bluequantum** [platformio/platformio-home#834]
PIO Core Call Error: "The current working directory /Users/bluepepper/Desktop/mcu/nano again will be used for the project.\n\nThe next files/directories have been created in /Users/bluepepper/Desktop/mcu/nano again\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing nanoatmega328 (platform: atmelavr; board: nanoatmega328; framework: arduino)\n--------------------------------------------------------------------------------\nIOError: [Errno 13] Permission denied: '/etc/paths.d/Wireshark':\n  File \"/Users/bluepepper/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py\", line 89:\n    env = DefaultEnvironment(**DEFAULT_ENV_OPTIONS)\n  File \"/Users/bluepepper/.platformio/packages/tool-scons/script/../engine/SCons/Defaults.py\", line 88:\n    _default_env = SCons.Environment.Environment(*args, **kw)\n  File \"/Users/bluepepper/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 953:\n    platform(self)\n  File \"/Users/bluepepper/.platformio/packages/tool-scons/script/../engine/SCons/Platform/__init__.py\", line 129:\n    return self.generate(*args, **kw)\n  File \"/Users/bluepepper/.platformio/packages/tool-scons/script/../engine/SCons/Platform/darwin.py\", line 59:\n    f = open(file, 'r')\n========================== [FAILED] Took 0.61 seconds =========================="

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platformio-home/issues/582
