### ISSUE TITLE
could not initialize Project

### ISSUE THREAD

**Issue by normuser** [platformio/platformio-home#845]
PIO Core Call Error: "The current working directory /home/patrick/Documents/PlatformIO/Projects/XMC will be used for the project.

The next files/directories have been created in /home/patrick/Documents/PlatformIO/Projects/XMC
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Error: Processing xmc1100_xmc2go (platform: infineonxmc; board: xmc1100_xmc2go; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/infineonxmc/xmc1100_xmc2go.html
PLATFORM: Infineon XMC 1.1.4 > XMC1100 XMC2Go
HARDWARE: XMC1100 32MHz, 16KB RAM, 64KB Flash
DEBUG: Current (jlink) On-board (jlink)
PACKAGES: 
 - framework-arduinoxmc 1.4.0 
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 257: invalid start byte:
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py\", line 168:
 env.SConscript(\"$BUILD_SCRIPT\")
 File \"/home/patrick/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 597:
 return _SConscript(self.fs, *files, **subst_kw)
 File \"/home/patrick/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 286:
 exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
 File \"/home/patrick/.platformio/platforms/infineonxmc/builder/main.py\", line 142:
 target_elf = env.BuildProgram()
 File \"/home/patrick/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 219:
 return self.method(*nargs, **kwargs)
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 62:
 env.ProcessProjectDeps()
 File \"/home/patrick/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 219:
 return self.method(*nargs, **kwargs)
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/platformio.py\", line 131:
 project_lib_builder = env.ConfigureProjectLibBuilder()
 File \"/home/patrick/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 219:
 return self.method(*nargs, **kwargs)
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 1038:
 lib_builders = env.GetLibBuilders()
 File \"/home/patrick/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 219:
 return self.method(*nargs, **kwargs)
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 963:
 lb = LibBuilderFactory.new(env, lib_dir)
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 59:
 obj = getattr(sys.modules[__name__], clsname)(env, path, verbose=verbose)
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 118:
 self._manifest = manifest if manifest else self.load_manifest()
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/piolib.py\", line 470:
 return ManifestParserFactory.new_from_file(manifest_path).as_dict()
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/package/manifest/parser.py\", line 74:
 cls.read_manifest_contents(path), type_from_uri, remote_url
 File \"/home/patrick/.platformio/penv/lib/python3.8/site-packages/platformio/package/manifest/parser.py\", line 64:
 return fp.read()
 File \"/usr/lib/python3.8/codecs.py\", line 322:
 (result, consumed) = self._buffer_decode(data, self.errors, final)
========================== [FAILED] Took 1.47 seconds =========================="

I had the problem when opening a new XMC 1100 - XMC2Go project - both on a Windows machine and this Linux/Arch.

Seems to be similar to #773,
On Linux I have
- Python 3.8.2
- PlatformIO 4.3.4
Platform Infineon XMC
- infineonxmc                     @ 1.1.4          [Up-to-date]
- Updating toolchain-gccarmnoneeabi        @ 1.70201.0      [Up-to-date]
- Updating framework-arduinoxmc            @ 1.4.0          [Up-to-date]

**Comment by valeros** [comment]
Duplicate https://github.com/Infineon/platformio-infineonxmc/issues/12
