### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/squix78/esp8266-oled-ssd1306/master/library.json

### ISSUE THREAD

**Issue by xingyusky111** [platformio/platformio-home#846]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /squix78/esp8266-oled-ssd1306/master/library.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000000000558DA48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by valeros** [comment]
Looks like an issue with Github infrastructure. Please try again later.
