### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by Trayko67** [platformio/platformio-home#848]
PIO Core Call Error: "Library Storage: C:\\Users\\Lobi\\Documents\\PlatformIO\\Projects\\200530-000040-megaatmega1280\\.pio\\libdeps\\megaatmega1280\r\nLooking for Si5351mcu library in registry\r\n\n\nError: Library `{'name': 'Si5351mcu', 'requirements': None}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'name': 'Si5351mcu', 'requirements': None}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by valeros** [comment]
There is no such library in PlatformIO Library registry https://platformio.org/lib/search?query=Si5351mcu
