### ISSUE TITLE
Projects: lib_archive / test_build_project_src saved even though not changed

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-home#85]
I've noticed that in the new project configurator it is saving the following even if they haven't been changed from defaults. 
```
lib_archive = yes
test_build_project_src = no
```
on it's own, even though these options haven't been touched.

It appears from https://github.com/platformio/platformio-home/issues/80#issuecomment-554674074 that if boolean values are at their defaults, they should not be set by the GUI.

I would go one step further, to say if they have not been explicit set (to their defaults) they should not be present, but that is more of a behaviour change, not the current apparent bug.

**Comment by ivankravets** [comment]
Fixed with new UI
