### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by the-real-orca** [platformio/platformio-home#858]
PIO Core Call Error: "Library Storage: P:\\SmartHome\\Projects\\Brunnensteuerung\\SW\\lib\nUpdating PCF8574                         @ 0.1.9          [0.2.0]\r\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 16, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 260, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 805, in update\n    self.uninstall(pkg_dir, after_update=True)\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 723, in uninstall\n    with LockFile(self.package_dir):\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\lockfile.py\", line 102, in __enter__\n    self.acquire()\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\lockfile.py\", line 86, in acquire\n    return self._lock()\n  File \"c:\\users\\stephan\\.platformio\\penv\\lib\\site-packages\\platformio\\lockfile.py\", line 61, in _lock\n    self._fp = open(self._lock_path, \"w\")\nIOError: [Errno 13] Permission denied: 'P:\\\\SmartHome\\\\Projects\\\\Brunnensteuerung\\\\SW\\\\lib.lock'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by valeros** [comment]
Hi @the-real-orca ! Is this error reproducible?
