### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by Edward6329** [platformio/platformio-home#861]
PIO Core Call Error: "Library Storage: C:\\Users\\Administrator\\Desktop\\3D打印机\\固件\\Marlin2.5.2\\.pio\\libdeps\\esp32\n\n\nc:\\users\\administrator\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py:424: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal\n  if manifest[\"__pkg_dir\"] == realpath(pkg_dir):\nError: Traceback (most recent call last):\n  File \"c:\\users\\administrator\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\administrator\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\administrator\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\administrator\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\administrator\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\administrator\\.platformio\\

**Comment by valeros** [comment]
Hi @Edward6329 ! Looks like there is a problem with non-ascii symbols `打印机\固件` in the project path.
What python version is installed in your system?
```
python --version
```
