### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Snehan2k2** [platformio/platformio-home#867]
PIO Core Call Error: "The current working directory C:\\Users\\Snehan Jayakumar\\Documents\\PlatformIO\\Projects\\blink_led will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Snehan Jayakumar\\Documents\\PlatformIO\\Projects\\blink_led\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing espressif32\r\nespressif32 @ 1.12.2 has been successfully installed!\r\nPackageManager: Installing toolchain-xtensa32 @ ~2.50200.0\r\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\r\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\r\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\r\nThe platform 'espressif32' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\r\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\r\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\r\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\r\nPackageManager: Installing framework-espidf @ ~3.40001.0\r\nframework-espidf @ 3.40001.200521 has been successfully installed!\r\nPackageManager: Installing tool-cmake @ ~3.16.0\r\ntool-cmake @ 3.16.5 has been successfully installed!\r\nPackageManager: Installing tool-ninja @ ^1.7.0\r\ntool-ninja @ 1.9.0 has been successfully installed!\r\nPackageManager: Installing tool-mconf @ ~1.4060000.0\r\ntool-mconf @ 1.4060000.20190628 has been successfully installed!\r\nPackageManager: Installing tool-idf @ ~1.0.1\r\ntool-idf @ 1.0.1 has been successfully installed!\r\nCorePackageManager: Installing tool-scons @ ~3.30102.0\r\ntool-scons @ 3.30102.0 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html\r\nPLATFORM: Espressif 32 1.12.2 > DOIT ESP32 DEVKIT V1\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40001.200521 (4.0.1) \r\n - tool-cmake 3.16.5 \r\n - tool-esptoolpy 1.20600.0 (2.6.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \r\n - toolchain-xtensa32 2.80200.200226 (8.2.0)\r\nInstalling ESP-IDF's Python dependencies\r\n'c:\\users\\snehan' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n*** Error 1\r\nError: Detected a whitespace character in project paths.\r\n========================= [FAILED] Took 109.57 seconds ========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in your username. Starting with ESP-IDF v4.0 it's not allowed. You can try to change [Core Dir](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#core-dir) option to a path without spaces.
