### ISSUE TITLE
Could not import Arduino project

### ISSUE THREAD

**Issue by IFXGAWU** [platformio/platformio-home#869]
PIO Core Call Error: "The current working directory C:\\Users\\WulzGerh\\Documents\\PlatformIO\\Projects\\200602-213930-xmc1300_boot_kit will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\WulzGerh\\Documents\\PlatformIO\\Projects\\200602-213930-xmc1300_boot_kit\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing infineonxmc\r\ninfineonxmc @ 1.1.4 has been successfully installed!\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0,<1.80000.0\r\ntoolchain-gccarmnoneeabi @ 1.70201.0 has been successfully installed!\r\nThe platform 'infineonxmc' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing xmc1300_boot_kit (platform: infineonxmc; board: xmc1300_boot_kit; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing framework-arduinoxmc @ ^1.4.0\r\nframework-arduinoxmc @ 1.4.0 has been successfully installed!\r\nCorePackageManager: Installing tool-scons @ ~3.30102.0\r\ntool-scons @ 3.30102.0 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/infineonxmc/xmc1300_boot_kit.html\r\nPLATFORM: Infineon XMC 1.1.4 > XMC1300 Boot Kit\r\nHARDWARE: XMC1300 32MHz, 16KB RAM, 64KB Flash\r\nDEBUG: Current (jlink) On-board (jlink)\r\nPACKAGES: \r\n - framework-arduinoxmc 1.4.0 \r\n - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\r\nLDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf\r\nLDF Modes: Finder ~ chain, Compatibility ~ soft\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 257: invalid start byte:\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\main.py\", line 168:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\platforms\\infineonxmc\\builder\\main.py\", line 142:\r\n    target_elf = env.BuildProgram()\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 62:\r\n    env.ProcessProjectDeps()\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 131:\r\n    project_lib_builder = env.ConfigureProjectLibBuilder()\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 1038:\r\n    lib_builders = env.GetLibBuilders()\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 963:\r\n    lb = LibBuilderFactory.new(env, lib_dir)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 59:\r\n    obj = getattr(sys.modules[__name__], clsname)(env, path, verbose=verbose)\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 118:\r\n    self._manifest = manifest if manifest else self.load_manifest()\r\n  File \"C:\\Users\\WulzGerh\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 470:\r\n    return ManifestParserFactory.new_from_file(manifest_path).as_dict()\r\n  File \"c:\\users\\wulzgerh\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manifest\\parser.py\", line 74:\r\n    cls.read_manifest_contents(path), type_from_uri, remote_url\r\n  File \"c:\\users\\wulzgerh\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manifest\\parser.py\", line 64:\r\n    return fp.read()\r\n  File \"C:\\Users\\WulzGerh\\AppData\\Local\\Programs\\Python\\Python38\\lib\\codecs.py\", line 322:\r\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\r\n========================= [FAILED] Took 15.25 seconds ========================="

**Comment by valeros** [comment]
Duplicate https://github.com/Infineon/platformio-infineonxmc/issues/12
