### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by amryounis** [platformio/platformio-home#88]
PIO Core Call Error: "Library Storage: C:\\Users\\Amr\\.platformio\\lib\r\nLibraryManager: Installing id=850 @ ^2.3.3\r\n\n\nError: Got an unrecognized status code '503' when downloaded http://dl.platformio.org/libraries/archives/8/15832.tar.gz"

**Comment by ivankravets** [comment]
Could you try again? It should work now.
