### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by jarcosrou** [platformio/platformio-home#886]
PIO Core Call Error: "Library Storage: C:\\Users\\Javi\\.platformio\\lib\r\nLooking for LCP1769 library in registry\r\n\n\nError: Library `{'name': 'LCP1769', 'requirements': None}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'name': 'LCP1769', 'requirements': None}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by valeros** [comment]
There is no such library in PlatformIO Library registry https://platformio.org/lib/search?query=LCP1769
