### ISSUE TITLE
Platforms: Registry

### ISSUE THREAD

**Issue by Zezoh** [platformio/platformio-home#89]
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 174, in platform_search\r\n    _get_registry_platform_data(\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 130, in _get_registry_platform_data\r\n    for p in _get_registry_platforms():\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 57, in _get_registry_platforms\r\n    platforms = util.get_api_result(\"/platforms\", cache_valid=\"7d\")\r\n  File \"c:\\users\\abdulaziz halawani\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 344, in get_api_result\r\n    return json.loads(result)\r\n  File \"C:\\Users\\Abdulaziz Halawani\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\json\\__init__.py\", line 357, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"C:\\Users\\Abdulaziz Halawani\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\json\\decoder.py\", line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"C:\\Users\\Abdulaziz Halawani\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\json\\decoder.py\", line 355, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Please run `pio update` and restart VSCode.
