### ISSUE TITLE
Bibliotecas: Não foi possível instalar biblioteca

### ISSUE THREAD

**Issue by bertholdhoffmann** [platformio/platformio-home#890]
PIO Core Call Error: "Library Storage: C:\\Users\\Berthold\\.platformio\\lib\r\nLooking for ITEADLIB library in registry\r\n\n\nError: Library `{'name': 'ITEADLIB', 'requirements': None}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'name': 'ITEADLIB', 'requirements': None}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by valeros** [comment]
There is no such library in PlatformIO Library registry https://platformio.org/lib/search?query=ITEADLIB
