### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by broutok** [platformio/platformio-home#896]
PIO Core Call Error: "The current working directory C:\\Users\\User\\Documents\\Arduino\\test pio platform will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\User\\Documents\\Arduino\\test pio platform\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing espressif32\r\nespressif32 @ 1.12.2 has been successfully installed!\r\nPackageManager: Installing toolchain-xtensa32 @ ~2.50200.0\r\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\r\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\r\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\r\nThe platform 'espressif32' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\r\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\r\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\r\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\r\nPackageManager: Installing framework-espidf @ ~3.40001.0\r\nframework-espidf @ 3.40001.200521 has been successfully installed!\r\nPa

**Comment by valeros** [comment]
Looks like you have a whitespace character in project name `test pio platform`. Starting with ESP-IDF v4.0 it's not allowed.
