### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by wangmings** [platformio/platformio-home#898]
PIO Core Call Error: "Library Storage: /Users/mac/.platformio/lib\nLibraryManager: Installing id=942 @ ^2.28.6\n\n\nError: [API] Invalid response: b'<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\"white\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n'"

**Comment by valeros** [comment]
Hi @wangmings ! Are you able to reproduce the issue?

**Comment by ivankravets** [comment]
Should be fixed now.
