### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by reveyo** [platformio/platformio-home#911]
PIO Core Call Error: "The current working directory /home/david/Documents/PlatformIO/Projects/Test esp32 will be used for the project.\n\nThe next files/directories have been created in /home/david/Documents/PlatformIO/Projects/Test esp32\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing espressif32\nespressif32 @ 1.12.4 has been successfully installed!\nPackageManager: Installing toolchain-xtensa32 @ ~2.50200.0\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\nThe platform 'espressif32' has been successfully installed!\nThe rest of packages will be installed automatically depending on your build environment.\n\n\nError: Processing az-delivery-devkit-v4 (platform: espressif32; board: az-delivery-devkit-v4; framework: espidf)\n--------------------------------------------------------------------------------\nPackageManager: Installing toolchain-xtensa32 @ ~2.80200.0\ntoolchain-xtensa32 @ 2.80200.200226 has been successfully installed!\nPackageManager: Installing toolchain-esp32ulp @ ~1.22851.190618\ntoolchain-esp32ulp @ 1.22851.190618 has been successfully installed!\nPackageManager: Installing framework-espidf @ ~3.40001.0\nframework-espidf @ 3.40001.200521 has been successfully installed!\nPackageManager: Installing tool-cmake @ ~3.16.0\ntool-cmake @ 3.16.4 has been successfully installed!\nPackageManager: Installing tool-ninja @ ^1.7.0\ntool-ninja @ 1.7.1 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~3.30102.0\ntool-scons @ 3.30102.0 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/az-delivery-devkit-v4.html\nPLATFORM: Espressif 32 1.12.4 > AZ-Delivery ESP-32 Dev Kit C V4\nHARDWARE: ESP32 240MHz, 520KB RAM, 16MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40001.200521 (4.0.1) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.7.1 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nInstalling ESP-IDF's Python dependencies\nCollecting cryptography>=2.1.4\n  Downloading cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)\nCollecting future>=0.15.2\n  Downloading future-0.18.2.tar.gz (829 kB)\nCollecting pyparsing<2.4.0,>=2.0.3\n  Using cached pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)\nCollecting cffi!=1.11.3,>=1.8\n  Downloading cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399 kB)\nCollecting six>=1.4.1\n  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)\nCollecting pycparser\n  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)\nBuilding wheels for collected packages: future\n  Building wheel for future (setup.py): started\n  Building wheel for future (setup.py): finished with status 'done'\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=77c3849372f83b6e6f49f74d8e2e8af5fa93a9143ccf39bdd46734c569869b0e\n  Stored in directory: /home/david/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94\nSuccessfully built future\nInstalling collected packages: pycparser, cffi, six, cryptography, future, pyparsing\nSuccessfully installed cffi-1.14.0 cryptography-2.9.2 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 six-1.15.0\nError: Detected a whitespace character in project paths.\n========================= [FAILED] Took 44.55 seconds ========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in project name `Test esp32`. [Starting with ESP-IDF v4.0](https://docs.platformio.org/en/latest/frameworks/espidf.html#limitations) it's not allowed.
