### ISSUE TITLE
Libraries: Updates

### ISSUE THREAD

**Issue by criticalboot** [platformio/platformio-home#914]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/commands/lib.py\", line 251, in lib_update\n    latest = lm.outdated(pkg_dir, requirements)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 641, in outdated\n    latest = self.get_latest_repo_version(\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/managers/lib.py\", line 103, in get_latest_repo_version\n    util.get_api_result(\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/util.py\", line 348, in get_api_result\n    cc.set(cache_key, result, cache_valid)\n  File \"/home/criticalboot/.platformio/penv/lib/python3.8/site-packages/platformio/app.py\", line 234, in set\n    os.makedirs(self.cache_dir)\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\n    mkdir(name, mode)\nFileExistsError: [Errno 17] File exists: '/home/criticalboot/.platformio/.cache'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Fixed in the latest PlatformIO Core 5.0.1-dev. Please re-test with `pio upgrade --dev`.
