### ISSUE TITLE
Could not load project examples

### ISSUE THREAD

**Issue by koval62** [platformio/platformio-home#915]
Server error: {"args":["title"],"message":"'title'","type":"KeyError"}

**Comment by valeros** [comment]
Could you please explain when this error happens?

**Comment by koval62** [comment]
The programming environment was open for more than one day and that's when
the message appeared with error. I rebooted the environment and now
everything works fine. Thanks.

pt., 19 cze 2020 o 17:13 Valerii Koval <notifications@github.com>
napisał(a):
