### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by grbba** [platformio/platformio-home#920]
PIO Core Call Error: "The current working directory /Users/gregor/Documents/PlatformIO/Projects/mDash-2 will be used for the project.\n\nThe next files/directories have been created in /Users/gregor/Documents/PlatformIO/Projects/mDash-2\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing az-delivery-devkit-v4 (platform: espressif32; board: az-delivery-devkit-v4; framework: arduino)\n--------------------------------------------------------------------------------\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\nPackageManager: Installing framework-arduinoespressif32 @ ~3.10004.191002\nThe platform 'espressif32' has been successfully installed!\nThe rest of packages will be installed automatically depending on your build environment."

**Comment by valeros** [comment]
I don't see any error messages in the log. Please try to create a new project from PlatformIO Home.
