### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by j-shirazi** [platformio/platformio-home#926]
PIO Core Call Error: "The current working directory C:\\Users\\Ali\\Documents\\PlatformIO\\Projects\\sadasdas will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\Ali\\Documents\\PlatformIO\\Projects\\sadasdas\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing nrf52840_dk (platform: nordicnrf52; board: nrf52840_dk; framework: zephyr)\n-------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/nrf52840_dk.html\nPLATFORM: Nordic nRF52 4.2.1 > Nordic nRF52840-DK\nHARDWARE: NRF52840 64MHz, 256KB RAM, 1MB Flash\nDEBUG: Current (jlink) On-board (cmsis-dap, jlink) External (blackmagic, stlink)\nPACKAGES: \n - framework-zephyr 2.20200.200401 (2.2.0) \n - framework-zephyr-canopennode 0.20200.200115 (2.2.0) \n - framework-zephyr-civetweb 0.20200.190807 (2.2.0) \n - framework-zephyr-fatfs 0.20200.191125 (2.2.0) \n - framework-zephyr-hal-nordic 0.20200.200130 (2.2.0) \n - framework-zephyr-libmetal 0.20200.190530 (2.2.0) \n - framework-zephyr-littlefs 0.20200.190811 (2.2.0) \n - framework-zephyr-loramac-node 0.20200.191220 (2.2.0) \n - framework-zephyr-lvgl 0.20200.191207 (2.2.0) \n - framework-zephyr-mbedtls 0.20200.200206 (2.2.0) \n - framework-zephyr-mcuboot 0.20200.200219 (2.2.0) \n - framework-zephyr-mcumgr 0.20200.200117 (2.2.0) \n - framework-zephyr-mipi-sys-t 0.20200.191024 (2.2.0) \n - framework-zephyr-nrf-hw-models 0.20200.191115 (2.2.0) \n - framework-zephyr-open-amp 0.20200.190612 (2.2.0) \n - framework-zephyr-openthread 0.20200.191014 (2.2.0) \n - framework-zephyr-segger 0.20200.190421 (2.2.0) \n - framework-zephyr-tinycbor 0.20200.191016 (2.2.0) \n - tool-cmake 3.16.5 \n - tool-dtc 1.4.7 \n - tool-ninja 1.9.0 \n - tool-sreccat 1.164.0 (1.64) \n - toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)\nPython 3.4 or greater required, but you have Python 2.7.16\n========================= [FAILED] Took 5.13 seconds ========================="

**Comment by valeros** [comment]
Looks like your PlatformIO virtual environment was created for Python 2.7.
- Close the IDE
- Make sure Python 3.x is the main Python installation in your system.
- Delete folder `C:\Users\Ali\.platformio\.penv`
- Open the IDE and wait until a new installation is completed
