### ISSUE TITLE
Could not load PIO Account information

### ISSUE THREAD

**Issue by TechyEd** [platformio/platformio-home#93]
PIO Core Call Error: "b''\n\nb'Error: Traceback (most recent call last):\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\__main__.py\", line 102, in main\\r\\n    cli()  # pylint: disable=no-value-for-parameter\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 764, in __call__\\r\\n    return self.main(*args, **kwargs)\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 717, in main\\r\\n    rv = self.invoke(ctx)\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\commands\\\\__init__.py\", line 44, in invoke\\r\\n    return super(PlatformioCLI, self).invoke(ctx)\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 1137, in invoke\\r\\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 1137, in invoke\\r\\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 956, in invoke\\r\\n    return ctx.invoke(self.callback, **ctx.params)\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\click\\\\core.py\", line 555, in invoke\\r\\n    return callback(*args, **kwargs)\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\commands\\\\account.py\", line 72, in account_show\\r\\n    pioplus_call(sys.argv[1:])\\r\\n  File \"c:\\\\users\\\\edmon\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\managers\\\\core.py\", line 133, in pioplus_call\\r\\n    code = subprocess.call([pioplus_path] + args, **kwargs)\\r\\n  File \"C:\\\\Users\\\\edmon\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python38-32\\\\lib\\\\subprocess.py\", line 340, in call\\r\\n    with Popen(*popenargs, **kwargs) as p:\\r\\n  File \"C:\\\\Users\\\\edmon\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python38-32\\\\lib\\\\subprocess.py\", line 854, in __init__\\r\\n    self._execute_child(args, executable, preexec_fn, close_fds,\\r\\n  File \"C:\\\\Users\\\\edmon\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python38-32\\\\lib\\\\subprocess.py\", line 1307, in _execute_child\\r\\n    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,\\r\\nFileNotFoundError: [WinError 2] O sistema n\\xe3o pode encontrar o arquivo especificado\\r\\n\\r\\n============================================================\\r\\n\\r\\nAn unexpected error occurred. Further steps:\\r\\n\\r\\n* Verify that you have the latest version of PlatformIO using\\r\\n  `pip install -U platformio` command\\r\\n\\r\\n* Try to find answer in FAQ Troubleshooting section\\r\\n  https://docs.platformio.org/page/faq.html\\r\\n\\r\\n* Report this problem to the developers\\r\\n  https://github.com/platformio/platformio-core/issues\\r\\n\\r\\n============================================================\\r\\n\\r\\n'"

**Comment by ivankravets** [comment]
Do you use antivirus tools? They block PlatformIO manager.
