### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/jrowberg/i2cdevlib/master/Arduino/MPU6050/library.json

### ISSUE THREAD

**Issue by dmk69** [platformio/platformio-home#938]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jrowberg/i2cdevlib/master/Arduino/MPU6050/library.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)')))

**Comment by ivankravets** [comment]
Resolved in the latest release.
