### ISSUE TITLE
Could not update platform

### ISSUE THREAD

**Issue by VN-vnascimento** [platformio/platformio-home#94]
PIO Core Call Error: "Platform C:\\Users\\vnascimento\\.platformio\\platforms\\ststm32\r\n--------\r\nUpdating ststm32                         @ 87f5ae4        [cad41e7]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please remove `C:\Users\vnascimento\.platformio\platforms\ststm32` and try to build again. It seems you did changes in cloned repo.
