### ISSUE TITLE
Could not load recent projects

### ISSUE THREAD

**Issue by exothink** [platformio/platformio-home#940]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\EliteDesk\\\\.platformio\\\\platforms\\\\Arduino_Core_STM32\\\\platform.json'","type":"FileNotFoundError"}

I can't load 'Platforms' ... etc.  tried deleting 'penv' folder. No help.

**Comment by valeros** [comment]
`C:\\Users\\EliteDesk\\.platformio\\platforms\\Arduino_Core_STM32` what is this folder? How did it get in PlatformIO Home directory? Try to delete it.

**Comment by exothink** [comment]
I have it working now.  

At one time I hacked an install of STM23Arduino 1.9 before it was available on PIO.  I deleted the PIO extension and reinstalled it. All is well.  I also uninstalled all old STM23Arduino versions.
