### ISSUE TITLE
Could not load platform data

### ISSUE THREAD

**Issue by VN-vnascimento** [platformio/platformio-home#95]
PIO Core Call Error: "Platform C:\\Users\\vnascimento\\.platformio\\platforms\\ststm32\r\n--------\r\nUpdating ststm32                         @ 87f5ae4        [cad41e7]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-home/issues/94
