### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by julipoelrey** [platformio/platformio-home#957]
PIO Core Call Error: "Library Storage: C:\\Users\\julio\\.platformio\\lib\nUpdating TimeAlarms                      @ c291c1ddad     [0.0.0-alpha+sha.c291c1ddad]\r\nUninstalling TimeAlarms @ c291c1ddad: \t[OK]\nLooking for TimeAlarms library in registry\nFound: https://platformio.org/lib/show/68/TimeAlarms\nLibraryManager: Installing id=68 @ 0.0.0-alpha+sha.c291c1ddad\r\nDownloading\nDownloading\nUnpacking\nUnpacking\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 16, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 260, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 810, in update\n    self.install(name, latest, after_update=True)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 281, in install\n    force=force,\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 704, in install\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 131, in _install_from_piorepo\n    requirements,\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 499, in _install_from_url\n    return self._install_from_tmp_dir(_tmp_dir, requirements)\n  File \"c:\\users\\julio\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 542, in _install_from_tmp_dir\n    assert tmp_manifest[\"version\"] == requirements, mismatch_error\nAssertionError: Package version c291c1ddad doesn't satisfy requirements 0.0.0-alpha+sha.c291c1ddad\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Sorry for the issue. Fixed. Please try again.
