### ISSUE TITLE
Libraries: Could not update library

### ISSUE THREAD

**Issue by denn-gubsky** [platformio/platformio-home#958]
PIO Core Call Error: "Library Storage: /home/denn/workspace/arduino/libraries\nUpdating AT24C1024                       @ 1c6bba12f6     [0.0.0-alpha+sha.1c6bba12f6]\nUninstalling AT24C1024 @ 1c6bba12f6: \t[OK]\nLooking for AT24C1024 library in registry\nFound: https://platformio.org/lib/show/2438/AT24C1024\nLibraryManager: Installing id=2438 @ 0.0.0-alpha+sha.1c6bba12f6\n\n\nError: Traceback (most recent call last):\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 538, in _install_from_tmp_dir\n    assert tmp_semver and tmp_semver in semantic_version.SimpleSpec(\nAssertionError: Package version 1c6bba12f6 doesn't satisfy requirements 0.0.0-alpha+sha.1c6bba12f6\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/commands/lib.py\", line 260, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 810, in update\n    self.install(name, latest, after_update=True)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/lib.py\", line 275, in install\n    pkg_dir = BasePkgManager.install(\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 704, in install\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/lib.py\", line 126, in _install_from_piorepo\n    return self._install_from_url(\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 499, in _install_from_url\n    return self._install_from_tmp_dir(_tmp_dir, requirements)\n  File \"/home/denn/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 542, in _install_from_tmp_dir\n    assert tmp_manifest[\"version\"] == requirements, mismatch_error\nAssertionError: Package version 1c6bba12f6 doesn't satisfy requirements 0.0.0-alpha+sha.1c6bba12f6\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Sorry for the issue. Fixed. Please try again.
