### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by A29sTech** [platformio/platformio-home#96]
PIO Core Call Error: "The current working directory C:\\Users\\A29\\Documents\\PlatformIO\\Projects\\as will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\A29\\Documents\\PlatformIO\\Projects\\as\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing node32s (platform: espressif32; board: node32s; framework: arduino)\r\n--------------------------------------------------------------------------------\r\ntoolchain-xtensa32 @ 2.50200.80 has been successfully installed!\r\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\r\ntool-esptoolpy @ 1.20600.0 is already installed\r\nPackageManager: Installing framework-arduinoespressif32 @ ~2.10004.191002\r\nThe platform 'espressif32' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n========================= [SUCCESS] Took 79.34 seconds ========================="

**Comment by ivankravets** [comment]
Please restart VSCode, it should work now.
