### ISSUE TITLE
Error occurred while requesting content from https://raw.githubusercontent.com/milesburton/Arduino-Temperature-Control-Library/master/library.json

### ISSUE THREAD

**Issue by wangmings** [platformio/platformio-home#961]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /milesburton/Arduino-Temperature-Control-Library/master/library.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x105a0fb00>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by valeros** [comment]
Looks like there was a temporarily issue with Github infrastructure, are you able to reproduce the issue again?
