### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by danilloaguiar** [platformio/platformio-home#966]
PIO Core Call Error: "The current working directory /home/danillo/Documentos/3 - Projects/ESP32-IDF-Overview-ADC/Analog to Digital Converter will be used for the project.\n\nThe next files/directories have been created in /home/danillo/Documentos/3 - Projects/ESP32-IDF-Overview-ADC/Analog to Digital Converter\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: espidf)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32cam.html\nPLATFORM: Espressif 32 1.12.4 > AI Thinker ESP32-CAM\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\nPACKAGES: \n - framework-espidf 3.40001.200521 (4.0.1) \n - tool-cmake 3.16.4 \n - tool-esptoolpy 1.20600.0 (2.6.0) \n - tool-ninja 1.7.1 \n - toolchain-esp32ulp 1.22851.190618 (2.28.51) \n - toolchain-xtensa32 2.80200.200226 (8.2.0)\nError: Detected a whitespace character in project paths.\n========================== [FAILED] Took 0.37 seconds =========================="

**Comment by valeros** [comment]
Looks like you have a whitespace character in the path to your project. Starting with ESP-IDF v4.0 it's not allowed.
