### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by damanbedi2011** [platformio/platformio-home#973]
PIO Core Call Error: "PlatformManager: Installing \u001b[36mplatform-quectel\u001b[0m\nquectel @ 1b8c472 has been successfully installed!\nPackageManager: Installing \u001b[36mtoolchain-gcc-ec2x\u001b[0m\nDownloading...\nUnpacking...\ntoolchain-gcc-ec2x @ 1.0.0 has been successfully installed!\nPackageManager: Installing \u001b[36mframework-quectel\u001b[0m\nframework-quectel @ 591c533 has been successfully installed!\nPackageManager: Installing \u001b[36mtoolchain-gccarmnoneeabi\u001b[0m @ =1.70201.0\nDownloading...\nUnpacking...\ntoolchain-gccarmnoneeabi @ 1.70201.0 has been successfully installed!\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 325, in platform_install\n    force=force,\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 107, in install\n    return self.cleanup_packages(list(p.packages))\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 167, in cleanup_packages\n    p = PlatformFactory.newPlatform(manifest[\"__pkg_dir\"])\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 273, in newPlatform\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 562, in __init__\n    self._manifest = fs.load_json(manifest_path)\n  File \"c:\\users\\ripdaman singh\\.platformio\\penv\\lib\\site-packages\\platformio\\fs.py\", line 53, in load_json\n    with open(file_path, \"r\") as f:\nIOError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Ripdaman Singh\\\\.platformio\\\\platforms\\\\framework-quectel\\\\platform.json'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by valeros** [comment]
`C:\\Users\\Ripdaman Singh\\.platformio\\platforms` folder is meant to contain only platform directories. Please delete ``C:\\Users\\Ripdaman Singh\\.platformio\\platforms\\framework-quectel`` folder.
