### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by 11722461** [platformio/platformio-home#977]
PIO Core Call Error: "The current working directory C:\\Users\\moham\\Documents\\PlatformIO\\Projects\\CAPSTONE_PROJECT will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\moham\\Documents\\PlatformIO\\Projects\\CAPSTONE_PROJECT\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing atmelsam\r\natmelsam @ 4.5.1 has been successfully installed!\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ ~1.70201.0\r\ntoolchain-gccarmnoneeabi @ 1.70201.0 has been successfully installed!\r\nThe platform 'atmelsam' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing dueUSB (platform: atmelsam; board: dueUSB; framework: simba)\r\n--------------------------------------------------------------------------------\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ >=1.40803.0,<1.40805.0\r\ntoolchain-gccarmnoneeabi @ 1.40804.0 has been successfully installed!\r\nPackageManager: Installing framework-simba @ >=7.0.0\r\nframework-simba @ 15.0.3 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/dueUSB.html\r\nPLATFORM: Atmel SAM 4.5.1 > Arduino Due (USB Native Port)\r\nHARDWARE: AT91SAM3X8E 84MHz, 96KB RAM, 512KB Flash\r\nDEBUG: Current (atmel-ice) External (atmel-ice, blackmagic, jlink, stlink)\r\nPACKAGES: \r\n - framework-simba 15.0.3 \r\n - toolchain-gccarmnoneeabi 1.40804.0 (4.8.4)\r\nValueError: BOARD dueUSB is not supported by Simba.:\r\n  File \"C:\\Users\\moham\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 168:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\moham\\.platformio\\platforms\\atmelsam\\builder\\main.py\", line 128:\r\n    target_elf = env.BuildProgram()\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\moham\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 61:\r\n    env.ProcessProgramDeps()\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\moham\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 118:\r\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\moham\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 330:\r\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 660:\r\n    return method(*args, **kw)\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\moham\\.platformio\\platforms\\atmelsam\\builder\\frameworks\\simba.py\", line 60:\r\n    [env.subst(join(\"$PLATFORMFW_DIR\", \"make\", \"platformio.sconscript\"))])\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 660:\r\n    return method(*args, **kw)\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\moham\\.platformio\\packages\\framework-simba\\make\\platformio.sconscript\", line 4187:\r\n    raise ValueError(\"BOARD {} is not supported by Simba.\".format(board))\r\n========================= [FAILED] Took 542.68 seconds ========================="

**Comment by valeros** [comment]
Looks like `dueUSB` is not properly remapped in the Simba build script https://github.com/eerimoq/simba/blob/master/make/platformio/platformio.py#L62, please use `due` board instead.
