### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by Valmach** [platformio/platformio-home#980]
PIO Core Call Error: "The current working directory /home/valmach/Documents/PlatformIO/Projects/ESP32 Development  will be used for the project.\n\nThe next files/directories have been created in /home/valmach/Documents/PlatformIO/Projects/ESP32 Development \ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nFileNotFoundError: [Errno 2] No such file or directory: '/home/valmach/Documents/PlatformIO/Projects/ESP32 Development':\n  File \"/home/valmach/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py\", line 159:\n    env.LoadPioPlatform()\n  File \"/home/valmach/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/home/valmach/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/pioplatform.py\", line 94:\n    board_config = env.BoardConfig()\n  File \"/home/valmach/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 219:\n    return self.method(*nargs, **kwargs)\n  File \"/home/valmach/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/pioplatform.py\", line 43:\n    with fs.cd(env.subst(\"$PROJECT_DIR\")):\n  File \"/home/valmach/.platformio/penv/lib/python3.8/site-packages/platformio/fs.py\", line 36:\n    os.chdir(self.new_path)\n========================== [FAILED] Took 0.39 seconds =========================="

**Comment by valeros** [comment]
For some reason the project folder `/home/valmach/Documents/PlatformIO/Projects/ESP32 Development` wasn't created. Is this folder present is the file system?
