### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by JSCLadon** [platformio/platformio-home#99]
PIO Core Call Error: "Library Storage: C:\\Users\\JohannesSchnitzler\\.platformio\\lib\r\nLooking for stdlib.h library in registry\r\n\n\nError: Library `{'name': 'stdlib.h', 'requirements': None}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'name': 'stdlib.h', 'requirements': None}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
> stdlib.h

Unknonwl ibrary
